name: cryptowallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+8

environment:
  sdk: ">=2.11.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  bip39: ^1.0.6
  flutter_js: ^0.5.0+6
  bip32: ^2.0.0
  http: ^0.13.4
  intl: ^0.17.0
  web3dart: ^2.3.3
  qr_flutter: ^4.0.0
  share: ^2.0.4
  local_auth: ^1.1.11
  url_launcher: ^6.0.20
  wallet_connect: ^1.0.4
  bitcoin_flutter: ^2.0.2
  percent_indicator: ^3.4.0
  flutter_svg: ^1.0.0
  page_transition: ^2.0.5
  hex: ^0.2.0
  ed25519_hd_key: ^2.2.0
  rename: 2.0.1
  flutter_local_notifications: 9.0.0
  form_field_validator: ^1.0.1
  font_awesome_flutter: 8.8.1
  intl_phone_number_input: ^0.7.0+2
  qr_code_scanner: ^1.0.1
  image_picker: ^0.8.4+5
  awesome_dialog: ^2.1.3
  validators: ^3.0.0
  device_info_plus: ^3.2.3
  path: ^1.8.0
  prompt_dialog: ^1.0.9
  eth_sig_util: ^0.0.7
  flutter_inappwebview: 6.0.0-beta.11
  scan: ^1.6.0
  path_provider: ^2.0.11
  file_picker: 4.6.1
  cached_network_image: ^3.2.0
  decimal: ^2.2.0
  flutter_pin_code_fields: ^1.1.0
  pinput: ^2.2.11
  html: ^0.15.0
  flutter_windowmanager: 0.2.0
  screenshot_callback: ^2.0.2
  mime: ^1.0.2
  flutter_countdown_timer: ^4.1.0
  flutter_secure_storage: ^6.0.0
  solana: ^0.26.0
  worker_manager: ^4.4.6
  shimmer: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  package_info_plus: 1.0.6
  cardano_wallet_sdk: ^0.1.0-alpha.12
  bs58check: ^1.0.2
  bech32: ^0.1.2
  sha3: ^0.2.0
  charts_flutter: ^0.12.0
  stellar_flutter_sdk: ^1.3.7
  oxidized: ^5.2.0
  blockfrost: ^1.0.0-dev.8
  receive_sharing_intent: ^1.4.5
  ntcdcrypto: ^0.2.0
  firebase_crashlytics: ^3.0.4
  firebase_core: ^2.1.1
  firebase_analytics: ^10.0.4
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11
  flutter_dotenv: ^5.0.2
  get: ^4.6.5
  flutter_phoenix: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  change_app_package_name: ^0.1.3

dependency_overrides:
  permission_handler: ^10.2.0
  pointycastle: ^3.4.0
  convert: ^3.0.0
  bip32: ^2.0.0
  hex: ^0.2.0
  ffi: ^1.0.0
  collection: 1.15.0
  http: ^0.13.4
  pinenacl: ^0.3.3
  quiver: ^3.0.1+1
  xml: ^5.0.0
  petitparser: ^4.0.0
flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/currency_flags/
    - assets/images/
    - dappBrowser/
    - js/
    - json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:Ï€
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
