
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.equihash]
audit-as-crates-io = true

[policy.f4jumble]
audit-as-crates-io = true

[policy.zcash_address]
audit-as-crates-io = true

[policy.zcash_client_backend]
audit-as-crates-io = true

[policy.zcash_client_sqlite]
audit-as-crates-io = true

[policy.zcash_encoding]
audit-as-crates-io = true

[policy.zcash_extensions]
audit-as-crates-io = true

[policy.zcash_history]
audit-as-crates-io = true

[policy.zcash_keys]
audit-as-crates-io = true

[policy.zcash_primitives]
audit-as-crates-io = true

[policy.zcash_proofs]
audit-as-crates-io = true

[policy.zcash_protocol]
audit-as-crates-io = true

[policy.zip321]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.aead]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.allocator-api2]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.arrayvec]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.assert_matches]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.78"
criteria = "safe-to-deploy"

[[exemptions.axum]]
version = "0.6.20"
criteria = "safe-to-deploy"

[[exemptions.axum-core]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.69"
criteria = "safe-to-deploy"

[[exemptions.bech32]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.bellman]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.blake2b_simd]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.blake2s_simd]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.bls12_381]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.bs58]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cbc]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.chacha20]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.chacha20poly1305]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.cipher]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "3.2.25"
criteria = "safe-to-run"

[[exemptions.cpp_demangle]]
version = "0.4.3"
criteria = "safe-to-run"

[[exemptions.cpufeatures]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-channel]]
version = "0.5.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.15"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.19"
criteria = "safe-to-deploy"

[[exemptions.daggy]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.fallible-iterator]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.fallible-streaming-iterator]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.ff]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.findshlibs]]
version = "0.10.2"
criteria = "safe-to-run"

[[exemptions.fixed-hash]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.fpe]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.29"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.29"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.29"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.29"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.28.1"
criteria = "safe-to-deploy"

[[exemptions.group]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.gumdrop]]
version = "0.8.1"
criteria = "safe-to-run"

[[exemptions.gumdrop_derive]]
version = "0.8.1"
criteria = "safe-to-run"

[[exemptions.h2]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.hdwallet]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.home]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.27"
criteria = "safe-to-deploy"

[[exemptions.hyper-timeout]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.3"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.2.6"
criteria = "safe-to-deploy"

[[exemptions.inferno]]
version = "0.11.17"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.65"
criteria = "safe-to-deploy"

[[exemptions.jubjub]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.154"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.libsqlite3-sys]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.11"
criteria = "safe-to-run"

[[exemptions.matchit]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.6.4"
criteria = "safe-to-deploy"

[[exemptions.memmap2]]
version = "0.5.10"
criteria = "safe-to-run"

[[exemptions.memuse]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.minreq]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.multimap]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.nonempty]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.num-format]]
version = "0.4.4"
criteria = "safe-to-run"

[[exemptions.num_cpus]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.32.1"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.os_str_bytes]]
version = "6.6.1"
criteria = "safe-to-run"

[[exemptions.pairing]]
version = "0.23.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.9"
criteria = "safe-to-run"

[[exemptions.pasta_curves]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.petgraph]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.5"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.poly1305]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.pprof]]
version = "0.11.1"
criteria = "safe-to-run"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.prettyplease]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.primitive-types]]
version = "0.12.2"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.3.1"
criteria = "safe-to-deploy"

[[exemptions.prost]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.prost-build]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.prost-types]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.quick-error]]
version = "1.2.3"
criteria = "safe-to-deploy"

[[exemptions.quick-xml]]
version = "0.26.0"
criteria = "safe-to-run"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.reddsa]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.4.1"
criteria = "safe-to-run"

[[exemptions.regex]]
version = "1.10.2"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.rgb]]
version = "0.8.37"
criteria = "safe-to-run"

[[exemptions.ring]]
version = "0.16.20"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.8"
criteria = "safe-to-deploy"

[[exemptions.ripemd]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.rusqlite]]
version = "0.29.0"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.34"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.21.8"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.101.7"
criteria = "safe-to-deploy"

[[exemptions.rusty-fork]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.15"
criteria = "safe-to-run"

[[exemptions.schemer]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.schemer-rusqlite]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.sct]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.secp256k1]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.secp256k1-sys]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.secrecy]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.str_stack]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.symbolic-common]]
version = "10.2.1"
criteria = "safe-to-run"

[[exemptions.symbolic-demangle]]
version = "10.2.1"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.53"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.8.1"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.23"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.35.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-io-timeout]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.tonic]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.tonic-build]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.40"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.27"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.32"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.uint]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.wait-timeout]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.4.0"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.88"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.88"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.65"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.4.2"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.wyz]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.xdg]]
version = "2.5.2"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize_derive]]
version = "1.4.2"
criteria = "safe-to-deploy"
