name: youtube_player_flutter_example
description: Demonstrates how to use the youtube_player_flutter plugin.
version: 7.0.0
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  youtube_player_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ypf.png

  