# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/rust/rust_static_library.gni")

source_set("zk_proof") {
  sources = [
    "zk_proof.h",
    "zk_proof.cc",
    "tls_info/tls_data_store.h",
    "tls_info/tls_data_store.cc",
  ]

  deps = [
    ":rust_zk_proof",
    "//base",
  ]

  public_deps = [
    "//base",
  ]
 
}

rust_static_library("rust_zk_proof") {
  crate_root = "rust/src/lib.rs"
  sources = [
    "rust/src/lib.rs",
  ]
  
  cxx_bindings = [ "rust/src/lib.rs" ]
  
  deps = [
    "//third_party/rust/ark_bn254/v0_5:lib",
    "//third_party/rust/ark_groth16/v0_5:lib",
    "//third_party/rust/ark_ff/v0_5:lib",
    "//third_party/rust/ark_ec/v0_5:lib",
    "//third_party/rust/ark_std/v0_5:lib",
    "//third_party/rust/ark_serialize/v0_5:lib",
    "//third_party/rust/ark_relations/v0_5:lib",
    "//third_party/rust/ark_snark/v0_5:lib",
    "//third_party/rust/serde/v1:lib",
    "//third_party/rust/serde_json/v1:lib",
    "//third_party/rust/cxx/v1:lib",
    "//third_party/rust/sha2/v0_10:lib",
    "//third_party/rust/num_bigint/v0_4:lib",
    "//third_party/rust/base64/v0_13:lib",
  ]
}
