/* Copyright (c) 2020 The Wootz Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef COMPONENTS_WOOTZ_WALLET_BROWSER_WOOTZ_WALLET_CONSTANTS_H_
#define COMPONENTS_WOOTZ_WALLET_BROWSER_WOOTZ_WALLET_CONSTANTS_H_

#include <string>
#include <vector>

#include "components/wootz_wallet/common/wootz_wallet_types.h"
#include "components/grit/wootz_components_strings.h"
#include "ui/base/webui/web_ui_util.h"

namespace wootz_wallet {

inline constexpr char kWootzServicesKeyHeader[] = "x-wootz-key";

constexpr uint256_t kDefaultSendEthGasLimit = 21000;
constexpr uint256_t kDefaultERC20TransferGasLimit = 300000;
constexpr uint256_t kDefaultERC721TransferGasLimit = 800000;
constexpr uint256_t kDefaultERC20ApproveGasLimit = 300000;

constexpr int32_t kAutoLockMinutesMin = 1;
constexpr int32_t kAutoLockMinutesMax = 10080;

constexpr int32_t kAssetDiscoveryMinutesPerRequest = 1;

inline constexpr char kWalletBaseDirectory[] = "WootzWallet";
inline constexpr char kImageSourceHost[] = "erc-token-images";
inline constexpr char kRampBaseUrl[] = "https://app.ramp.network";
inline constexpr char kOffRampEnabledFlows[] = "OFFRAMP";
inline constexpr char kOnRampEnabledFlows[] = "ONRAMP";
inline constexpr char kOnRampID[] = "8yxja8782as5essk2myz3bmh4az6gpq4nte9n2gf";
inline constexpr char kOffRampID[] = "y57zqta99ohs7o2paf4ak6vpfb7wf8ubj9krwtwe";
inline constexpr char kSardineStorefrontBaseURL[] = "https://crypto.sardine.ai";
inline constexpr char kSardineClientTokensURL[] =
    "https://api.sardine.ai/v1/auth/client-tokens";
inline constexpr char kTransakURL[] = "https://global.transak.com/";
inline constexpr char kTransakApiKey[] = "985d14f0-4cf5-4a4c-8917-78107620d3b7";
inline constexpr char kCoinbaseURL[] = "https://pay.coinbase.com";
inline constexpr char kCoinbaseAppId[] = "8072ff71-8469-4fef-9404-7c905e2359c9";
inline constexpr char kSimpleHashUrl[] = "https://api.simplehash.com";
inline constexpr char kSimpleHashWootzProxyUrl[] =
    "https://simplehash.wallet.wootz.com";

inline constexpr size_t kSimpleHashMaxBatchSize = 50;

inline constexpr webui::LocalizedString kLocalizedStrings[] = {
    {"wootzWalletWatchOnly", IDS_WOOTZ_WALLET_WATCH_ONLY},
    {"wootzWalletNftSymbolFieldExplanation",
     IDS_WOOTZ_WALLET_NFT_SYMBOL_FIELD_EXPLANATION},
    {"wootzWalletNftNameFieldExplanation",
     IDS_WOOTZ_WALLET_NFT_NAME_FIELD_EXPLANATION},
    {"wootzWalletExempliGratia", IDS_WOOTZ_WALLET_EXEMPLI_GRATIA},
    {"wootzWalletUnownedNftAlert", IDS_WOOTZ_WALLET_UNOWNED_NFT_ALERT},
    {"wootzWalletWatchThisNft", IDS_WOOTZ_WALLET_WATCH_THIS_NFT},
    {"wootzWalletFetchNftMetadataError",
     IDS_WOOTZ_WALLET_FETCH_NFT_METADATA_ERROR},
    {"wootzWalletWhatIsAnNftTokenId", IDS_WOOTZ_WALLET_WHAT_IS_AN_NFT_TOKEN_ID},
    {"wootzWalletWhatIsAnNftContractAddress",
     IDS_WOOTZ_WALLET_WHAT_IS_AN_NFT_CONTRACT_ADDRESS},
    {"wootzWalletGroupByCollection", IDS_WOOTZ_WALLET_GROUP_BY_COLLECTION},
    {"wootzWalletAddNftModalDescription",
     IDS_WOOTZ_WALLET_ADD_NFT_MODAL_DESCRIPTION},
    {"wootzWalletHideNotOwnedNfTs", IDS_WOOTZ_WALLET_HIDE_NOT_OWNED_NF_TS},
    {"wootzWalletNoRoutesFound", IDS_WOOTZ_WALLET_NO_ROUTES_FOUND},
    {"wootzWalletPrivateKeyImportType",
     IDS_WOOTZ_WALLET_PRIVATE_KEY_IMPORT_TYPE},
    {"wootzWalletEnterPasswordIfApplicable",
     IDS_WOOTZ_WALLET_ENTER_PASSWORD_IF_APPLICABLE},
    {"wootzWalletFoundIssues", IDS_WOOTZ_WALLET_FOUND_ISSUES},
    {"wootzWalletContract", IDS_WOOTZ_WALLET_CONTRACT},
    {"wootzWalletFoundRisks", IDS_WOOTZ_WALLET_FOUND_RISKS},
    {"wootzWalletProceedButton", IDS_WOOTZ_WALLET_PROCEED_BUTTON},
    {"wootzWalletUntrustedRequestWarning",
     IDS_WOOTZ_WALLET_UNTRUSTED_REQUEST_WARNING},
    {"wootzWalletRiskOfLossAction", IDS_WOOTZ_WALLET_RISK_OF_LOSS_ACTION},
    {"wootzWalletTestNetworkAccount", IDS_WOOTZ_WALLET_TEST_NETWORK_ACCOUNT},
    {"wootzWalletPopular", IDS_WOOTZ_WALLET_POPULAR},
    {"wootzWalletFeatured", IDS_WOOTZ_WALLET_FEATURED},
    {"wootzWalletShowTestnets", IDS_WOOTZ_WALLET_SHOW_TESTNETS},
    {"wootzWalletChooseChainsToUse", IDS_WOOTZ_WALLET_CHOOSE_CHAINS_TO_USE},
    {"wootzWalletSupportedNetworks", IDS_WOOTZ_WALLET_SUPPORTED_NETWORKS},
    {"wootzWalletAddNetworksAnytimeInSettings",
     IDS_WOOTZ_WALLET_ADD_NETWORKS_ANYTIME_IN_SETTINGS},
    {"wootzWalletContinueWithXItems", IDS_WOOTZ_WALLET_CONTINUE_WITH_X_ITEMS},
    {"wootzWalletTopNavExplore", IDS_WOOTZ_WALLET_TOP_NAV_EXPLORE},
    {"wootzWalletWeb3", IDS_WOOTZ_WALLET_WEB_3},
    {"wootzWalletSpenderAddress", IDS_WOOTZ_WALLET_SPENDER_ADDRESS},
    {"wootzWalletTokenIsVerifiedByLists",
     IDS_WOOTZ_WALLET_TOKEN_IS_VERIFIED_BY_LISTS},
    {"wootzWalletTokenIsVerified", IDS_WOOTZ_WALLET_TOKEN_IS_VERIFIED},
    {"wootzWalletTokenIsUnverified", IDS_WOOTZ_WALLET_TOKEN_IS_UNVERIFIED},
    {"wootzWalletUnlimitedAssetAmount",
     IDS_WOOTZ_WALLET_UNLIMITED_ASSET_AMOUNT},
    {"wootzWalletFrom", IDS_WOOTZ_WALLET_FROM},
    {"wootzWalletReceive", IDS_WOOTZ_WALLET_RECEIVE},
    {"wootzWalletChangeAnytimeInSettings",
     IDS_WOOTZ_WALLET_CHANGE_ANYTIME_IN_SETTINGS},
    {"wootzWalletAvailable", IDS_WOOTZ_WALLET_AVAILABLE},
    {"wootzWalletAvailableBalanceDescription",
     IDS_WOOTZ_WALLET_AVAILABLE_BALANCE_DESCRIPTION},
    {"wootzWalletPending", IDS_WOOTZ_WALLET_PENDING},
    {"wootzWalletPendingBalanceDescription",
     IDS_WOOTZ_WALLET_PENDING_BALANCE_DESCRIPTION},
    {"wootzWalletTotalBalanceDescription",
     IDS_WOOTZ_WALLET_TOTAL_BALANCE_DESCRIPTION},
    {"wootzWalletUnavailableBalances", IDS_WOOTZ_WALLET_UNAVAILABLE_BALANCES},
    {"wootzWalletTransactionSimulationTerms",
     IDS_WOOTZ_WALLET_TRANSACTION_SIMULATION_TERMS},
    {"wootzWalletButtonEnable", IDS_WOOTZ_WALLET_BUTTON_ENABLE},
    {"wootzWalletButtonNoThanks", IDS_WOOTZ_WALLET_BUTTON_NO_THANKS},
    {"wootzWalletTransactionSimulationDetectPhishing",
     IDS_WOOTZ_WALLET_TRANSACTION_SIMULATION_DETECT_PHISHING},
    {"wootzWalletTransactionSimulationDetectMalicious",
     IDS_WOOTZ_WALLET_TRANSACTION_SIMULATION_DETECT_MALICIOUS},
    {"wootzWalletTransactionSimulationSeeEstimates",
     IDS_WOOTZ_WALLET_TRANSACTION_SIMULATION_SEE_ESTIMATES},
    {"wootzWalletEnableEnhancedTransactionDetailsTitle",
     IDS_WOOTZ_WALLET_ENABLE_ENHANCED_TRANSACTION_DETAILS_TITLE},
    {"wootzWalletNetworkFees", IDS_WOOTZ_WALLET_NETWORK_FEES},
    {"wootzWalletSolanaSysvarRentProgram",
     IDS_WOOTZ_WALLET_SOLANA_SYSVAR_RENT_PROGRAM},
    {"wootzWalletSolanaMetaDataProgram",
     IDS_WOOTZ_WALLET_SOLANA_META_DATA_PROGRAM},
    {"wootzWalletSolanaAssociatedTokenProgram",
     IDS_WOOTZ_WALLET_SOLANA_ASSOCIATED_TOKEN_PROGRAM},
    {"wootzWalletSolanaTokenProgram", IDS_WOOTZ_WALLET_SOLANA_TOKEN_PROGRAM},
    {"wootzWalletTransactionHasFeeEstimatesError",
     IDS_WOOTZ_WALLET_TRANSACTION_HAS_FEE_ESTIMATES_ERROR},
    {"wootzWalletGasFeeLimitLowerThanBaseFeeWarning",
     IDS_WOOTZ_WALLET_GAS_FEE_LIMIT_LOWER_THAN_BASE_FEE_WARNING},
    {"wootzWalletTokenMintAddress", IDS_WOOTZ_WALLET_TOKEN_MINT_ADDRESS},
    {"wootzWalletActivity", IDS_WOOTZ_WALLET_ACTIVITY},
    {"wootzWalletTokenDecimalsIsRequiredError",
     IDS_WOOTZ_WALLET_TOKEN_DECIMALS_IS_REQUIRED_ERROR},
    {"wootzWalletTokenSymbolIsRequiredError",
     IDS_WOOTZ_WALLET_TOKEN_SYMBOL_IS_REQUIRED_ERROR},
    {"wootzWalletInvalidTokenContractAddressError",
     IDS_WOOTZ_WALLET_INVALID_TOKEN_CONTRACT_ADDRESS_ERROR},
    {"wootzWalletTokenNameIsRequiredError",
     IDS_WOOTZ_WALLET_TOKEN_NAME_IS_REQUIRED_ERROR},
    {"wootzWalletNetworkIsRequiredError",
     IDS_WOOTZ_WALLET_NETWORK_IS_REQUIRED_ERROR},
    {"wootzWalletEnterYourPasswordToStartBackup",
     IDS_WOOTZ_WALLET_ENTER_YOUR_PASSWORD_TO_START_BACKUP},
    {"wootzWalletEnterAPasswordToContinue",
     IDS_WOOTZ_WALLET_ENTER_A_PASSWORD_TO_CONTINUE},
    {"wootzWalletNoTransactionsYetDescription",
     IDS_WOOTZ_WALLET_NO_TRANSACTIONS_YET_DESCRIPTION},
    {"wootzWalletNoTransactionsYet", IDS_WOOTZ_WALLET_NO_TRANSACTIONS_YET},
    {"wootzWalletInvalidMnemonicError", IDS_WALLET_INVALID_MNEMONIC_ERROR},
    {"wootzWalletImportWalletTypeTitle",
     IDS_WOOTZ_WALLET_IMPORT_WALLET_TYPE_TITLE},
    {"wootzWalletImportWalletTypeHotWalletTitle",
     IDS_WOOTZ_WALLET_IMPORT_WALLET_TYPE_HOT_WALLET_TITLE},
    {"wootzWalletImportWalletTypeHotWalletDescription",
     IDS_WOOTZ_WALLET_IMPORT_WALLET_TYPE_HOT_WALLET_DESCRIPTION},
    {"wootzWalletImportWalletTypeHardwareWalletTitle",
     IDS_WOOTZ_WALLET_IMPORT_WALLET_TYPE_HARDWARE_WALLET_TITLE},
    {"wootzWalletImportWalletTypeHardwareWalletDescription",
     IDS_WOOTZ_WALLET_IMPORT_WALLET_TYPE_HARDWARE_WALLET_DESCRIPTION},
    {"wootzWalletRecoveryPhraseLengthError",
     IDS_WOOTZ_WALLET_RECOVERY_PHRASE_LENGTH_ERROR},
    {"wootzWalletOrdinalTwentyFourth", IDS_WOOTZ_WALLET_ORDINAL_TWENTY_FOURTH},
    {"wootzWalletOrdinalTwentyThird", IDS_WOOTZ_WALLET_ORDINAL_TWENTY_THIRD},
    {"wootzWalletOrdinalTwentySecond", IDS_WOOTZ_WALLET_ORDINAL_TWENTY_SECOND},
    {"wootzWalletOrdinalTwentyFirst", IDS_WOOTZ_WALLET_ORDINAL_TWENTY_FIRST},
    {"wootzWalletOrdinalTwentieth", IDS_WOOTZ_WALLET_ORDINAL_TWENTIETH},
    {"wootzWalletOrdinalNineteenth", IDS_WOOTZ_WALLET_ORDINAL_NINETEENTH},
    {"wootzWalletOrdinalEighteenth", IDS_WOOTZ_WALLET_ORDINAL_EIGHTEENTH},
    {"wootzWalletOrdinalSeventeenth", IDS_WOOTZ_WALLET_ORDINAL_SEVENTEENTH},
    {"wootzWalletOrdinalSixteenth", IDS_WOOTZ_WALLET_ORDINAL_SIXTEENTH},
    {"wootzWalletOrdinalFifteenth", IDS_WOOTZ_WALLET_ORDINAL_FIFTEENTH},
    {"wootzWalletOrdinalFourteenth", IDS_WOOTZ_WALLET_ORDINAL_FOURTEENTH},
    {"wootzWalletOrdinalThirteenth", IDS_WOOTZ_WALLET_ORDINAL_THIRTEENTH},
    {"wootzWalletOrdinalTwelfth", IDS_WOOTZ_WALLET_ORDINAL_TWELFTH},
    {"wootzWalletOrdinalSuffixOther", IDS_WOOTZ_WALLET_ORDINAL_SUFFIX_OTHER},
    {"wootzWalletOrdinalSuffixFew", IDS_WOOTZ_WALLET_ORDINAL_SUFFIX_FEW},
    {"wootzWalletOrdinalSuffixTwo", IDS_WOOTZ_WALLET_ORDINAL_SUFFIX_TWO},
    {"wootzWalletOrdinalSuffixOne", IDS_WOOTZ_WALLET_ORDINAL_SUFFIX_ONE},
    {"wootzWalletOrdinalEleventh", IDS_WOOTZ_WALLET_ORDINAL_ELEVENTH},
    {"wootzWalletOrdinalTenth", IDS_WOOTZ_WALLET_ORDINAL_TENTH},
    {"wootzWalletOrdinalNinth", IDS_WOOTZ_WALLET_ORDINAL_NINTH},
    {"wootzWalletOrdinalEighth", IDS_WOOTZ_WALLET_ORDINAL_EIGHTH},
    {"wootzWalletOrdinalSeventh", IDS_WOOTZ_WALLET_ORDINAL_SEVENTH},
    {"wootzWalletOrdinalSixth", IDS_WOOTZ_WALLET_ORDINAL_SIXTH},
    {"wootzWalletOrdinalFifth", IDS_WOOTZ_WALLET_ORDINAL_FIFTH},
    {"wootzWalletOrdinalFourth", IDS_WOOTZ_WALLET_ORDINAL_FOURTH},
    {"wootzWalletOrdinalSecond", IDS_WOOTZ_WALLET_ORDINAL_SECOND},
    {"wootzWalletRemoveAccountModalTitle",
     IDS_WOOTZ_WALLET_REMOVE_ACCOUNT_MODAL_TITLE},
    {"wootzWalletViewDecodedMessage", IDS_WOOTZ_WALLET_VIEW_DECODED_MESSAGE},
    {"wootzWalletViewEncodedMessage", IDS_WOOTZ_WALLET_VIEW_ENCODED_MESSAGE},
    {"wootzWalletNonAsciiCharactersInMessageWarning",
     IDS_WOOTZ_WALLET_NON_ASCII_CHARACTERS_IN_MESSAGE_WARNING},
    {"wootzWalletEnterYourPassword", IDS_WOOTZ_WALLET_ENTER_YOUR_PASSWORD},
    {"wootzWalletEnterYourWootzWalletPassword",
     IDS_WOOTZ_WALLET_ENTER_YOUR_WOOTZ_WALLET_PASSWORD},
    {"wootzWalletClickToSwitch", IDS_WOOTZ_WALLET_CLICK_TO_SWITCH},
    {"wootzWalletMultiChain", IDS_WOOTZ_WALLET_MULTI_CHAIN},
    {"wootzWalletPerksBrowserNative", IDS_WOOTZ_WALLET_PERKS_BROWSER_NATIVE},
    {"wootzWalletPerksTokens", IDS_WOOTZ_WALLET_PERKS_TOKENS},
    {"wootzWallet", IDS_WOOTZ_WALLET},
    {"wootzWalletSearchText", IDS_WOOTZ_WALLET_SEARCH_TEXT},
    {"wootzWalletSideNavCrypto", IDS_WOOTZ_WALLET_SIDE_NAV_CRYPTO},
    {"wootzWalletSideNavRewards", IDS_WOOTZ_WALLET_SIDE_NAV_REWARDS},
    {"wootzWalletSideNavCards", IDS_WOOTZ_WALLET_SIDE_NAV_CARDS},
    {"wootzWalletTopNavPortfolio", IDS_WOOTZ_WALLET_TOP_NAV_PORTFOLIO},
    {"wootzWalletTopTabPrices", IDS_WOOTZ_WALLET_TOP_TAB_PRICES},
    {"wootzWalletTopNavNFTS", IDS_WOOTZ_WALLET_TOP_NAV_N_F_T_S},
    {"wootzWalletTopNavAccounts", IDS_WOOTZ_WALLET_TOP_NAV_ACCOUNTS},
    {"wootzWalletTopNavMarket", IDS_WOOTZ_WALLET_TOP_NAV_MARKET},
    {"wootzWalletChartOneHour", IDS_WOOTZ_WALLET_CHART_ONE_HOUR},
    {"wootzWalletChartOneDay", IDS_WOOTZ_WALLET_CHART_ONE_DAY},
    {"wootzWalletChartOneWeek", IDS_WOOTZ_WALLET_CHART_ONE_WEEK},
    {"wootzWalletChartOneMonth", IDS_WOOTZ_WALLET_CHART_ONE_MONTH},
    {"wootzWalletChartThreeMonths", IDS_WOOTZ_WALLET_CHART_THREE_MONTHS},
    {"wootzWalletChartOneYear", IDS_WOOTZ_WALLET_CHART_ONE_YEAR},
    {"wootzWalletChartAllTime", IDS_WOOTZ_WALLET_CHART_ALL_TIME},
    {"wootzWalletChartOneHourAbbr", IDS_WOOTZ_WALLET_CHART_ONE_HOUR_ABBR},
    {"wootzWalletChartOneDayAbbr", IDS_WOOTZ_WALLET_CHART_ONE_DAY_ABBR},
    {"wootzWalletChartOneWeekAbbr", IDS_WOOTZ_WALLET_CHART_ONE_WEEK_ABBR},
    {"wootzWalletChartOneMonthAbbr", IDS_WOOTZ_WALLET_CHART_ONE_MONTH_ABBR},
    {"wootzWalletChartThreeMonthsAbbr",
     IDS_WOOTZ_WALLET_CHART_THREE_MONTHS_ABBR},
    {"wootzWalletChartOneYearAbbr", IDS_WOOTZ_WALLET_CHART_ONE_YEAR_ABBR},
    {"wootzWalletChartAllTimeAbbr", IDS_WOOTZ_WALLET_CHART_ALL_TIME_ABBR},
    {"wootzWalletAddCoin", IDS_WOOTZ_WALLET_ADD_COIN},
    {"wootzWalletBalance", IDS_WOOTZ_WALLET_BALANCE},
    {"wootzWalletPortfolioAssetNetworkDescription",
     IDS_WOOTZ_WALLET_PORTFOLIO_ASSET_NETWORK_DESCRIPTION},
    {"wootzWalletAccounts", IDS_WOOTZ_WALLET_ACCOUNTS},
    {"wootzWalletSubviewAccount", IDS_WOOTZ_WALLET_SUBVIEW_ACCOUNT},
    {"wootzWalletOwner", IDS_WOOTZ_WALLET_OWNER},
    {"wootzWalletTransactions", IDS_WOOTZ_WALLET_TRANSACTIONS},
    {"wootzWalletPrice", IDS_WOOTZ_WALLET_PRICE},
    {"wootzWalletBack", IDS_WOOTZ_WALLET_BACK},
    {"wootzWalletAddAccount", IDS_WOOTZ_WALLET_ADD_ACCOUNT},
    {"wootzWalletPoweredByCoinGecko", IDS_WOOTZ_WALLET_POWERED_BY_COIN_GECKO},
    {"wootzWalletBuy", IDS_WOOTZ_WALLET_BUY},
    {"wootzWalletSend", IDS_WOOTZ_WALLET_SEND},
    {"wootzWalletSwap", IDS_WOOTZ_WALLET_SWAP},
    {"wootzWalletBridge", IDS_WOOTZ_WALLET_BRIDGE},
    {"wootzWalletReset", IDS_WOOTZ_WALLET_RESET},
    {"wootzWalletSell", IDS_WOOTZ_WALLET_SELL},
    {"wootzWalletNotEnoughBalance", IDS_WOOTZ_WALLET_NOT_ENOUGH_BALANCE},
    {"wootzWalletChooseAssetToSend", IDS_WOOTZ_WALLET_CHOOSE_ASSET_TO_SEND},
    {"wootzWalletChooseAssetToSwap", IDS_WOOTZ_WALLET_CHOOSE_ASSET_TO_SWAP},
    {"wootzWalletEnterRecipientAddress",
     IDS_WOOTZ_WALLET_ENTER_RECIPIENT_ADDRESS},
    {"wootzWalletNotEnoughFunds", IDS_WOOTZ_WALLET_NOT_ENOUGH_FUNDS},
    {"wootzWalletSendHalf", IDS_WOOTZ_WALLET_SEND_HALF},
    {"wootzWalletSendMax", IDS_WOOTZ_WALLET_SEND_MAX},
    {"wootzWalletReviewOrder", IDS_WOOTZ_WALLET_REVIEW_ORDER},
    {"wootzWalletReviewSend", IDS_WOOTZ_WALLET_REVIEW_SEND},
    {"wootzWalletNoAvailableTokens", IDS_WOOTZ_WALLET_NO_AVAILIBLE_TOKENS},
    {"wootzWalletSearchTokens", IDS_WOOTZ_WALLET_SEARCH_TOKENS},
    {"wootzWalletSearchNFTs", IDS_WOOTZ_WALLET_SEARCH_NFTS},
    {"wootzWalletChooseAsset", IDS_WOOTZ_WALLET_CHOOSE_ASSET},
    {"wootzWalletOrdinalsWarningMessage",
     IDS_WOOTZ_WALLET_ORDINALS_WARNING_MESSAGE},
    {"wootzWalletUserUnderstandsLabel",
     IDS_WOOTZ_WALLET_USER_UNDERSTANDS_LABEL},
    {"wootzWalletChooseRecipient", IDS_WOOTZ_WALLET_CHOOSE_RECIPIENT},
    {"wootzWalletMyAddresses", IDS_WOOTZ_WALLET_MY_ADDRESSES},
    {"wootzWalletAddressOrDomainPlaceholder",
     IDS_WOOTZ_WALLET_ADDRESS_OR_DOMAIN_PLACEHOLDER},
    {"wootzWalletSendTo", IDS_WOOTZ_WALLET_SEND_TO},
    {"wootzWalletInvalidDomainExtension",
     IDS_WOOTZ_WALLET_INVALID_DOMAIN_EXTENSION},
    {"wootzWalletChooseAccount", IDS_WOOTZ_WALLET_CHOOSE_ACCOUNT},
    {"wootzWalletMarketPrice", IDS_WOOTZ_WALLET_MARKET_PRICE},
    {"wootzWalletOwned", IDS_WOOTZ_WALLET_OWNED},
    {"wootzWalletNotOwned", IDS_WOOTZ_WALLET_NOT_OWNED},
    {"wootzWalletAmount24H", IDS_WOOTZ_WALLET_AMOUNT_24H},
    {"wootzWalletChooseAssetToBridge", IDS_WOOTZ_WALLET_CHOOSE_ASSET_TO_BRIDGE},
    {"wootzWalletReviewSwap", IDS_WOOTZ_WALLET_REVIEW_SWAP},
    {"wootzWalletChooseQuoteProvider", IDS_WOOTZ_WALLET_CHOOSE_QUOTE_PROVIDER},
    {"wootzWalletQuoteProviderInfo", IDS_WOOTZ_WALLET_QUOTE_PROVIDER_INFO},
    {"wootzWalletNotAvailable", IDS_WOOTZ_WALLET_REVIEW_NOT_AVAILABLE},
    {"wootzWalletUpdate", IDS_WOOTZ_WALLET_REVIEW_UPDATE},
    {"wootzWalletProviderNotSupported",
     IDS_WOOTZ_WALLET_PROVIDER_NOT_SUPPORTED},
    {"wootzWalletChangeProvider", IDS_WOOTZ_WALLET_CHANGE_PROVIDER},
    {"wootzWalletRoute", IDS_WOOTZ_WALLET_ROUTE},
    {"wootzWalletMaxSlippage", IDS_WOOTZ_WALLET_MAX_SLIPPAGE},
    {"wootzWalletMaxSlippageDescription",
     IDS_WOOTZ_WALLET_SLIPPAGE_DESCRIPTION},
    {"wootzWalletPriceImpactDescription",
     IDS_WOOTZ_WALLET_PRICE_IMPACT_DESCRIPTION},
    {"wootzWalletSuggestedValues", IDS_WOOTZ_WALLET_SUGGESTED_VALUES},
    {"wootzWalletMainstreamAssetPairs",
     IDS_WOOTZ_WALLET_MAINSTREAM_ASSET_PAIRS},
    {"wootzWalletStablecoinPairs", IDS_WOOTZ_WALLET_STABLECOIN_PAIRS},
    {"wootzWalletOthers", IDS_WOOTZ_WALLET_OTHERS},
    {"wootzWalletSuggested", IDS_WOOTZ_WALLET_SUGGESTED},
    {"wootzWalletCustom", IDS_WOOTZ_WALLET_CUSTOM},
    {"wootzWalletEstTime", IDS_WOOTZ_WALLET_EST_TIME},
    {"wootzWalletExchangeRate", IDS_WOOTZ_WALLET_EXCHANGE_RATE},
    {"wootzWalletExchangeFor", IDS_WOOTZ_WALLET_EXCHANGE_FOR},
    {"wootzWalletRecipient", IDS_WOOTZ_WALLET_RECIPIENT},
    {"wootzWalletReviewBridge", IDS_WOOTZ_WALLET_REVIEW_BRIDGE},
    {"wootzWalletSlippageToleranceWarning",
     IDS_WOOTZ_WALLET_SLIPPAGE_TOLERANCE_WARNING},
    {"wootzWalletExpiresInTitle", IDS_WOOTZ_WALLET_EXPIRES_IN_TITLE},
    {"wootzWalletSendPlaceholder", IDS_WOOTZ_WALLET_SEND_PLACEHOLDER},
    {"wootzWalletSendNoURLPlaceholder",
     IDS_WOOTZ_WALLET_SEND_NO_URL_PLACEHOLDER},
    {"wootzWalletSwapDisclaimer", IDS_WOOTZ_WALLET_SWAP_DISCLAIMER},
    {"wootzWalletSwapDisclaimerDescription",
     IDS_WOOTZ_WALLET_SWAP_DISCLAIMER_DESCRIPTION},
    {"wootzWalletJupiterSwapDisclaimerDescription",
     IDS_WOOTZ_WALLET_JUPITER_SWAP_DISCLAIMER_DESCRIPTION},
    {"wootzWalletSwapFeesNotice", IDS_WOOTZ_WALLET_SWAP_FEES_NOTICE},
    {"wootzWalletDecimalPlacesError", IDS_WOOTZ_WALLET_DECIMAL_PLACES_ERROR},
    {"wootzWalletCreateAccountDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_DESCRIPTION},
    {"wootzWalletCreateAccountYes", IDS_WOOTZ_WALLET_CREATE_ACCOUNT_YES},
    {"wootzWalletCreateAccountNo", IDS_WOOTZ_WALLET_CREATE_ACCOUNT_NO},
    {"wootzWalletButtonContinue", IDS_WOOTZ_WALLET_BUTTON_CONTINUE},
    {"wootzWalletButtonNext", IDS_WOOTZ_WALLET_BUTTON_NEXT},
    {"wootzWalletButtonVerifyPhrase", IDS_WOOTZ_WALLET_BUTTON_GOT_IT},
    {"wootzWalletButtonCopy", IDS_WOOTZ_WALLET_BUTTON_COPY},
    {"wootzWalletButtonCopied", IDS_WOOTZ_WALLET_BUTTON_COPIED},
    {"wootzWalletButtonVerify", IDS_WOOTZ_WALLET_BUTTON_VERIFY},
    {"wootzWalletButtonClose", IDS_WOOTZ_WALLET_BUTTON_CLOSE},
    {"wootzWalletButtonMore", IDS_WOOTZ_WALLET_BUTTON_MORE},
    {"wootzWalletButtonDone", IDS_WOOTZ_WALLET_BUTTON_DONE},
    {"wootzWalletWelcomeTitle", IDS_WOOTZ_WALLET_WELCOME_TITLE},
    {"wootzWalletWelcomeRestoreButton",
     IDS_WOOTZ_WALLET_WELCOME_RESTORE_BUTTON},
    {"wootzWalletWelcomeDescription", IDS_WOOTZ_WALLET_WELCOME_DESCRIPTION},
    {"wootzWalletWelcomeNewWalletTitle",
     IDS_WOOTZ_WALLET_WELCOME_NEW_WALLET_TITLE},
    {"wootzWalletWelcomeNewWalletDescription",
     IDS_WOOTZ_WALLET_WELCOME_NEW_WALLET_DESCRIPTION},
    {"wootzWalletWelcomeImportWalletTitle",
     IDS_WOOTZ_WALLET_WELCOME_IMPORT_WALLET_TITLE},
    {"wootzWalletWelcomeImportWalletDescription",
     IDS_WOOTZ_WALLET_WELCOME_IMPORT_WALLET_DESCRIPTION},
    {"wootzWalletWelcomeWatchOnlyTitle",
     IDS_WOOTZ_WALLET_WELCOME_WATCH_ONLY_TITLE},
    {"wootzWalletCopyright", IDS_WOOTZ_WALLET_WELCOME_COPYRIGHT},
    {"wootzWalletWelcomeDividerText", IDS_WOOTZ_WALLET_WELCOME_DIVIDER_TEXT},
    {"wootzWalletBackupIntroTitle", IDS_WOOTZ_WALLET_BACKUP_INTRO_TITLE},
    {"wootzWalletBackupIntroTerms", IDS_WOOTZ_WALLET_BACKUP_INTRO_TERMS},
    {"wootzWalletButtonSkip", IDS_WOOTZ_WALLET_BUTTON_SKIP},
    {"wootzWalletButtonCancel", IDS_WOOTZ_WALLET_BUTTON_CANCEL},
    {"wootzWalletButtonSaveChanges", IDS_WOOTZ_WALLET_BUTTON_SAVE_CHANGES},
    {"wootzWalletRecoveryTitle", IDS_WOOTZ_WALLET_RECOVERY_TITLE},
    {"wootzWalletRecoveryDescription", IDS_WOOTZ_WALLET_RECOVERY_DESCRIPTION},
    {"wootzWalletRecoveryWarning1", IDS_WOOTZ_WALLET_RECOVERY_WARNING1},
    {"wootzWalletRecoveryWarning2", IDS_WOOTZ_WALLET_RECOVERY_WARNING2},
    {"wootzWalletRecoveryWarning3", IDS_WOOTZ_WALLET_RECOVERY_WARNING3},
    {"wootzWalletRecoveryTerms", IDS_WOOTZ_WALLET_RECOVERY_TERMS},
    {"wootzWalletVerifyRecoveryTitle", IDS_WOOTZ_WALLET_VERIFY_RECOVERY_TITLE},
    {"wootzWalletVerifyRecoveryDescription",
     IDS_WOOTZ_WALLET_VERIFY_RECOVERY_DESCRIPTION},
    {"wootzWalletVerifyError", IDS_WOOTZ_WALLET_VERIFY_ERROR},
    {"wootzWalletVerifyRecoveryPhraseTitle",
     IDS_WOOTZ_WALLET_VERIFY_RECOVERY_PHRASE_TITLE},
    {"wootzWalletVerifyRecoveryPhraseInstructions",
     IDS_WOOTZ_WALLET_VERIFY_RECOVERY_PHRASE_INSTRUCTIONS},
    {"wootzWalletVerifyPhraseError", IDS_WOOTZ_WALLET_VERIFY_PHRASE_ERROR},
    {"wootzWalletCreatePasswordTitle", IDS_WOOTZ_WALLET_CREATE_PASSWORD_TITLE},
    {"wootzWalletCreatePasswordDescription",
     IDS_WOOTZ_WALLET_CREATE_PASSWORD_DESCRIPTION},
    {"wootzWalletCreatePasswordInput", IDS_WOOTZ_WALLET_CREATE_PASSWORD_INPUT},
    {"wootzWalletConfirmPasswordInput",
     IDS_WOOTZ_WALLET_CONFIRM_PASSWORD_INPUT},
    {"wootzWalletCreatePasswordError", IDS_WOOTZ_WALLET_CREATE_PASSWORD_ERROR},
    {"wootzWalletConfirmPasswordError",
     IDS_WOOTZ_WALLET_CONFIRM_PASSWORD_ERROR},
    {"wootzWalletLockScreenTitle", IDS_WOOTZ_WALLET_LOCK_SCREEN_TITLE},
    {"wootzWalletLockScreenButton", IDS_WOOTZ_WALLET_LOCK_SCREEN_BUTTON},
    {"wootzWalletLockScreenError", IDS_WOOTZ_WALLET_LOCK_SCREEN_ERROR},
    {"wootzWalletUnlockWallet", IDS_WOOTZ_WALLET_UNLOCK_WALLET},
    {"wootzWalletWalletPopupSettings", IDS_WOOTZ_WALLET_WALLET_POPUP_SETTINGS},
    {"wootzWalletWalletPopupLock", IDS_WOOTZ_WALLET_WALLET_POPUP_LOCK},
    {"wootzWalletWalletPopupBackup", IDS_WOOTZ_WALLET_WALLET_POPUP_BACKUP},
    {"wootzWalletWalletPopupConnectedSites",
     IDS_WOOTZ_WALLET_WALLET_POPUP_CONNECTED_SITES},
    {"wootzWalletWalletPopupHideBalances",
     IDS_WOOTZ_WALLET_WALLET_POPUP_HIDE_BALANCES},
    {"wootzWalletWalletPopupShowGraph",
     IDS_WOOTZ_WALLET_WALLET_POPUP_SHOW_GRAPH},
    {"wootzWalletWalletNFTsTab", IDS_WOOTZ_WALLET_WALLET_NFTS_TAB},
    {"wootzWalletBackupWarningText", IDS_WOOTZ_WALLET_BACKUP_WARNING_TEXT},
    {"wootzWalletBackupButton", IDS_WOOTZ_WALLET_BACKUP_BUTTON},
    {"wootzWalletDismissButton", IDS_WOOTZ_WALLET_DISMISS_BUTTON},
    {"wootzWalletDefaultWalletBanner", IDS_WOOTZ_WALLET_DEFAULT_WALLET_BANNER},
    {"wootzWalletRestoreTite", IDS_WOOTZ_WALLET_RESTORE_TITE},
    {"wootzWalletRestoreDescription", IDS_WOOTZ_WALLET_RESTORE_DESCRIPTION},
    {"wootzWalletRestoreError", IDS_WOOTZ_WALLET_RESTORE_ERROR},
    {"wootzWalletRestorePlaceholder", IDS_WOOTZ_WALLET_RESTORE_PLACEHOLDER},
    {"wootzWalletRestoreShowPhrase", IDS_WOOTZ_WALLET_RESTORE_SHOW_PHRASE},
    {"wootzWalletRestoreLegacyCheckBox",
     IDS_WOOTZ_WALLET_RESTORE_LEGACY_CHECK_BOX},
    {"wootzWalletRestoreFormText", IDS_WOOTZ_WALLET_RESTORE_FORM_TEXT},
    {"wootzWalletSkipBackupWarning", IDS_WOOTZ_WALLET_SKIP_BACKUP_WARNING},
    {"wootzWalletSkipBackup", IDS_WALLET_SKIP_BACKUP},
    {"wootzWalletGoBack", IDS_WOOTZ_WALLET_GO_BACK},
    {"wootzWalletToolTipCopyToClipboard",
     IDS_WOOTZ_WALLET_TOOL_TIP_COPY_TO_CLIPBOARD},
    {"wootzWalletToolTipCopiedToClipboard",
     IDS_WOOTZ_WALLET_TOOL_TIP_COPIED_TO_CLIPBOARD},
    {"wootzWalletClickToCopy", IDS_WOOTZ_WALLET_CLICK_TO_COPY},
    {"wootzWalletPasteFromClipboard", IDS_WOOTZ_WALLET_PASTE_FROM_CLIPBOARD},
    {"wootzWalletAccountsPrimary", IDS_WOOTZ_WALLET_ACCOUNTS_PRIMARY},
    {"wootzWalletAccountsSecondary", IDS_WOOTZ_WALLET_ACCOUNTS_SECONDARY},
    {"wootzWalletConnectedHardwareWallets",
     IDS_WOOTZ_WALLET_CONNECTED_HARDWARE_WALLETS},
    {"wootzWalletAccountsAssets", IDS_WOOTZ_WALLET_ACCOUNTS_ASSETS},
    {"wootzWalletAccountsEditVisibleAssets",
     IDS_WOOTZ_WALLET_ACCOUNTS_EDIT_VISIBLE_ASSETS},
    {"wootzWalletAccountBalance", IDS_WOOTZ_WALLET_ACCOUNT_BALANCE},
    {"wootzWalletViewAddressOn", IDS_WOOTZ_WALLET_VIEW_ADDRESS_ON},
    {"wootzWalletNetworkExplorer", IDS_WOOTZ_WALLET_NETWORK_EXPLORER},
    {"wootzWalletAddAccountCreate", IDS_WOOTZ_WALLET_ADD_ACCOUNT_CREATE},
    {"wootzWalletCreateAccount", IDS_WOOTZ_WALLET_CREATE_ACCOUNT},
    {"wootzWalletCreateAccountButton", IDS_WOOTZ_WALLET_CREATE_ACCOUNT_BUTTON},
    {"wootzWalletCreateAccountImportAccount",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_IMPORT_ACCOUNT},
    {"wootzWalletCreateAccountTitle", IDS_WOOTZ_WALLET_CREATE_ACCOUNT_TITLE},
    {"wootzWalletCreateAccountEthereumDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_ETHEREUM_DESCRIPTION},
    {"wootzWalletCreateAccountSolanaDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_SOLANA_DESCRIPTION},
    {"wootzWalletCreateAccountFilecoinDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_FILECOIN_DESCRIPTION},
    {"wootzWalletCreateAccountBitcoinDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_BITCOIN_DESCRIPTION},
    {"wootzWalletCreateAccountZCashDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_ZCASH_DESCRIPTION},
    {"wootzWalletFilecoinPrivateKeyProtocol",
     IDS_WOOTZ_WALLET_FILECOIN_PRIVATE_KEY_PROTOCOL},
    {"wootzWalletAddAccountImport", IDS_WOOTZ_WALLET_ADD_ACCOUNT_IMPORT},
    {"wootzWalletAddAccountImportHardware",
     IDS_WOOTZ_WALLET_ADD_ACCOUNT_IMPORT_HARDWARE},
    {"wootzWalletAddAccountHardware", IDS_WOOTZ_WALLET_ADD_ACCOUNT_HARDWARE},
    {"wootzWalletAddAccountConnect", IDS_WOOTZ_WALLET_ADD_ACCOUNT_CONNECT},
    {"wootzWalletAddAccountPlaceholder",
     IDS_WOOTZ_WALLET_ADD_ACCOUNT_PLACEHOLDER},
    {"wootzWalletImportAccountDisclaimer",
     IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_DISCLAIMER},
    {"wootzWalletImportAccountPlaceholder",
     IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_PLACEHOLDER},
    {"wootzWalletImportAccountKey", IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_KEY},
    {"wootzWalletImportAccountFile", IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_FILE},
    {"wootzWalletImportAccountUploadButton",
     IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_UPLOAD_BUTTON},
    {"wootzWalletImportAccountUploadPlaceholder",
     IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_UPLOAD_PLACEHOLDER},
    {"wootzWalletImportAccountError", IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_ERROR},
    {"wootzWalletImportAccount", IDS_WOOTZ_WALLET_IMPORT_ACCOUNT},
    {"wootzWalletConnectHardwareTitle",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_TITLE},
    {"wootzWalletConnectHardwareInfo1",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_INFO1},
    {"wootzWalletConnectHardwareInfo2",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_INFO2},
    {"wootzWalletConnectHardwareWrongApplicationUserHint",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_WRONG_APPLICATION_USER_HINT},
    {"wootzWalletConnectHardwareTrezor",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_TREZOR},
    {"wootzWalletConnectHardwareLedger",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_LEDGER},
    {"wootzWalletConnectHardwareAuthorizationNeeded",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_AUTHORIZATION_NEEDED},
    {"wootzWalletConnectingHardwareWallet",
     IDS_WOOTZ_WALLET_CONNECTING_HARDWARE_WALLET},
    {"wootzWalletAddCheckedAccountsHardwareWallet",
     IDS_WOOTZ_WALLET_ADD_CHECKED_ACCOUNTS_HARDWARE_WALLET},
    {"wootzWalletLoadMoreAccountsHardwareWallet",
     IDS_WOOTZ_WALLET_LOAD_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"wootzWalletLoadingMoreAccountsHardwareWallet",
     IDS_WOOTZ_WALLET_LOADING_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"wootzWalletSearchScannedAccounts",
     IDS_WOOTZ_WALLET_SEARCH_SCANNED_ACCOUNTS},
    {"wootzWalletSwitchHDPathTextHardwareWallet",
     IDS_WOOTZ_WALLET_SWITCH_H_D_PATH_TEXT_HARDWARE_WALLET},
    {"wootzWalletHDPath", IDS_WOOTZ_WALLET_H_D_PATH},
    {"wootzWalletLedgerLiveDerivationPath",
     IDS_WOOTZ_WALLET_LEDGER_LIVE_DERIVATION_PATH},
    {"wootzWalletLedgerLegacyDerivationPath",
     IDS_WOOTZ_WALLET_LEDGER_LEGACY_DERIVATION_PATH},
    {"wootzWalletConnectHardwareSearchNothingFound",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_SEARCH_NOTHING_FOUND},
    {"wootzWalletAuthorizeHardwareWallet",
     IDS_WOOTZ_WALLET_AUTHORIZE_HARDWARE_WALLET},
    {"wootzWalletConnectHardwareWallet",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_WALLET},
    {"wootzWallectConnectHardwareDescription",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_WALLET_DESCRIPTION},
    {"wootzWalletImportHardwareWalletDescription",
     IDS_WOOTZ_WALLET_IMPORT_HARDWARE_WALLET_DESCRIPTION},
    {"wootzWalletConnectHardwareWalletSelectBlockchain",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_WALLET_SELECT_BLOCKCHAIN},
    {"wootzWalletConnectHardwareDeviceDescription",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_DEVICE_DESCRIPTION},
    {"wootzWalletUnknownInternalError",
     IDS_WOOTZ_WALLET_UNKNOWN_INTERNAL_ERROR},
    {"wootzWalletAccountSettingsDetails",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_DETAILS},
    {"wootzWalletAccountSettingsWatchlist",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_WATCHLIST},
    {"wootzWalletAccountSettingsPrivateKey",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_PRIVATE_KEY},
    {"wootzWalletAccountSettingsSave", IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_SAVE},
    {"wootzWalletAccountSettingsRemove",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_REMOVE},
    {"wootzWalletWatchlistAddCustomAsset",
     IDS_WOOTZ_WALLET_WATCHLIST_ADD_CUSTOM_ASSET},
    {"wootzWalletWatchListTokenName", IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_NAME},
    {"wootzWalletWatchListTokenAddress",
     IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_ADDRESS},
    {"wootzWalletWatchListTokenSymbol",
     IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_SYMBOL},
    {"wootzWalletWatchListTokenDecimals",
     IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_DECIMALS},
    {"wootzWalletWatchListAdd", IDS_WOOTZ_WALLET_WATCH_LIST_ADD},
    {"wootzWalletWatchListDoneButton", IDS_WOOTZ_WALLET_WATCH_LIST_DONE_BUTTON},
    {"wootzWalletWatchListNoAsset", IDS_WOOTZ_WALLET_WATCH_LIST_NO_ASSET},
    {"wootzWalletWatchListSearchPlaceholder",
     IDS_WOOTZ_WALLET_WATCH_LIST_SEARCH_PLACEHOLDER},
    {"wootzWalletWatchListError", IDS_WOOTZ_WALLET_WATCH_LIST_ERROR},
    {"wootzWalletCustomTokenExistsError",
     IDS_WOOTZ_WALLET_CUSTOM_TOKEN_EXISTS_ERROR},
    {"wootzWalletWatchListTokenId", IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_ID},
    {"wootzWalletWatchListTokenIdError",
     IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_ID_ERROR},
    {"wootzWalletWatchListAdvanced", IDS_WOOTZ_WALLET_WATCH_LIST_ADVANCED},
    {"wootzWalletWatchListCoingeckoId",
     IDS_WOOTZ_WALLET_WATCH_LIST_COINGECKO_ID},
    {"wootzWalletIconURL", IDS_WOOTZ_WALLET_ICON_URL},
    {"wootzWalletAddAsset", IDS_WOOTZ_WALLET_ADD_ASSET},
    {"wootzWalletAccountsExport", IDS_WOOTZ_WALLET_ACCOUNTS_EXPORT},
    {"wootzWalletAccountsDeposit", IDS_WOOTZ_WALLET_ACCOUNTS_DEPOSIT},
    {"wootzWalletAccountsRemove", IDS_WOOTZ_WALLET_ACCOUNTS_REMOVE},
    {"wootzWalletAccountSettings", IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS},
    {"wootzWalletNoAvailableAssets", IDS_WOOTZ_WALLET_NO_AVAILABLE_ASSETS},
    {"wootzWalletNoAvailableAssetsDescription",
     IDS_WOOTZ_WALLET_NO_AVAILABLE_ASSETS_DESCRIPTION},
    {"wootzWalletAccountSettingsDisclaimer",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_DISCLAIMER},
    {"wootzWalletFilExportPrivateKeyFormatDescription",
     IDS_WOOTZ_WALLET_FIL_EXPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"wootzWalletFilImportPrivateKeyFormatDescription",
     IDS_WOOTZ_WALLET_FIL_IMPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"wootzWalletBtcImportPrivateKeyFormatDescription",
     IDS_WOOTZ_WALLET_BTC_IMPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"wootzWalletAccountSettingsShowKey",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_SHOW_KEY},
    {"wootzWalletAccountSettingsHideKey",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_HIDE_KEY},
    {"wootzWalletAccountSettingsUpdateError",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_UPDATE_ERROR},
    {"wootzWalletPreset25", IDS_WOOTZ_WALLET_PRESET25},
    {"wootzWalletPreset50", IDS_WOOTZ_WALLET_PRESET50},
    {"wootzWalletPreset75", IDS_WOOTZ_WALLET_PRESET75},
    {"wootzWalletPreset100", IDS_WOOTZ_WALLET_PRESET100},
    {"wootzWalletUnsupportedNetwork", IDS_WOOTZ_WALLET_UNSUPPORTED_NETWORK},
    {"wootzWalletNetworkETH", IDS_WOOTZ_WALLET_NETWORK_E_T_H},
    {"wootzWalletNetworkMain", IDS_WOOTZ_WALLET_NETWORK_MAIN},
    {"wootzWalletNetworkTest", IDS_WOOTZ_WALLET_NETWORK_TEST},
    {"wootzWalletNetworkGoerli", IDS_WOOTZ_WALLET_NETWORK_GOERLI},
    {"wootzWalletNetworkSepolia", IDS_WOOTZ_WALLET_NETWORK_SEPOLIA},
    {"wootzWalletNetworkLocalhost", IDS_WOOTZ_WALLET_NETWORK_LOCALHOST},
    {"wootzWalletSelectAccount", IDS_WOOTZ_WALLET_SELECT_ACCOUNT},
    {"wootzWalletSearchAccount", IDS_WOOTZ_WALLET_SEARCH_ACCOUNT},
    {"wootzWalletSelectNetwork", IDS_WOOTZ_WALLET_SELECT_NETWORK},
    {"wootzWalletSelectAsset", IDS_WOOTZ_WALLET_SELECT_ASSET},
    {"wootzWalletSearchAsset", IDS_WOOTZ_WALLET_SEARCH_ASSET},
    {"wootzWalletSwapFrom", IDS_WOOTZ_WALLET_SWAP_FROM},
    {"wootzWalletSwapTo", IDS_WOOTZ_WALLET_SWAP_TO},
    {"wootzWalletSwapEstimate", IDS_WOOTZ_WALLET_SWAP_ESTIMATE},
    {"wootzWalletSwapMarket", IDS_WOOTZ_WALLET_SWAP_MARKET},
    {"wootzWalletSwapLimit", IDS_WOOTZ_WALLET_SWAP_LIMIT},
    {"wootzWalletSwapPriceIn", IDS_WOOTZ_WALLET_SWAP_PRICE_IN},
    {"wootzWalletBuyTitle", IDS_WOOTZ_WALLET_BUY_TITLE},
    {"wootzWalletBuyDescription", IDS_WOOTZ_WALLET_BUY_DESCRIPTION},
    {"wootzWalletBuyContinueButton", IDS_WOOTZ_WALLET_BUY_CONTINUE_BUTTON},
    {"wootzWalletSignTransactionTitle",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_TITLE},
    {"wootzWalletSignWarning", IDS_WOOTZ_WALLET_SIGN_WARNING},
    {"wootzWalletSignWarningTitle", IDS_WOOTZ_WALLET_SIGN_WARNING_TITLE},
    {"wootzWalletSignTransactionMessageTitle",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_MESSAGE_TITLE},
    {"wootzWalletSignTransactionEIP712MessageDomain",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_EIP712_MESSAGE_DOMAIN},
    {"wootzWalletSignTransactionEIP712MessageTitle",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_EIP712_MESSAGE_TITLE},
    {"wootzWalletSignTransactionEIP712MessageHideDetails",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_EIP712_MESSAGE_HIDE_DETAILS},
    {"wootzWalletSignTransactionButton",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_BUTTON},
    {"wootzWalletProvideEncryptionKeyTitle",
     IDS_WOOTZ_WALLET_PROVIDE_ENCRYPTION_KEY_TITLE},
    {"wootzWalletProvideEncryptionKeyDescription",
     IDS_WOOTZ_WALLET_PROVIDE_ENCRYPTION_KEY_DESCRIPTION},
    {"wootzWalletProvideEncryptionKeyButton",
     IDS_WOOTZ_WALLET_PROVIDE_ENCRYPTION_KEY_BUTTON},
    {"wootzWalletReadEncryptedMessageTitle",
     IDS_WOOTZ_WALLET_READ_ENCRYPTED_MESSAGE_TITLE},
    {"wootzWalletReadEncryptedMessageDecryptButton",
     IDS_WOOTZ_WALLET_READ_ENCRYPTED_MESSAGE_DECRYPT_BUTTON},
    {"wootzWalletReadEncryptedMessageButton",
     IDS_WOOTZ_WALLET_READ_ENCRYPTED_MESSAGE_BUTTON},
    {"wootzWalletAllowSpendTitle", IDS_WOOTZ_WALLET_ALLOW_SPEND_TITLE},
    {"wootzWalletAllowSpendDescription",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_DESCRIPTION},
    {"wootzWalletAllowSpendBoxTitle", IDS_WOOTZ_WALLET_ALLOW_SPEND_BOX_TITLE},
    {"wootzWalletAllowSpendTransactionFee",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_TRANSACTION_FEE},
    {"wootzWalletAllowSpendEditButton",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_EDIT_BUTTON},
    {"wootzWalletAllowSpendDetailsButton",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_DETAILS_BUTTON},
    {"wootzWalletAllowSpendRejectButton",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_REJECT_BUTTON},
    {"wootzWalletAllowSpendConfirmButton",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_CONFIRM_BUTTON},
    {"wootzWalletAllowSpendCurrentAllowance",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_CURRENT_ALLOWANCE},
    {"wootzWalletAllowSpendProposedAllowance",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_PROPOSED_ALLOWANCE},
    {"wootzWalletAllowSpendUnlimitedWarningTitle",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_UNLIMITED_WARNING_TITLE},
    {"wootzWalletAllowAddNetworkTitle",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_TITLE},
    {"wootzWalletAllowChangeNetworkTitle",
     IDS_WOOTZ_WALLET_ALLOW_CHANGE_NETWORK_TITLE},
    {"wootzWalletAllowChangeNetworkDescription",
     IDS_WOOTZ_WALLET_ALLOW_CHANGE_NETWORK_DESCRIPTION},
    {"wootzWalletAllowChangeNetworkButton",
     IDS_WOOTZ_WALLET_ALLOW_CHANGE_NETWORK_BUTTON},
    {"wootzWalletAllowAddNetworkDescription",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_DESCRIPTION},
    {"wootzWalletAllowAddNetworkLearnMoreButton",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_LEARN_MORE_BUTTON},
    {"wootzWalletAllowAddNetworkName", IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_NAME},
    {"wootzWalletAllowAddNetworkUrl", IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_URL},
    {"wootzWalletAllowAddNetworkDetailsButton",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_DETAILS_BUTTON},
    {"wootzWalletAllowAddNetworkButton",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_BUTTON},
    {"wootzWalletChainId", IDS_WOOTZ_WALLET_CHAIN_ID},
    {"wootzWalletAllowAddNetworkCurrencySymbol",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_CURRENCY_SYMBOL},
    {"wootzWalletAllowAddNetworkExplorer",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_EXPLORER},
    {"wootzWalletAllowAddNetworkNetworkPanelTitle",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_PANEL_TITLE},
    {"wootzWalletAllowAddNetworkDetailsPanelTitle",
     IDS_WOOTZ_WALLET_ALLOW_ADD_DETAILS_PANEL_TITLE},
    {"wootzWalletConfirmTransactionTotal",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_TOTAL},
    {"wootzWalletConfirmTransactionGasFee",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_GAS_FEE},
    {"wootzWalletConfirmTransactionTransactionFee",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_TRANSACTION_FEE},
    {"wootzWalletConfirmTransactionBid",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_BID},
    {"wootzWalletConfirmTransactionAmountGas",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_AMOUNT_GAS},
    {"wootzWalletConfirmTransactionAmountFee",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_AMOUNT_FEE},
    {"wootzWalletConfirmTransactionNoData",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_NO_DATA},
    {"wootzWalletConfirmTransactionNext",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_NEXT},
    {"wootzWalletConfirmTransactionFirst",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_FIRST},
    {"wootzWalletConfirmTransactions", IDS_WOOTZ_WALLET_CONFIRM_TRANSACTIONS},
    {"wootzWalletConfirmTransactionAccountCreationFee",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_ACCOUNT_CREATION_FEE},
    {"wootzWalletTransactionGasLimit", IDS_WOOTZ_WALLET_TRANSACTION_GAS_LIMIT},
    {"wootzWalletTransactionGasPremium",
     IDS_WOOTZ_WALLET_TRANSACTION_GAS_PREMIUM},
    {"wootzWalletTransactionGasFeeCap",
     IDS_WOOTZ_WALLET_TRANSACTION_GAS_FEE_CAP},
    {"wootzWalletPanelTitle", IDS_WOOTZ_WALLET_PANEL_TITLE},
    {"wootzWalletPanelConnected", IDS_WOOTZ_WALLET_PANEL_CONNECTED},
    {"wootzWalletSitePermissionsAccounts",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_ACCOUNTS},
    {"wootzWalletSitePermissionsDisconnect",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_DISCONNECT},
    {"wootzWalletSitePermissionsSwitch",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_SWITCH},
    {"wootzWalletSitePermissionsTrust",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_TRUST},
    {"wootzWalletSitePermissionsRevoke",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_REVOKE},
    {"wootzWalletChangeNetwork", IDS_WOOTZ_WALLET_CHANGE_NETWORK},
    {"wootzWalletChangeAccount", IDS_WOOTZ_WALLET_CHANGE_ACCOUNT},
    {"wootzWalletActive", IDS_WOOTZ_WALLET_ACTIVE},
    {"wootzWalletNotConnected", IDS_WOOTZ_WALLET_NOT_CONNECTED},
    {"wootzWalletConnectedAccounts", IDS_WOOTZ_WALLET_CONNECTED_ACCOUNTS},
    {"wootzWalletAvailableAccounts", IDS_WOOTZ_WALLET_AVAILABLE_ACCOUNTS},
    {"wootzWalletSitePermissionsNewAccount",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_NEW_ACCOUNT},
    {"wootzWalletPanelBlocked", IDS_WOOTZ_WALLET_PANEL_BLOCKED},
    {"wootzWalletTitle", IDS_WOOTZ_WALLET_TITLE},
    {"wootzWalletWelcomePanelDescription",
     IDS_WOOTZ_WALLET_WELCOME_PANEL_DESCRIPTION},
    {"wootzWalletLearnMore", IDS_WOOTZ_WALLET_LEARN_MORE},
    {"wootzWalletTransactionDetailBoxFunction",
     IDS_WOOTZ_WALLET_TRANSACTION_DETAIL_BOX_FUNCTION},
    {"wootzWalletTransactionDetailBoxHex",
     IDS_WOOTZ_WALLET_TRANSACTION_DETAIL_BOX_HEX},
    {"wootzWalletTransactionDetailBoxBytes",
     IDS_WOOTZ_WALLET_TRANSACTION_DETAIL_BOX_BYTES},
    {"wootzWalletConnectWithSiteNext", IDS_WOOTZ_WALLET_CONNECT_WITH_SITE_NEXT},
    {"wootzWalletConnectWallet", IDS_WOOTZ_WALLET_CONNECT_WALLET},
    {"wootzWalletConnectWithSite", IDS_WOOTZ_WALLET_CONNECT_WITH_SITE},
    {"wootzWalletConnectPermittedLabel",
     IDS_WOOTZ_WALLET_CONNECT_PERMITTED_LABEL},
    {"wootzWalletConnectNotPermittedLabel",
     IDS_WOOTZ_WALLET_CONNECT_NOT_PERMITTED_LABEL},
    {"wootzWalletConnectPermissionBalanceAndActivity",
     IDS_WOOTZ_WALLET_CONNECT_PERMISSION_BALANCE_AND_ACTIVITY},
    {"wootzWalletConnectPermissionRequestApproval",
     IDS_WOOTZ_WALLET_CONNECT_PERMISSION_REQUEST_APPROVAL},
    {"wootzWalletConnectPermissionAddress",
     IDS_WOOTZ_WALLET_CONNECT_PERMISSION_ADDRESS},
    {"wootzWalletConnectPermissionMoveFunds",
     IDS_WOOTZ_WALLET_CONNECT_PERMISSION_MOVE_FUNDS},
    {"wootzWalletConnectTrustWarning", IDS_WOOTZ_WALLET_CONNECT_TRUST_WARNING},
    {"wootzWalletPermissionDuration", IDS_WOOTZ_WALLET_PERMISSION_DURATION},
    {"wootzWalletPermissionUntilClose",
     IDS_WOOTZ_WALLET_PERMISSION_UNTIL_CLOSE},
    {"wootzWalletPermissionOneDay", IDS_WOOTZ_WALLET_PERMISSION_ONE_DAY},
    {"wootzWalletPermissionOneWeek", IDS_WOOTZ_WALLET_PERMISSION_ONE_WEEK},
    {"wootzWalletPermissionForever", IDS_WOOTZ_WALLET_PERMISSION_FOREVER},
    {"wootzWalletCryptoWalletsDetected",
     IDS_WOOTZ_WALLET_CRYPTO_WALLETS_DETECTED},
    {"wootzWalletLegacyWalletDetected",
     IDS_WOOTZ_WALLET_LEGACY_WALLET_DETECTED},
    {"wootzWalletCryptoWalletsDescriptionTwo",
     IDS_WOOTZ_WALLET_CRYPTO_WALLETS_DESCRIPTION_TWO},
    {"wootzWalletImportWootzLegacyDescription",
     IDS_WOOTZ_WALLET_IMPORT_WOOTZ_LEGACY_DESCRIPTION},
    {"wootzWalletImportWootzLegacyInput",
     IDS_WOOTZ_WALLET_IMPORT_WOOTZ_LEGACY_INPUT},
    {"wootzWalletConnectHardwarePanelConnected",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_CONNECTED},
    {"wootzWalletConnectHardwarePanelDisconnected",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_DISCONNECTED},
    {"wootzWalletConnectHardwarePanelInstructions",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_INSTRUCTIONS},
    {"wootzWalletConnectHardwarePanelConnect",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_CONNECT},
    {"wootzWalletConnectHardwarePanelConfirmation",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_CONFIRMATION},
    {"wootzWalletConnectHardwarePanelOpenApp",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_OPEN_APP},
    {"wootzWalletTransactionSent", IDS_WOOTZ_WALLET_TRANSACTION_SENT},
    {"wootzWalletTransactionReceived", IDS_WOOTZ_WALLET_TRANSACTION_RECEIVED},
    {"wootzWalletTransactionExplorerMissing",
     IDS_WOOTZ_WALLET_TRANSACTION_EXPLORER_MISSING},
    {"wootzWalletTransactionExplorer", IDS_WOOTZ_WALLET_TRANSACTION_EXPLORER},
    {"wootzWalletTransactionCopyHash", IDS_WOOTZ_WALLET_TRANSACTION_COPY_HASH},
    {"wootzWalletTransactionSpeedup", IDS_WOOTZ_WALLET_TRANSACTION_SPEEDUP},
    {"wootzWalletTransactionCancel", IDS_WOOTZ_WALLET_TRANSACTION_CANCEL},
    {"wootzWalletTransactionRetry", IDS_WOOTZ_WALLET_TRANSACTION_RETRY},
    {"wootzWalletTransactionStatusUnapproved",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_UNAPPROVED},
    {"wootzWalletTransactionStatusApproved",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_APPROVED},
    {"wootzWalletTransactionStatusRejected",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_REJECTED},
    {"wootzWalletTransactionStatusSubmitted",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_SUBMITTED},
    {"wootzWalletTransactionStatusConfirmed",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_CONFIRMED},
    {"wootzWalletTransactionStatusError",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_ERROR},
    {"wootzWalletTransactionStatusDropped",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_DROPPED},
    {"wootzWalletTransactionStatusSigned",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_SIGNED},
    {"wootzWalletOn", IDS_WOOTZ_WALLET_ON},
    {"wootzWalletRecentTransactions", IDS_WOOTZ_WALLET_RECENT_TRANSACTIONS},
    {"wootzWalletTransactionDetailHash",
     IDS_WOOTZ_WALLET_TRANSACTION_DETAIL_HASH},
    {"wootzWalletTransactionDetailNetwork",
     IDS_WOOTZ_WALLET_TRANSACTION_DETAIL_NETWORK},
    {"wootzWalletTransactionPlaceholder",
     IDS_WOOTZ_WALLET_TRANSACTION_PLACEHOLDER},
    {"wootzWalletTransactionApproveUnlimited",
     IDS_WOOTZ_WALLET_TRANSACTION_APPROVE_UNLIMITED},
    {"wootzWalletEditGasTitle1", IDS_WOOTZ_WALLET_EDIT_GAS_TITLE1},
    {"wootzWalletEditGasTitle2", IDS_WOOTZ_WALLET_EDIT_GAS_TITLE2},
    {"wootzWalletEditGasDescription", IDS_WOOTZ_WALLET_EDIT_GAS_DESCRIPTION},
    {"wootzWalletEditGasLow", IDS_WOOTZ_WALLET_EDIT_GAS_LOW},
    {"wootzWalletEditGasOptimal", IDS_WOOTZ_WALLET_EDIT_GAS_OPTIMAL},
    {"wootzWalletEditGasHigh", IDS_WOOTZ_WALLET_EDIT_GAS_HIGH},
    {"wootzWalletEditGasLimit", IDS_WOOTZ_WALLET_EDIT_GAS_LIMIT},
    {"wootzWalletEditGasPerGasPrice", IDS_WOOTZ_WALLET_EDIT_GAS_PER_GAS_PRICE},
    {"wootzWalletEditGasPerTipLimit", IDS_WOOTZ_WALLET_EDIT_GAS_PER_TIP_LIMIT},
    {"wootzWalletEditGasPerPriceLimit",
     IDS_WOOTZ_WALLET_EDIT_GAS_PER_PRICE_LIMIT},
    {"wootzWalletEditGasMaxFee", IDS_WOOTZ_WALLET_EDIT_GAS_MAX_FEE},
    {"wootzWalletEditGasMaximumFee", IDS_WOOTZ_WALLET_EDIT_GAS_MAXIMUM_FEE},
    {"wootzWalletEditGasBaseFee", IDS_WOOTZ_WALLET_EDIT_GAS_BASE_FEE},
    {"wootzWalletEditGasGwei", IDS_WOOTZ_WALLET_EDIT_GAS_GWEI},
    {"wootzWalletEditGasSetCustom", IDS_WOOTZ_WALLET_EDIT_GAS_SET_CUSTOM},
    {"wootzWalletEditGasSetSuggested", IDS_WOOTZ_WALLET_EDIT_GAS_SET_SUGGESTED},
    {"wootzWalletEditGasZeroGasPriceWarning",
     IDS_WOOTZ_WALLET_EDIT_GAS_ZERO_GAS_PRICE_WARNING},
    {"wootzWalletAdvancedTransactionSettings",
     IDS_WOOTZ_WALLET_ADVANCED_TRANSACTION_SETTINGS},
    {"wootzWalletAdvancedTransactionSettingsPlaceholder",
     IDS_WOOTZ_WALLET_ADVANCED_TRANSACTION_SETTINGS_PLACEHOLDER},
    {"wootzWalletEditNonce", IDS_WOOTZ_WALLET_EDIT_NONCE},
    {"wootzWalletEditNonceInfo", IDS_WOOTZ_WALLET_EDIT_NONCE_INFO},
    {"wootzWalletEditPermissionsTitle",
     IDS_WOOTZ_WALLET_EDIT_PERMISSIONS_TITLE},
    {"wootzWalletEditPermissionsDescription",
     IDS_WOOTZ_WALLET_EDIT_PERMISSIONS_DESCRIPTION},
    {"wootzWalletEditPermissionsButton",
     IDS_WOOTZ_WALLET_EDIT_PERMISSIONS_BUTTON},
    {"wootzWalletEditPermissionsProposedAllowance",
     IDS_WOOTZ_WALLET_EDIT_PERMISSIONS_PROPOSED_ALLOWANCE},
    {"wootzWalletEditPermissionsCustomAllowance",
     IDS_WOOTZ_WALLET_EDIT_PERMISSIONS_CUSTOM_ALLOWANCE},
    {"wootzWalletNotValidEthAddress", IDS_WOOTZ_WALLET_NOT_VALID_ETH_ADDRESS},
    {"wootzWalletNotValidSolAddress", IDS_WOOTZ_WALLET_NOT_VALID_SOL_ADDRESS},
    {"wootzWalletNotValidAddress", IDS_WOOTZ_WALLET_NOT_VALID_ADDRESS},
    {"wootzWalletNotDomain", IDS_WOOTZ_WALLET_NOT_DOMAIN},
    {"wootzWalletSameAddressError", IDS_WOOTZ_WALLET_SAME_ADDRESS_ERROR},
    {"wootzWalletContractAddressError",
     IDS_WOOTZ_WALLET_CONTRACT_ADDRESS_ERROR},
    {"wootzWalletFailedChecksumTitle", IDS_WOOTZ_WALLET_FAILED_CHECKSUM_TITLE},
    {"wootzWalletFailedChecksumDescription",
     IDS_WOOTZ_WALLET_FAILED_CHECKSUM_DESCRIPTION},
    {"wootzWalletHowToSolve", IDS_WOOTZ_WALLET_HOW_TO_SOLVE},
    {"wootzWalletAddressMissingChecksumInfoWarning",
     IDS_WOOTZ_WALLET_ADDRESS_MISSING_CHECKSUM_INFO_WARNING},
    {"wootzWalletNotValidChecksumAddressError",
     IDS_WOOTZ_WALLET_NOT_VALID_CHECKSUM_ADDRESS_ERROR},
    {"wootzWalletMissingGasLimitError",
     IDS_WOOTZ_WALLET_MISSING_GAS_LIMIT_ERROR},
    {"wootzWalletZeroBalanceError", IDS_WOOTZ_WALLET_ZERO_BALANCE_ERROR},
    {"wootzWalletAddressRequiredError",
     IDS_WOOTZ_WALLET_ADDRESS_REQUIRED_ERROR},
    {"wootzWalletInvalidZcashUnifiedRecipientAddress",
     IDS_WOOTZ_WALLET_INVALID_ZCASH_UNIFIED_RECIPIENT_ADDRESS},
    {"wootzWalletChecksumModalTitle", IDS_WOOTZ_WALLET_CHECKSUM_MODAL_TITLE},
    {"wootzWalletChecksumModalDescription",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_DESCRIPTION},
    {"wootzWalletChecksumModalStepOneTitle",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_STEP_ONE_TITLE},
    {"wootzWalletChecksumModalStepOneDescription",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_STEP_ONE_DESCRIPTION},
    {"wootzWalletChecksumModalStepTwoTitle",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_STEP_TWO_TITLE},
    {"wootzWalletChecksumModalStepTwoDescription",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_STEP_TWO_DESCRIPTION},
    {"wootzWalletChecksumModalNeedHelp",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_NEED_HELP},
    {"wootzWalletQueueOf", IDS_WOOTZ_WALLET_QUEUE_OF},
    {"wootzWalletQueueNext", IDS_WOOTZ_WALLET_QUEUE_NEXT},
    {"wootzWalletQueueFirst", IDS_WOOTZ_WALLET_QUEUE_FIRST},
    {"wootzWalletQueueRejectAll", IDS_WOOTZ_WALLET_QUEUE_REJECT_ALL},
    {"wootzWalletSwapInsufficientBalance",
     IDS_WOOTZ_WALLET_SWAP_INSUFFICIENT_BALANCE},
    {"wootzWalletSwapInsufficientFundsForGas",
     IDS_WOOTZ_WALLET_SWAP_INSUFFICIENT_FUNDS_FOR_GAS},
    {"wootzWalletSwapInsufficientLiquidity",
     IDS_WOOTZ_WALLET_SWAP_INSUFFICIENT_LIQUIDITY},
    {"wootzWalletSwapInsufficientAllowance",
     IDS_WOOTZ_WALLET_SWAP_INSUFFICIENT_ALLOWANCE},
    {"wootzWalletSwapUnknownError", IDS_WOOTZ_WALLET_SWAP_UNKNOWN_ERROR},
    {"wootzWalletSwapReviewSpend", IDS_WOOTZ_WALLET_SWAP_REVIEW_SPEND},
    {"wootzWalletSwapReviewReceive", IDS_WOOTZ_WALLET_SWAP_REVIEW_RECEIVE},
    {"wootzWalletSwapReviewHeader", IDS_WOOTZ_WALLET_SWAP_REVIEW_HEADER},
    {"wootzWalletSolanaSwap", IDS_WOOTZ_WALLET_SOLANA_SWAP},
    {"wootzWalletUnlockError", IDS_WOOTZ_WALLET_UNLOCK_ERROR},
    {"wootzWalletDeviceUnknownScheme", IDS_WOOTZ_WALLET_UNKNOWN_SCHEME_ERROR},
    {"wootzWalletApprovalTransactionIntent",
     IDS_WOOTZ_WALLET_APPROVAL_TRANSACTION_INTENT},
    {"wootzWalletNoAccountsWithABalance",
     IDS_WOOTZ_WALLET_NO_ACCOUNTS_WITH_A_BALANCE},
    {"wootzWalletNoAccountsWithABalanceDescription",
     IDS_WOOTZ_WALLET_NO_ACCOUNTS_WITH_A_BALANCE_DESCRIPTION},
    {"wootzWalletLedgerFilecoinUnlockError",
     IDS_WOOTZ_WALLET_LEDGER_FILECOIN_UNLOCK_ERROR},
    {"wootzWalletLedgerValidationError",
     IDS_WOOTZ_WALLET_LEDGER_VALIDATION_ERROR},
    {"wootzWalletHardwareAccountNotFound",
     IDS_WOOTZ_WALLET_HARDWARE_ACCOUNT_NOT_FOUND_ERROR},
    {"wootzWalletCreateBridgeError",
     IDS_WOOTZ_WALLET_HARDWARE_CREATE_BRIDGE_ERROR},
    {"wootzWalletProcessTransactionError",
     IDS_WOOTZ_WALLET_HARDWARE_PROCESS_TRANSACTION_ERROR},
    {"wootzWalletApproveTransactionError",
     IDS_WOOTZ_WALLET_HARDWARE_APPROVE_TRANSACTION_ERROR},
    {"wootzWalletTransactionNotFoundSignError",
     IDS_WOOTZ_WALLET_HARDWARE_TRANSACTION_NOT_FOUND_ERROR},
    {"wootzWalletSignOnDeviceError",
     IDS_WOOTZ_WALLET_HARDWARE_TRANSACTION_DEVICE_ERROR},
    {"wootzWalletNoMessageToSignError",
     IDS_WOOTZ_WALLET_HARDWARE_TRANSACTION_NO_MESSAGE_TO_SIGN_ERROR},
    {"wootzWalletProcessMessageError",
     IDS_WOOTZ_WALLET_HARDWARE_SIGN_MESSAGE_ERROR},
    {"wootzWalletHardwareOperationUnsupportedError",
     IDS_WOOTZ_WALLET_HARDWARE_OPERATION_UNSUPPORTED_ERROR},
    {"wootzWalletUnknownKeyringError",
     IDS_WOOTZ_WALLET_HARDWARE_UNKNOWN_KEYRING_ERROR},
    {"wootzWalletBridgeCommandInProgress",
     IDS_WOOTZ_WALLET_HARDWARE_COMMAND_IN_PROGRESS_ERROR},
    {"wootzWalletBridgeNotReady",
     IDS_WOOTZ_WALLET_HARDWARE_BRIDGE_NOT_READY_ERROR},
    {"wootzWalletAddSuggestedTokenTitle",
     IDS_WOOTZ_WALLET_ADD_SUGGESTED_TOKEN_TITLE},
    {"wootzWalletAddSuggestedTokenDescription",
     IDS_WOOTZ_WALLET_ADD_SUGGESTED_TOKEN_DESCRIPTION},
    {"wootzWalletNFTDetailBlockchain", IDS_WOOTZ_WALLET_NFT_DETAIL_BLOCKCHAIN},
    {"wootzWalletNFTDetailTokenStandard",
     IDS_WOOTZ_WALLET_NFT_DETAIL_TOKEN_STANDARD},
    {"wootzWalletNFTDetailTokenID", IDS_WOOTZ_WALLET_NFT_DETAIL_TOKEN_ID},
    {"wootzWalletNFTDetailContractAddress",
     IDS_WOOTZ_WALLET_NFT_DETAIL_CONTRACT_ADDRESS},
    {"wootzWalletNFTDetailDescription",
     IDS_WOOTZ_WALLET_NFT_DETAIL_DESCRIPTION},
    {"wootzWalletNFTDetailImageAddress",
     IDS_WOOTZ_WALLET_NFT_DETAIL_IMAGE_ADDRESS},
    {"wootzWalletNFTDetailsOverview", IDS_WOOTZ_WALLET_NFT_DETAILS_OVERVIEW},
    {"wootzWalletNFTDetailsOwnedBy", IDS_WOOTZ_WALLET_NFT_DETAILS_OWNED_BY},
    {"wootzWalletNFTDetailsViewAccount",
     IDS_WOOTZ_WALLET_NFT_DETAILS_VIEW_ACCOUNT},
    {"wootzWalletNFTDetailsPinningStatusLabel",
     IDS_WOOTZ_WALLET_NFT_DETAILS_PINNING_STATUS_LABEL},
    {"wootzWalletNFTDetailsCid", IDS_WOOTZ_WALLET_NFT_DETAILS_CID},
    {"wootzWalletNFTDetailsNotAvailable",
     IDS_WOOTZ_WALLET_NFT_DETAILS_NOT_AVAILABLE},
    {"wootzWalletNFTDetailsProperties",
     IDS_WOOTZ_WALLET_NFT_DETAILS_PROPERTIES},
    {"wootzWalletTrezorSignTypedDataError",
     IDS_WOOTZ_WALLET_TREZOR_SIGN_TYPED_DATA_ERROR},
    {"wootzWalletSweepstakesTitle", IDS_WOOTZ_WALLET_SWEEPSTAKES_TITLE},
    {"wootzWalletSweepstakesDescription",
     IDS_WOOTZ_WALLET_SWEEPSTAKES_DESCRIPTION},
    {"wootzWalletSweepstakesCallToAction",
     IDS_WOOTZ_WALLET_SWEEPSTAKES_CALL_TO_ACTION},
    {"wootzWalletNotValidFilAddress", IDS_WOOTZ_WALLET_NOT_VALID_FIL_ADDRESS},
    {"wootzWalletBuyWithRamp", IDS_WOOTZ_WALLET_BUY_WITH_RAMP},
    {"wootzWalletSellWithProvider", IDS_WOOTZ_WALLET_SELL_WITH_PROVIDER},
    {"wootzWalletBuyDisclaimer", IDS_WOOTZ_WALLET_BUY_DISCLAIMER},
    {"wootzWalletBuyWithSardine", IDS_WOOTZ_WALLET_BUY_WITH_SARDINE},
    {"wootzWalletBuyWithTransak", IDS_WOOTZ_WALLET_BUY_WITH_TRANSAK},
    {"wootzWalletBuyWithStripe", IDS_WOOTZ_WALLET_BUY_WITH_STRIPE},
    {"wootzWalletBuyWithCoinbase", IDS_WOOTZ_WALLET_BUY_WITH_COINBASE},
    {"wootzWalletBuyRampNetworkName", IDS_WOOTZ_WALLET_BUY_RAMP_NETWORK_NAME},
    {"wootzWalletBuySardineName", IDS_WOOTZ_WALLET_BUY_SARDINE_NAME},
    {"wootzWalletBuyTransakName", IDS_WOOTZ_WALLET_BUY_TRANSAK_NAME},
    {"wootzWalletBuyStripeName", IDS_WOOTZ_WALLET_BUY_STRIPE_NAME},
    {"wootzWalletBuyCoinbaseName", IDS_WOOTZ_WALLET_BUY_COINBASE_NAME},
    {"wootzWalletBuyRampDescription", IDS_WOOTZ_WALLET_BUY_RAMP_DESCRIPTION},
    {"wootzWalletBuySardineDescription",
     IDS_WOOTZ_WALLET_BUY_SARDINE_DESCRIPTION},
    {"wootzWalletBuyTransakDescription",
     IDS_WOOTZ_WALLET_BUY_TRANSAK_DESCRIPTION},
    {"wootzWalletBuyStripeDescription",
     IDS_WOOTZ_WALLET_BUY_STRIPE_DESCRIPTION},
    {"wootzWalletBuyCoinbaseDescription",
     IDS_WOOTZ_WALLET_BUY_COINBASE_DESCRIPTION},
    {"wootzWalletNetworkFilterAll", IDS_WOOTZ_WALLET_NETWORK_FILTER_ALL},
    {"wootzWalletAssetFilterLowToHigh",
     IDS_WOOTZ_WALLET_ASSET_FILTER_LOW_TO_HIGH},
    {"wootzWalletAssetFilterHighToLow",
     IDS_WOOTZ_WALLET_ASSET_FILTER_HIGH_TO_LOW},
    {"wootzWalletAssetFilterAToZ", IDS_WOOTZ_WALLET_ASSET_FILTER_A_TO_Z},
    {"wootzWalletAssetFilterZToA", IDS_WOOTZ_WALLET_ASSET_FILTER_Z_TO_A},
    {"wootzWalletNone", IDS_WOOTZ_WALLET_NONE},
    {"wootzWalletNetworks", IDS_WOOTZ_WALLET_NETWORKS},
    {"wootzWalletPortfolioGroupByTitle",
     IDS_WOOTZ_WALLET_PORTFOLIO_GROUP_BY_TITLE},
    {"wootzWalletPortfolioGroupByDescription",
     IDS_WOOTZ_WALLET_PORTFOLIO_GROUP_BY_DESCRIPTION},
    {"wootzWalletPortfolioFiltersTitle",
     IDS_WOOTZ_WALLET_PORTFOLIO_FILTERS_TITLE},
    {"wootzWalletPortfolioNftsFiltersTitle",
     IDS_WOOTZ_WALLET_PORTFOLIO_NFTS_FILTERS_TITLE},
    {"wootzWalletSortAssets", IDS_WOOTZ_WALLET_SORT_ASSETS},
    {"wootzWalletSortAssetsDescription",
     IDS_WOOTZ_WALLET_SORT_ASSETS_DESCRIPTION},
    {"wootzWalletHideSmallBalances", IDS_WOOTZ_WALLET_SMALL_BALANCES},
    {"wootzWalletHideSmallBalancesDescription",
     IDS_WOOTZ_WALLET_SMALL_BALANCES_DESCRIPTION},
    {"wootzWalletSelectAccounts", IDS_WOOTZ_WALLET_SELECT_ACCOUNTS},
    {"wootzWalletSelectNetworks", IDS_WOOTZ_WALLET_SELECT_NETWORKS},
    {"wootzWalletSelectAll", IDS_WOOTZ_WALLET_SELECT_ALL},
    {"wootzWalletDeselectAll", IDS_WOOTZ_WALLET_DESELECT_ALL},
    {"wootzWalletPrimaryNetworks", IDS_WOOTZ_WALLET_PRIMARY_NETWORKS},
    {"wootzWalletETHAccountDescription",
     IDS_WOOTZ_WALLET_ETH_ACCOUNT_DESCRIPTION},
    {"wootzWalletSOLAccountDescription",
     IDS_WOOTZ_WALLET_SOL_ACCOUNT_DESCRIPTION},
    {"wootzWalletFILAccountDescription",
     IDS_WOOTZ_WALLET_FIL_ACCOUNT_DESCRIPTION},
    {"wootzWalletBTCMainnetAccountDescription",
     IDS_WOOTZ_WALLET_BTC_MAINNET_ACCOUNT_DESCRIPTION},
    {"wootzWalletBTCTestnetAccountDescription",
     IDS_WOOTZ_WALLET_BTC_TESTNET_ACCOUNT_DESCRIPTION},
    {"wootzWalletZECAccountDescription",
     IDS_WOOTZ_WALLET_ZEC_ACCOUNT_DESCRIPTION},
    {"wootzWalletZECTestnetAccountDescription",
     IDS_WOOTZ_WALLET_ZEC_TESTNET_ACCOUNT_DESCRIPTION},
    {"wootzWalletShowNetworkLogoOnNftsTitle",
     IDS_WOOTZ_WALLET_SHOW_NETWORK_LOGO_ON_NFTS_TITLE},
    {"wootzWalletShowNetworkLogoOnNftsDescription",
     IDS_WOOTZ_WALLET_SHOW_NETWORK_LOGO_ON_NFTS_DESCRIPTION},
    {"wootzWalletShowSpamNftsTitle", IDS_WOOTZ_WALLET_SHOW_SPAM_NFTS_TITLE},
    {"wootzWalletShowSpamNftsDescription",
     IDS_WOOTZ_WALLET_SHOW_SPAM_NFTS_DESCRIPTION},
    {"wootzWalletPortfolioSettings", IDS_WOOTZ_WALLET_PORTFOLIO_SETTINGS},
    {"wootzWalletAccountFilterAllAccounts",
     IDS_WOOTZ_WALLET_ACCOUNT_FILTER_ALL_ACCOUNTS},
    {"wootzWalletTransactionSubmittedTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_SUBMITTED_TITLE},
    {"wootzWalletTransactionSubmittedDescription",
     IDS_WOOTZ_WALLET_TRANSACTION_SUBMITTED_DESCRIPTION},
    {"wootzWalletTransactionSignedTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_SIGNED_TITLE},
    {"wootzWalletTransactionSignedDescription",
     IDS_WOOTZ_WALLET_TRANSACTION_SIGNED_DESCRIPTION},
    {"wootzWalletTransactionFailedHeaderTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_HEADER_TITLE},
    {"wootzWalletTransactionFailedTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_TITLE},
    {"wootzWalletTransactionFailedDescription",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_DESCRIPTION},
    {"wootzWalletTransactionFailedSwapNextCTA",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_SWAP_NEXT_CTA},
    {"wootzWalletTransactionFailedNextCTA",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_NEXT_CTA},
    {"wootzWalletTransactionFailedViewErrorCTA",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_VIEW_ERROR_CTA},
    {"wootzWalletTransactionFailedReceiptCTA",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_RECEIPT_CTA},
    {"wootzWalletTransactionFailedModalTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_MODAL_TITLE},
    {"wootzWalletTransactionFailedModalSubtitle",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_MODAL_SUBTITLE},
    {"wootzWalletTransactionCompleteSwapHeaderTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_COMPLETE_SWAP_HEADER_TITLE},
    {"wootzWalletTransactionCompleteTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_COMPLETE_TITLE},
    {"wootzWalletTransactionCompleteDescription",
     IDS_WOOTZ_WALLET_TRANSACTION_COMPLETE_DESCRIPTION},
    {"wootzWalletTransactionCompleteReceiptCTA",
     IDS_WOOTZ_WALLET_TRANSACTION_COMPLETE_RECEIPT_CTA},
    {"wootzWalletTransactionConfirmingTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_CONFIRMING_TITLE},
    {"wootzWalletTransactionConfirmingDescription",
     IDS_WOOTZ_WALLET_TRANSACTION_CONFIRMING_DESCRIPTION},
    {"wootzWalletTransactionConfirmingText",
     IDS_WOOTZ_WALLET_TRANSACTION_CONFIRMING_TEXT},
    {"wootzWalletTransactionIntentDappInteraction",
     IDS_WOOTZ_WALLET_TRANSACTION_INTENT_DAPP_INTERACTION},
    {"wootzWalletTransactionIntentSend",
     IDS_WOOTZ_WALLET_TRANSACTION_INTENT_SEND},
    {"wootzWalletTransactionIntentSwap",
     IDS_WOOTZ_WALLET_TRANSACTION_INTENT_SWAP},
    {"wootzWalletSignInWithWootzWallet",
     IDS_WOOTZ_WALLET_SIGN_IN_WITH_WOOTZ_WALLET},
    {"wootzWalletSignInWithWootzWalletMessage",
     IDS_WOOTZ_WALLET_SIGN_IN_WITH_WOOTZ_WALLET_MESSAGE},
    {"wootzWalletSeeDetails", IDS_WOOTZ_WALLET_SEE_DETAILS},
    {"wootzWalletSignIn", IDS_WOOTZ_WALLET_SIGN_IN},
    {"wootzWalletOrigin", IDS_WOOTZ_WALLET_ORIGIN},
    {"wootzWalletAddress", IDS_WOOTZ_WALLET_ADDRESS},
    {"wootzWalletStatement", IDS_WOOTZ_WALLET_STATEMENT},
    {"wootzWalletUri", IDS_WOOTZ_WALLET_URI},
    {"wootzWalletVersion", IDS_WOOTZ_WALLET_VERSION},
    {"wootzWalletNonce", IDS_WOOTZ_WALLET_NONCE},
    {"wootzWalletIssuedAt", IDS_WOOTZ_WALLET_ISSUED_AT},
    {"wootzWalletExpirationTime", IDS_WOOTZ_WALLET_EXPIRATION_TIME},
    {"wootzWalletNotBefore", IDS_WOOTZ_WALLET_NOT_BEFORE},
    {"wootzWalletRequestId", IDS_WOOTZ_WALLET_REQUEST_ID},
    {"wootzWalletResources", IDS_WOOTZ_WALLET_RESOURCES},
    {"wootzWalletSecurityRiskDetected",
     IDS_WOOTZ_WALLET_SECURITY_RISK_DETECTED},
    {"wootzWalletEditGasLimitError", IDS_WOOTZ_WALLET_EDIT_GAS_LIMIT_ERROR},
    {"wootzWalletApproveTransaction", IDS_WOOTZ_WALLET_APPROVE_TRANSACTION},
    {"wootzWalletSolanaSystemProgram", IDS_WOOTZ_WALLET_SOLANA_SYSTEM_PROGRAM},
    {"wootzWalletSolanaConfigProgram", IDS_WOOTZ_WALLET_SOLANA_CONFIG_PROGRAM},
    {"wootzWalletSolanaStakeProgram", IDS_WOOTZ_WALLET_SOLANA_STAKE_PROGRAM},
    {"wootzWalletSolanaVoteProgram", IDS_WOOTZ_WALLET_SOLANA_VOTE_PROGRAM},
    {"wootzWalletSolanaBPFLoader", IDS_WOOTZ_WALLET_SOLANA_BP_FLOADER},
    {"wootzWalletSolanaAccounts", IDS_WOOTZ_WALLET_SOLANA_ACCOUNTS},
    {"wootzWalletSolanaData", IDS_WOOTZ_WALLET_SOLANA_DATA},
    {"wootzWalletSolanaProgramID", IDS_WOOTZ_WALLET_SOLANA_PROGRAM_ID},
    {"wootzWalletSolanaMaxRetries", IDS_WOOTZ_WALLET_SOLANA_MAX_RETRIES},
    {"wootzWalletSolanaPreflightCommitment",
     IDS_WOOTZ_WALLET_SOLANA_PREFLIGHT_COMMITMENT},
    {"wootzWalletSolanaSkipPreflight", IDS_WOOTZ_WALLET_SOLANA_SKIP_PREFLIGHT},
    {"wootzWalletSolanaAddressLookupTableAccount",
     IDS_WOOTZ_WALLET_SOLANA_ADDRESS_LOOKUP_TABLE_ACCOUNT},
    {"wootzWalletSolanaAddressLookupTableIndex",
     IDS_WOOTZ_WALLET_SOLANA_ADDRESS_LOOKUP_TABLE_INDEX},
    {"wootzWalletSolanaEd25519Program",
     IDS_WOOTZ_WALLET_SOLANA_ED25519_PROGRAM},
    {"wootzWalletSolanaSecp256k1Program",
     IDS_WOOTZ_WALLET_SOLANA_SECP256K1_PROGRAM},
    {"wootzWalletNetworkFilterSecondary",
     IDS_WOOTZ_WALLET_NETWORK_FILTER_SECONDARY},
    {"wootzWalletNetworkFilterTestNetworks",
     IDS_WOOTZ_WALLET_NETWORK_FILTER_TEST_NETWORKS},
    {"wootzWalletSelectCurrency", IDS_WOOTZ_WALLET_SELECT_CURRENCY},
    {"wootzWalletSearchCurrency", IDS_WOOTZ_WALLET_SEARCH_CURRENCY},
    {"wootzWalletHelpCenter", IDS_WOOTZ_WALLET_HELP_CENTER},
    {"wootzWalletHelpCenterText", IDS_WOOTZ_WALLET_HELP_CENTER_TEXT},
    {"wootzWalletBuyTapBuyNotSupportedMessage",
     IDS_WOOTZ_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"wootzWalletAuroraModalTitle", IDS_WOOTZ_WALLET_AURORA_MODAL_TITLE},
    {"wootzWalletAuroraModalDescription",
     IDS_WOOTZ_WALLET_AURORA_MODAL_DESCRIPTION},
    {"wootzWalletAuroraModalLearnMore",
     IDS_WOOTZ_WALLET_AURORA_MODAL_LEARN_MORE},
    {"wootzWalletAuroraModalLearnMoreAboutRisk",
     IDS_WOOTZ_WALLET_AURORA_MODAL_LEARN_MORE_ABOUT_RISK},
    {"wootzWalletAuroraModalDontShowAgain",
     IDS_WOOTZ_WALLET_AURORA_MODAL_DONT_SHOW_AGAIN},
    {"wootzWalletAuroraModalOPenButtonText",
     IDS_WOOTZ_WALLET_AURORA_MODAL_OPEN_BUTTON_TEXT},
    {"wootzWalletBridgeToAuroraButton",
     IDS_WOOTZ_WALLET_BRIDGE_TO_AURORA_BUTTON},
    {"wootzWalletPasswordStrengthTooltipHeading",
     IDS_WOOTZ_WALLET_PASSWORD_STRENGTH_TOOLTIP_HEADING},
    {"wootzWalletPasswordStrengthTooltipIsLongEnough",
     IDS_WOOTZ_WALLET_PASSWORD_STRENGTH_TOOLTIP_IS_LONG_ENOUGH},
    {"wootzWalletPasswordMatch", IDS_WOOTZ_WALLET_PASSWORD_MATCH},
    {"wootzWalletPasswordIsStrong", IDS_WOOTZ_WALLET_PASSWORD_IS_STRONG},
    {"wootzWalletPasswordIsMediumStrength",
     IDS_WOOTZ_WALLET_PASSWORD_IS_MEDIUM_STRENGTH},
    {"wootzWalletPasswordIsWeak", IDS_WOOTZ_WALLET_PASSWORD_IS_WEAK},
    {"wootzWalletAutoLockTitle", IDS_WOOTZ_WALLET_AUTO_LOCK_TITLE},
    {"wootzWalletAutoLockDurationMinutes",
     IDS_WOOTZ_WALLET_AUTO_LOCK_DURATION_MINUTES},
    {"wootzWalletAutoLockDurationHours",
     IDS_WOOTZ_WALLET_AUTO_LOCK_DURATION_HOURS},
    {"wootzWalletCreatingWallet", IDS_WOOTZ_WALLET_CREATING_WALLET},
    {"wootzWalletOnboardingRecoveryPhraseBackupIntroTitle",
     IDS_WOOTZ_WALLET_ONBOARDING_RECOVERY_PHRASE_BACKUP_INTRO_TITLE},
    {"wootzWalletOnboardingRecoveryPhraseBackupIntroDescription",
     IDS_WOOTZ_WALLET_ONBOARDING_RECOVERY_PHRASE_BACKUP_INTRO_DESCRIPTION},
    {"wootzWalletRecoveryPhraseBackupWarning",
     IDS_WOOTZ_WALLET_RECOVERY_PHRASE_BACKUP_WARNING},
    {"wootzWalletRecoveryPhraseBackupWarningImportant",
     IDS_WOOTZ_WALLET_RECOVERY_PHRASE_BACKUP_WARNING_IMPORTANT},
    {"wootzWalletRecoveryWordInstructions",
     IDS_WOOTZ_WALLET_RECOVERY_WORD_INSTRUCTIONS},
    {"wootzWalletVerifyRecoveryPhraseGoBack",
     IDS_WOOTZ_WALLET_VERIFY_RECOVERY_PHRASE_GO_BACK},
    {"wootzWalletRecoveryPhraseBackupTitle",
     IDS_WOOTZ_WALLET_RECOVERY_PHRASE_BACKUP_TITLE},
    {"wootzWalletCopiedToClipboard", IDS_WOOTZ_WALLET_COPIED_TO_CLIPBOARD},
    {"wootzWalletClickToSeeRecoveryPhrase",
     IDS_WOOTZ_WALLET_CLICK_TO_SEE_RECOVERY_PHRASE},
    {"wootzWalletOrdinalFirst", IDS_WOOTZ_WALLET_ORDINAL_FIRST},
    {"wootzWalletOrdinalThird", IDS_WOOTZ_WALLET_ORDINAL_THIRD},
    {"wootzWalletOnboardingSuccessTitle",
     IDS_WOOTZ_WALLET_ONBOARDING_SUCCESS_TITLE},
    {"wootzWalletOnboardingSuccessDescription",
     IDS_WOOTZ_WALLET_ONBOARDING_SUCCESS_DESCRIPTION},
    {"wootzWalletOnboardingSuccessGoToPortfolio",
     IDS_WOOTZ_WALLET_ONBOARDING_SUCCESS_GO_TO_PORTFOLIO},
    {"wootzWalletArticleLinkWhatsARecoveryPhrase",
     IDS_WOOTZ_WALLET_ARTICLE_LINK_WHATS_A_RECOVERY_PHRASE},
    {"wootzWalletImportOrRestoreWalletTitle",
     IDS_WOOTZ_WALLET_IMPORT_OR_RESTORE_WALLET_TITLE},
    {"wootzWalletImportOrRestoreDescription",
     IDS_WOOTZ_WALLET_IMPORT_OR_RESTORE_DESCRIPTION},
    {"wootzWalletRestoreMyWootzWallet",
     IDS_WOOTZ_WALLET_RESTORE_MY_WOOTZ_WALLET},
    {"wootzWalletRestoreMyWootzWalletInstructions",
     IDS_WOOTZ_WALLET_RESTORE_MY_WOOTZ_WALLET_INSTRUCTIONS},
    {"wootzWalletRestoreMyWootzWalletDescription",
     IDS_WOOTZ_WALLET_RESTORE_MY_WOOTZ_WALLET_DESCRIPTION},
    {"wootzWalletImportFromMetaMask", IDS_WOOTZ_WALLET_IMPORT_FROM_META_MASK},
    {"wootzWalletImportFromMetaMaskDescription",
     IDS_WOOTZ_WALLET_IMPORT_FROM_META_MASK_DESCRIPTION},
    {"wootzWalletImportFromMetaMaskSeedInstructions",
     IDS_WOOTZ_WALLET_IMPORT_FROM_META_MASK_SEED_INSTRUCTIONS},
    {"wootzWalletCreateWalletInsteadLink",
     IDS_WOOTZ_WALLET_CREATE_WALLET_INSTEAD_LINK},
    {"wootzWalletRestoreAlternateLength",
     IDS_WOOTZ_WALLET_RESTORE_ALTERNATE_LENGTH},
    {"wootzWalletRestoreWalletError", IDS_WOOTZ_WALLET_RESTORE_WALLET_ERROR},
    {"wootzWalletImportWithRecoveryPhrase",
     IDS_WOOTZ_WALLET_IMPORT_WITH_RECOVERY_PHRASE},
    {"wootzWalletMetamaskDetected", IDS_WOOTZ_WALLET_METAMASK_DETECTED},
    {"wootzWalletUsePassword", IDS_WOOTZ_WALLET_USE_PASSWORD},
    {"wootzWalletRecoveryPhraseWord", IDS_WOOTZ_WALLET_RECOVERY_PHRASE_WORD},
    {"wootzWalletImportPasswordError", IDS_WOOTZ_WALLET_IMPORT_PASSWORD_ERROR},
    {"wootzWalletMetaMaskExtensionDetected",
     IDS_WOOTZ_WALLET_METAMASK_EXTENSION_DETECTED},
    {"wootzWalletMetaMaskExtensionImportDescription",
     IDS_WOOTZ_WALLET_METAMASK_EXTENSION_IMPORT_DESCRIPTION},
    {"wootzWalletMetaMaskPasswordInputPlaceholder",
     IDS_WOOTZ_WALLET_METAMASK_PASSWORD_INPUT_PLACEHOLDER},
    {"wootzWalletInputLabelPassword", IDS_WOOTZ_WALLET_INPUT_LABEL_PASSWORD},
    {"wootzWalletLearnAboutMyWallet", IDS_WOOTZ_WALLET_LEARN_ABOUT_MY_WALLET},
    {"wootzWalletDisclosuresTitle", IDS_WOOTZ_WALLET_DISCLOSURES_TITLE},
    {"wootzWalletDisclosuresDescription",
     IDS_WOOTZ_WALLET_DISCLOSURES_DESCRIPTION},
    {"wootzWalletSelfCustodyDisclosureCheckboxText",
     IDS_WOOTZ_WALLET_SELF_CUSTODY_DISCLOSURE_CHECKBOX_TEXT},
    {"wootzWalletTermsOfServiceCheckboxText",
     IDS_WOOTZ_WALLET_TERMS_OF_SERVICE_CHECKBOX_TEXT},
    {"wootzWalletBuyCryptoButton", IDS_WOOTZ_WALLET_BUY_CRYPTO_BUTTON},
    {"wootzWalletDepositCryptoButton", IDS_WOOTZ_WALLET_DEPOSIT_CRYPTO_BUTTON},
    {"wootzWalletCheckingInstalledExtensions",
     IDS_WOOTZ_WALLET_CHECKING_INSTALLED_EXTENSIONS},
    {"wootzWalletImportFromLegacy", IDS_WOOTZ_WALLET_IMPORT_FROM_LEGACY},
    {"wootzWalletBuySelectAsset", IDS_WOOTZ_WALLET_BUY_SELECT_ASSET},
    {"wootzWalletFundWalletTitle", IDS_WOOTZ_WALLET_FUND_WALLET_TITLE},
    {"wootzWalletDepositFundsTitle", IDS_WOOTZ_WALLET_DEPOSIT_FUNDS_TITLE},
    {"wootzWalletDepositX", IDS_WOOTZ_WALLET_DEPOSIT_X},
    {"wootzWalletDepositSolSplTokens", IDS_WOOTZ_WALLET_DEPOSIT_SOL_SPL_TOKENS},
    {"wootzWalletDepositErc", IDS_WOOTZ_WALLET_DEPOSIT_ERC},
    {"wootzWalletDepositOnlySendOnXNetwork",
     IDS_WOOTZ_WALLET_DEPOSIT_ONLY_SEND_ON_X_NETWORK},
    {"wootzWalletFundWalletDescription",
     IDS_WOOTZ_WALLET_FUND_WALLET_DESCRIPTION},
    {"wootzWalletLearnMoreAboutWootzWallet",
     IDS_WOOTZ_WALLET_LEARN_MORE_ABOUT_WOOTZ_WALLET},
    {"wootzWalletMarketDataAllAssetsFilter",
     IDS_WOOTZ_WALLET_MARKET_DATA_ALL_ASSETS_FILTER},
    {"wootzWalletMarketDataTradableFilter",
     IDS_WOOTZ_WALLET_MARKET_DATA_TRADABLE_FILTER},
    {"wootzWalletMarketDataAssetsColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_ASSETS_COLUMN},
    {"wootzWalletMarketDataPriceColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_PRICE_COLUMN},
    {"wootzWalletMarketData24HrColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_24Hr_COLUMN},
    {"wootzWalletMarketDataMarketCapColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_MARKETCAP_COLUMN},
    {"wootzWalletMarketDataVolumeColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_VOLUME_COLUMN},
    {"wootzWalletMarketDataNoAssetsFound",
     IDS_WOOTZ_WALLET_MARKET_DATA_NO_ASSETS_FOUND},
    {"wootzWalletInformation", IDS_WOOTZ_WALLET_INFORMATION},
    {"wootzWalletRankStat", IDS_WOOTZ_WALLET_RANK_STAT},
    {"wootzWalletVolumeStat", IDS_WOOTZ_WALLET_VOLUME_STAT},
    {"wootzWalletMarketCapStat", IDS_WOOTZ_WALLET_MARKET_CAP_STAT},
    {"wootzWalletBuyTapBuyNotSupportedMessage",
     IDS_WOOTZ_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"wootzWalletHelpCenterText", IDS_WOOTZ_WALLET_HELP_CENTER_TEXT},
    {"wootzWalletMarketDataAllAssetsFilter",
     IDS_WOOTZ_WALLET_MARKET_DATA_ALL_ASSETS_FILTER},
    {"wootzWalletMarketDataTradableFilter",
     IDS_WOOTZ_WALLET_MARKET_DATA_TRADABLE_FILTER},
    {"wootzWalletMarketDataAssetsColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_ASSETS_COLUMN},
    {"wootzWalletMarketDataPriceColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_PRICE_COLUMN},
    {"wootzWalletMarketData24HrColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_24Hr_COLUMN},
    {"wootzWalletMarketDataMarketCapColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_MARKETCAP_COLUMN},
    {"wootzWalletMarketDataVolumeColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_VOLUME_COLUMN},
    {"wootzWalletMarketDataBuyDepositColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_BUY_DEPOSIT_COLUMN},
    {"wootzWalletMarketDataNoAssetsFound",
     IDS_WOOTZ_WALLET_MARKET_DATA_NO_ASSETS_FOUND},
    {"wootzWalletInformation", IDS_WOOTZ_WALLET_INFORMATION},
    {"wootzWalletRankStat", IDS_WOOTZ_WALLET_RANK_STAT},
    {"wootzWalletVolumeStat", IDS_WOOTZ_WALLET_VOLUME_STAT},
    {"wootzWalletMarketCapStat", IDS_WOOTZ_WALLET_MARKET_CAP_STAT},
    {"wootzWalletBuyTapBuyNotSupportedMessage",
     IDS_WOOTZ_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"wootzWalletSearchingForDomain", IDS_WOOTZ_WALLET_SEARCHING_FOR_DOMAIN},
    {"wootzWalletEnsOffChainLookupTitle",
     IDS_WOOTZ_WALLET_ENS_OFF_CHAIN_LOOKUP_TITLE},
    {"wootzWalletEnsOffChainLookupDescription",
     IDS_WOOTZ_WALLET_ENS_OFF_CHAIN_LOOKUP_DESCRIPTION},
    {"wootzWalletEnsOffChainButton", IDS_WOOTZ_WALLET_ENS_OFF_CHAIN_BUTTON},
    {"wootzWalletPortfolioTokenDetailsMenuLabel",
     IDS_WOOTZ_WALLET_PORTFOLIO_TOKEN_DETAILS_MENU_LABEL},
    {"wootzWalletPortfolioViewOnExplorerMenuLabel",
     IDS_WOOTZ_WALLET_PORTFOLIO_VIEW_ON_EXPLORER_MENU_LABEL},
    {"wootzWalletPortfolioHideTokenMenuLabel",
     IDS_WOOTZ_WALLET_PORTFOLIO_VIEW_HIDE_TOKEN_LABEL},
    {"wootzWalletHideTokenModalTitle", IDS_WOOTZ_WALLET_HIDE_TOKEN_MODAL_TITLE},
    {"wootzWalletTokenContractAddress",
     IDS_WOOTZ_WALLET_TOKEN_CONTRACT_ADDRESS},
    {"wootzWalletTokenDecimal", IDS_WOOTZ_WALLET_TOKEN_DECIMAL},
    {"wootzWalletMakeTokenVisibleInstructions",
     IDS_WOOTZ_WALLET_MAKE_TOKEN_VISIBLE_INSTRUCTIONS},
    {"wootzWalletConfirmHidingToken", IDS_WOOTZ_WALLET_CONFIRM_HIDING_TOKEN},
    {"wootzWalletCancelHidingToken", IDS_WOOTZ_WALLET_CANCEL_HIDING_TOKEN},
    {"wootzWalletMyAssets", IDS_WOOTZ_WALLET_MY_ASSETS},
    {"wootzWalletAvailableAssets", IDS_WOOTZ_WALLET_AVAILABLE_ASSETS},
    {"wootzWalletDidntFindAssetEndOfList",
     IDS_WOOTZ_WALLET_DIDNT_FIND_ASSET_END_OF_LIST},
    {"wootzWalletDidntFindAssetInList",
     IDS_WOOTZ_WALLET_DIDNT_FIND_ASSET_IN_LIST},
    {"wootzWalletAssetNotFound", IDS_WOOTZ_WALLET_ASSET_NOT_FOUND},
    {"wootzWalletRequestFeatureButtonText",
     IDS_WOOTZ_WALLET_REQUEST_FEATURE_BUTTON_TEXT},
    {"wootzWalletEnsOffchainProceedWithYes",
     IDS_WOOTZ_WALLET_ENS_OFFCHAIN_PROCEED_WITH_YES},
    {"wootzWalletEnsOffchainProceedWithNo",
     IDS_WOOTZ_WALLET_ENS_OFFCHAIN_PROCEED_WITH_NO},
    {"wootzWalletEnsOffchainDontShowAgain",
     IDS_WOOTZ_WALLET_ENS_OFFCHAIN_DONT_SHOW_AGAIN},
    {"wootzWalletEnsOffchainWarning", IDS_WOOTZ_WALLET_ENS_OFFCHAIN_WARNING},
    {"wootzWalletAddAssetTokenTabTitle",
     IDS_WOOTZ_WALLET_ADD_ASSET_TOKEN_TAB_TITLE},
    {"wootzWalletAddAssetNftTabTitle",
     IDS_WOOTZ_WALLET_ADD_ASSET_NFT_TAB_TITLE},
    {"wootzWalletNftFetchingError", IDS_WOOTZ_WALLET_NFT_FETCHING_ERROR},
    {"wootzWalletEditToken", IDS_WOOTZ_WALLET_EDIT_TOKEN},
    {"wootzWalletFEVMAddressTranslationTitle",
     IDS_WOOTZ_WALLET_FEVM_ADDRESS_TRANSLATION_TITLE},
    {"wootzWalletFEVMAddressTranslationDescription",
     IDS_WOOTZ_WALLET_FEVM_ADDRESS_TRANSLATION_DESCRIPTION},

    // Wootz Swap
    {"wootzSwap", IDS_WOOTZ_SWAP},
    {"wootzSwapApproveToken", IDS_WOOTZ_SWAP_APPROVE_TOKEN},
    {"wootzSwapInsufficientBalance", IDS_WOOTZ_SWAP_INSUFFICIENT_BALANCE},
    {"wootzSwapInsufficientLiquidity", IDS_WOOTZ_SWAP_INSUFFICIENT_LIQUIDITY},
    {"wootzSwapSelectToken", IDS_WOOTZ_SWAP_SELECT_TOKEN},
    {"wootzSwapHalf", IDS_WOOTZ_SWAP_HALF},
    {"wootzSwapMax", IDS_WOOTZ_SWAP_MAX},
    {"wootzSwapEnterAnAmount", IDS_WOOTZ_SWAP_ENTER_AN_AMOUNT},
    {"wootzWalletFetchingQuote", IDS_WOOTZ_WALLET_FETCHING_QUOTE},
    {"wootzWalletReceiveEstimate", IDS_WOOTZ_WALLET_RECEIVE_ESTIMATE},
    {"wootzWalletFromToken", IDS_WOOTZ_WALLET_FROM_TOKEN},
    {"wootzWalletToToken", IDS_WOOTZ_WALLET_TO_TOKEN},
    {"wootzWalletNewQuoteIn", IDS_WOOTZ_WALLET_NEW_QUOTE_IN},
    {"wootzSwapBalance", IDS_WOOTZ_SWAP_BALANCE},
    {"wootzSwapSelectAToken", IDS_WOOTZ_SWAP_SELECT_A_TOKEN},
    {"wootzSwapShowTokensWithZeroBalances",
     IDS_WOOTZ_SWAP_SHOW_TOKENS_WITH_ZERO_BALANCES},
    {"wootzSwapHideTokensWithZeroBalances",
     IDS_WOOTZ_SWAP_HIDE_TOKENS_WITH_ZERO_BALANCES},
    {"wootzSwapSearchToken", IDS_WOOTZ_SWAP_SEARCH_TOKEN},
    {"wootzSwapOption", IDS_WOOTZ_SWAP_OPTION},
    {"wootzSwapPriceImpact", IDS_WOOTZ_SWAP_PRICE_IMPACT},
    {"wootzSwapMinimumReceivedAfterSlippage",
     IDS_WOOTZ_SWAP_MINIMUM_RECEIVED_AFTER_SLIPPAGE},
    {"wootzSwapNetworkFee", IDS_WOOTZ_SWAP_NETWORK_FEE},
    {"wootzSwapWootzFee", IDS_WOOTZ_SWAP_WOOTZ_FEE},
    {"wootzSwapFree", IDS_WOOTZ_SWAP_FREE},
    {"wootzSwapSwapAndSend", IDS_WOOTZ_SWAP_SWAP_AND_SEND},
    {"wootzSwapNoExtraFees", IDS_WOOTZ_SWAP_NO_EXTRA_FEES},
    {"wootzSwapConfirmAddress", IDS_WOOTZ_SWAP_CONFIRM_ADDRESS},
    {"wootzSwapAddressInputePlaceholder",
     IDS_WOOTZ_SWAP_ADDRESS_INPUT_PLACEHOLDER},
    {"wootzSwapSelectAccount", IDS_WOOTZ_SWAP_SELECT_ACCOUNT},
    {"wootzSwapToAccount", IDS_WOOTZ_SWAP_TO_ACCOUNT},
    {"wootzSwapToAddress", IDS_WOOTZ_SWAP_TO_ADDRESS},
    {"wootzSwapSlow", IDS_WOOTZ_SWAP_SLOW},
    {"wootzSwapAverage", IDS_WOOTZ_SWAP_AVERAGE},
    {"wootzSwapFast", IDS_WOOTZ_SWAP_FAST},
    {"wootzSwapGwei", IDS_WOOTZ_SWAP_GWEI},
    {"wootzSwapSlippageTolerance", IDS_WOOTZ_SWAP_SLIPPAGE_TOLERANCE},
    {"wootzSwapExchanges", IDS_WOOTZ_SWAP_EXCHANGES},
    {"wootzSwapDirectRouteTitle", IDS_WOOTZ_SWAP_DIRECT_ROUTE_TITLE},
    {"wootzSwapDirectRouteDescription",
     IDS_WOOTZ_SWAP_DIRECT_ROUTE_DESCRIPTION},
    {"wootzSwapNetworkFeeDescription", IDS_WOOTZ_SWAP_NETWORK_FEE_DESCRIPTION},
    {"wootzSwapCoinGeckoCheaper", IDS_WOOTZ_SWAP_COINGECKO_CHEAPER},
    {"wootzSwapCoinGeckoWithin", IDS_WOOTZ_SWAP_COINGECKO_WITHIN},
    {"wootzSwapCoinGeckoExpensive", IDS_WOOTZ_SWAP_COINGECKO_EXPENSIVE},
    {"wootzSwapAPI", IDS_WOOTZ_SWAP_API},
    {"wootzSwapName", IDS_WOOTZ_SWAP_NAME},
    {"wootzSwapDisconnectWallet", IDS_WOOTZ_SWAP_DISCONNECT_WALLET},
    {"wootzSwapAdvanced", IDS_WOOTZ_SWAP_ADVANCED},
    {"wootzSwapAccounts", IDS_WOOTZ_SWAP_ACCOUNTS},
    {"wootzSwapWallet", IDS_WOOTZ_SWAP_WALLET},
    {"wootzSwapBest", IDS_WOOTZ_SWAP_BEST},
    {"wootzSwapHelpCenter", IDS_WOOTZ_SWAP_HELP_CENTER},
    {"wootzSwapPrivacyPolicy", IDS_WOOTZ_SWAP_PRIVACY_POLICY},
    {"wootzSwapPrivacyDescription", IDS_WOOTZ_SWAP_PRIVACY_DESCRIPTION},
    {"wootzSwapV2Disclaimer", IDS_WOOTZ_SWAP_V2_DISCLAIMER},
    {"wootzSwapV2Privacy", IDS_WOOTZ_SWAP_V2_PRIVACY},
    {"wootzSwapChangeNetwork", IDS_WOOTZ_SWAP_CHANGE_NETWORK},

    {"wootzNftsTabImportNft", IDS_WOOTZ_WALLET_NFTS_TAB_IMPORT_NFT},
    {"wootzNftsTabEmptyStateHeading",
     IDS_WOOTZ_WALLET_NFTS_TAB_EMPTY_STATE_HEADING},
    {"wootzNftsTabEmptyStateSubHeading",
     IDS_WOOTZ_WALLET_NFTS_TAB_EMPTY_STATE_SUBHEADING},
    {"wootzNftsTabEmptyStateDisclaimer",
     IDS_WOOTZ_WALLET_NFTS_TAB_EMPTY_STATE_DISCLAIMER},
    {"wootzNftsTabHide", IDS_WOOTZ_WALLET_NFTS_TAB_HIDE},
    {"wootzNftsTabUnhide", IDS_WOOTZ_WALLET_NFTS_TAB_UNHIDE},
    {"wootzNftsTabEdit", IDS_WOOTZ_WALLET_NFTS_TAB_EDIT},
    {"wootzWalletNftUnspam", IDS_WOOTZ_WALLET_NFT_UNSPAM},
    {"wootzWalletNftJunk", IDS_WOOTZ_WALLET_NFT_JUNK},
    {"wootzWalletRemoveNftModalHeader",
     IDS_WOOTZ_WALLET_REMOVE_NFT_MODAL_HEADER},
    {"wootzWalletRemoveNftModalDescription",
     IDS_WOOTZ_WALLET_REMOVE_NFT_MODAL_DESCRIPTION},
    {"wootzWalletRemoveNftModalCancel",
     IDS_WOOTZ_WALLET_REMOVE_NFT_MODAL_CANCEL},
    {"wootzWalletRemoveNftModalConfirm",
     IDS_WOOTZ_WALLET_REMOVE_NFT_MODAL_CONFIRM},
    {"wootzWalletNftMoveToSpam", IDS_WOOTZ_WALLET_NFT_MOVE_TO_SPAM},
    {"wootzNftsTab", IDS_WOOTZ_WALLET_NFTS_TAB},
    {"wootzNftsTabHidden", IDS_WOOTZ_WALLET_NFTS_TAB_HIDDEN},
    {"wootzNftsTabCollected", IDS_WOOTZ_WALLET_NFTS_TAB_COLLECTED},
    {"wootzNftsTabRemove", IDS_WOOTZ_WALLET_NFTS_TAB_REMOVE},
    {"wootzWalletAddNftModalTitle", IDS_WOOTZ_WALLET_ADD_NFT_MODAL_TITLE},
    {"wootzWalletEditNftModalTitle", IDS_WOOTZ_WALLET_EDIT_NFT_MODAL_TITLE},
    {"wootzWalletEnableNftAutoDiscoveryModalHeader",
     IDS_WOOTZ_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_HEADER},
    {"wootzWalletEnableNftAutoDiscoveryModalDescription",
     IDS_WOOTZ_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_DESCRIPTION},
    {"wootzWalletEnableNftAutoDiscoveryModalConfirm",
     IDS_WOOTZ_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_CONFIRM},
    {"wootzWalletEnableNftAutoDiscoveryModalCancel",
     IDS_WOOTZ_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_CANCEL},
    {"wootzWalletAutoDiscoveryEmptyStateHeading",
     IDS_WOOTZ_WALLET_AUTO_DISCOVERY_EMPTY_STATE_HEADING},
    {"wootzWalletAutoDiscoveryEmptyStateSubHeading",
     IDS_WOOTZ_WALLET_AUTO_DISCOVERY_EMPTY_STATE_SUB_HEADING},
    {"wootzWalletAutoDiscoveryEmptyStateFooter",
     IDS_WOOTZ_WALLET_AUTO_DISCOVERY_EMPTY_STATE_FOOTER},
    {"wootzWalletAutoDiscoveryEmptyStateActions",
     IDS_WOOTZ_WALLET_AUTO_DISCOVERY_EMPTY_STATE_ACTIONS},
    {"wootzWalletAutoDiscoveryEmptyStateRefresh",
     IDS_WOOTZ_WALLET_AUTO_DISCOVERY_EMPTY_STATE_REFRESH},
    {"wootzWalletUphold", IDS_WOOTZ_WALLET_UPHOLD},
    {"wootzWalletGemini", IDS_WOOTZ_WALLET_GEMINI},
    {"wootzWalletZebpay", IDS_WOOTZ_WALLET_ZEBPAY},
    {"wootzWalletBitflyer", IDS_WOOTZ_WALLET_BITFLYER},
    {"wootzWalletRewardsAccount", IDS_WOOTZ_WALLET_REWARDS_ACCOUNT},
    {"wootzWalletWootzRewardsTitle", IDS_WOOTZ_WALLET_WOOTZ_REWARDS_TITLE},
    {"wootzWalletWootzRewardsDescription",
     IDS_WOOTZ_WALLET_WOOTZ_REWARDS_DESCRIPTION},
    {"wootzWalletWootzRewardsLoggedOutDescription",
     IDS_WOOTZ_WALLET_WOOTZ_REWARDS_LOGGED_OUT_DESCRIPTION},
    {"wootzWalletLogIn", IDS_WOOTZ_WALLET_LOG_IN},
    {"wootzWalletViewOn", IDS_WOOTZ_WALLET_VIEW_ON},
    {"wootzWalletRewardsSettings", IDS_WOOTZ_WALLET_REWARDS_SETTINGS},
    {"wootzWalletPlatforms", IDS_WOOTZ_WALLET_PLATFORMS},
    {"wootzWalletNoDappsFound", IDS_WOOTZ_WALLET_NO_DAPPS_FOUND},
    {"wootzWalletActiveWallets", IDS_WOOTZ_WALLET_ACTIVE_WALLETS},
    {"wootzWalletVisitDapp", IDS_WOOTZ_WALLET_VISIT_DAPP},
    {"wootzWalletFilters", IDS_WOOTZ_WALLET_FILTERS},
    {"wootzWalletClearFilters", IDS_WOOTZ_WALLET_CLEAR_FILTERS},
    {"wootzWalletShowMore", IDS_WOOTZ_WALLET_SHOW_MORE}};

// 0x swap constants
inline constexpr char kZeroExGoerliBaseAPIURL[] =
    "https://goerli.api.0x.wallet.wootz.com";
inline constexpr char kZeroExPolygonBaseAPIURL[] =
    "https://polygon.api.0x.wallet.wootz.com";
inline constexpr char kZeroExBinanceSmartChainBaseAPIURL[] =
    "https://bsc.api.0x.wallet.wootz.com";
inline constexpr char kZeroExAvalancheBaseAPIURL[] =
    "https://avalanche.api.0x.wallet.wootz.com";
inline constexpr char kZeroExFantomBaseAPIURL[] =
    "https://fantom.api.0x.wallet.wootz.com";
inline constexpr char kZeroExCeloBaseAPIURL[] =
    "https://celo.api.0x.wallet.wootz.com";
inline constexpr char kZeroExOptimismBaseAPIURL[] =
    "https://optimism.api.0x.wallet.wootz.com";
inline constexpr char kZeroExArbitrumBaseAPIURL[] =
    "https://arbitrum.api.0x.wallet.wootz.com";
inline constexpr char kZeroExBaseBaseAPIURL[] =
    "https://base.api.0x.wallet.wootz.com";
inline constexpr char kZeroExEthereumBaseAPIURL[] =
    "https://api.0x.wallet.wootz.com";
inline constexpr char kEVMFeeRecipient[] =
    "0xbd9420A98a7Bd6B89765e5715e169481602D9c3d";
inline constexpr char kAffiliateAddress[] =
    "0xbd9420A98a7Bd6B89765e5715e169481602D9c3d";

// Jupiter swap constants
inline constexpr char kJupiterBaseAPIURL[] = "https://jupiter.wallet.wootz.com";
inline constexpr char kJupiterReferralKey[] =
    "7yke2kxg6ewNsun61qBkdsLdxuXcUiB8CMB47Zv39Aoy";
inline constexpr char kJupiterReferralProgram[] =
    "REFER4ZgmyYx9c6He5XfaTMiGfdLwRnkV4RPp9t9iF3";
inline constexpr char kJupiterReferralProgramHeader[] = "referral_ata";
inline constexpr char kWrappedSolanaMintAddress[] =
    "So11111111111111111111111111111111111111112";

// Blowfish simulations constants
inline constexpr char kBlowfishBaseAPIURL[] =
    "https://blowfish.wallet.wootz.com";
inline constexpr char kBlowfishAPIVersionHeader[] = "X-Api-Version";
inline constexpr char kBlowfishAPIVersion[] = "2023-06-05";

// LiFi constants
inline constexpr char kLiFiBaseAPIURL[] = "https://lifi.wallet.wootz.com";
inline constexpr char kLiFiIntegratorID[] = "wootz";
inline constexpr char kLiFiNativeEVMAssetContractAddress[] =
    "0x0000000000000000000000000000000000000000";
inline constexpr char kLiFiNativeSVMAssetContractAddress[] =
    "So11111111111111111111111111111111111111112";

// LiFi // 0x common constants
inline constexpr char kNativeEVMAssetContractAddress[] =
    "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";

constexpr int64_t kBlockTrackerDefaultTimeInSeconds = 20;
constexpr int64_t kLogTrackerDefaultTimeInSeconds = 20;
constexpr int64_t kSolanaBlockTrackerTimeInSeconds = 2;

// Ankr constants
inline constexpr char kAnkrAdvancedAPIBaseURL[] =
    "https://multichain.ankr.wallet.wootz.com/";

// Unstoppable domains record key for ethereum address.
inline constexpr char kCryptoEthAddressKey[] = "crypto.ETH.address";
// Unstoppable domains record key for solana address.
inline constexpr char kCryptoSolAddressKey[] = "crypto.SOL.address";
// Unstoppable domains record key for filecoin address.
inline constexpr char kCryptoFilAddressKey[] = "crypto.FIL.address";

// ERC-165 identifier for ERC721 interface.
inline constexpr char kERC1155InterfaceId[] = "0xd9b67a26";
inline constexpr char kERC1155MetadataInterfaceId[] = "0x0e89341c";
inline constexpr char kERC721InterfaceId[] = "0x80ac58cd";
inline constexpr char kERC721MetadataInterfaceId[] = "0x5b5e139f";

inline constexpr char kBitcoinPrefKey[] = "bitcoin";
inline constexpr char kZCashPrefKey[] = "zcash";
inline constexpr char kEthereumPrefKey[] = "ethereum";
inline constexpr char kFilecoinPrefKey[] = "filecoin";
inline constexpr char kSolanaPrefKey[] = "solana";

inline constexpr char kEthereumBlockTagEarliest[] = "earliest";
inline constexpr char kEthereumBlockTagLatest[] = "latest";

inline constexpr char kBitcoinTestnetRpcEndpoint[] =
    "https://blockstream.info/testnet/api/";

inline constexpr char kMeldRpcEndpoint[] = "https://api-meld.wallet.wootz.com";
inline constexpr char kMeldRpcVersionHeader[] = "Meld-Version";
inline constexpr char kMeldRpcVersion[] = "2023-05-26";

const std::string GetSardineNetworkName(const std::string& chain_id);
const base::flat_map<std::string, std::string>&
GetEthBalanceScannerContractAddresses();
const std::vector<std::string>& GetEthSupportedNftInterfaces();
// Returns the URL for the Ratios service.
const std::string GetAssetRatioBaseURL();
const base::flat_map<std::string, std::string>& GetAnkrBlockchains();
// https://docs.rs/solana-program/1.18.10/src/solana_program/clock.rs.html#129-131
inline constexpr int kSolanaValidBlockHeightThreshold = 150;
}  // namespace wootz_wallet

#endif  // COMPONENTS_WOOTZ_WALLET_BROWSER_WOOTZ_WALLET_CONSTANTS_H_
