/* Copyright (c) 2020 The Wootz Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef WOOTZ_COMPONENTS_WOOTZ_WALLET_BROWSER_WOOTZ_WALLET_CONSTANTS_H_
#define WOOTZ_COMPONENTS_WOOTZ_WALLET_BROWSER_WOOTZ_WALLET_CONSTANTS_H_

#include <string>
#include <vector>

#include "chrome/components/wootz_wallet/common/wootz_wallet_types.h"
#include "components/grit/wootz_components_strings.h"
#include "ui/base/webui/web_ui_util.h"

namespace wootz_wallet {

inline constexpr char kWootzServicesKeyHeader[] = "x-wootz-key";

constexpr uint256_t kDefaultSendEthGasLimit = 21000;
constexpr uint256_t kDefaultERC20TransferGasLimit = 300000;
constexpr uint256_t kDefaultERC721TransferGasLimit = 800000;
constexpr uint256_t kDefaultERC20ApproveGasLimit = 300000;

constexpr int32_t kAutoLockMinutesMin = 1;
constexpr int32_t kAutoLockMinutesMax = 10080;

constexpr int32_t kAssetDiscoveryMinutesPerRequest = 1;

inline constexpr char kWalletBaseDirectory[] = "chromeWallet";
inline constexpr char kImageSourceHost[] = "erc-token-images";
inline constexpr char kRampBaseUrl[] = "https://app.ramp.network";
inline constexpr char kOffRampEnabledFlows[] = "OFFRAMP";
inline constexpr char kOnRampEnabledFlows[] = "ONRAMP";
inline constexpr char kOnRampID[] = "8yxja8782as5essk2myz3bmh4az6gpq4nte9n2gf";
inline constexpr char kOffRampID[] = "y57zqta99ohs7o2paf4ak6vpfb7wf8ubj9krwtwe";
inline constexpr char kSardineStorefrontBaseURL[] = "https://crypto.sardine.ai";
inline constexpr char kSardineClientTokensURL[] =
    "https://api.sardine.ai/v1/auth/client-tokens";
inline constexpr char kTransakURL[] = "https://global.transak.com/";
inline constexpr char kTransakApiKey[] = "985d14f0-4cf5-4a4c-8917-78107620d3b7";
inline constexpr char kCoinbaseURL[] = "https://pay.coinbase.com";
inline constexpr char kCoinbaseAppId[] = "8072ff71-8469-4fef-9404-7c905e2359c9";
inline constexpr char kSimpleHashUrl[] = "https://api.simplehash.com";
inline constexpr char kSimpleHashWootzProxyUrl[] =
    "https://simplehash.wallet.wootz.com";

inline constexpr size_t kSimpleHashMaxBatchSize = 50;

inline constexpr webui::LocalizedString kLocalizedStrings[] = {
    {"chromeWalletWatchOnly", IDS_WOOTZ_WALLET_WATCH_ONLY},
    {"chromeWalletNftSymbolFieldExplanation",
     IDS_WOOTZ_WALLET_NFT_SYMBOL_FIELD_EXPLANATION},
    {"chromeWalletNftNameFieldExplanation",
     IDS_WOOTZ_WALLET_NFT_NAME_FIELD_EXPLANATION},
    {"chromeWalletExempliGratia", IDS_WOOTZ_WALLET_EXEMPLI_GRATIA},
    {"chromeWalletUnownedNftAlert", IDS_WOOTZ_WALLET_UNOWNED_NFT_ALERT},
    {"chromeWalletWatchThisNft", IDS_WOOTZ_WALLET_WATCH_THIS_NFT},
    {"chromeWalletFetchNftMetadataError",
     IDS_WOOTZ_WALLET_FETCH_NFT_METADATA_ERROR},
    {"chromeWalletWhatIsAnNftTokenId", IDS_WOOTZ_WALLET_WHAT_IS_AN_NFT_TOKEN_ID},
    {"chromeWalletWhatIsAnNftContractAddress",
     IDS_WOOTZ_WALLET_WHAT_IS_AN_NFT_CONTRACT_ADDRESS},
    {"chromeWalletGroupByCollection", IDS_WOOTZ_WALLET_GROUP_BY_COLLECTION},
    {"chromeWalletAddNftModalDescription",
     IDS_WOOTZ_WALLET_ADD_NFT_MODAL_DESCRIPTION},
    {"chromeWalletHideNotOwnedNfTs", IDS_WOOTZ_WALLET_HIDE_NOT_OWNED_NF_TS},
    {"chromeWalletNoRoutesFound", IDS_WOOTZ_WALLET_NO_ROUTES_FOUND},
    {"chromeWalletPrivateKeyImportType",
     IDS_WOOTZ_WALLET_PRIVATE_KEY_IMPORT_TYPE},
    {"chromeWalletEnterPasswordIfApplicable",
     IDS_WOOTZ_WALLET_ENTER_PASSWORD_IF_APPLICABLE},
    {"chromeWalletFoundIssues", IDS_WOOTZ_WALLET_FOUND_ISSUES},
    {"chromeWalletContract", IDS_WOOTZ_WALLET_CONTRACT},
    {"chromeWalletFoundRisks", IDS_WOOTZ_WALLET_FOUND_RISKS},
    {"chromeWalletProceedButton", IDS_WOOTZ_WALLET_PROCEED_BUTTON},
    {"chromeWalletUntrustedRequestWarning",
     IDS_WOOTZ_WALLET_UNTRUSTED_REQUEST_WARNING},
    {"chromeWalletRiskOfLossAction", IDS_WOOTZ_WALLET_RISK_OF_LOSS_ACTION},
    {"chromeWalletTestNetworkAccount", IDS_WOOTZ_WALLET_TEST_NETWORK_ACCOUNT},
    {"chromeWalletPopular", IDS_WOOTZ_WALLET_POPULAR},
    {"chromeWalletFeatured", IDS_WOOTZ_WALLET_FEATURED},
    {"chromeWalletShowTestnets", IDS_WOOTZ_WALLET_SHOW_TESTNETS},
    {"chromeWalletChooseChainsToUse", IDS_WOOTZ_WALLET_CHOOSE_CHAINS_TO_USE},
    {"chromeWalletSupportedNetworks", IDS_WOOTZ_WALLET_SUPPORTED_NETWORKS},
    {"chromeWalletAddNetworksAnytimeInSettings",
     IDS_WOOTZ_WALLET_ADD_NETWORKS_ANYTIME_IN_SETTINGS},
    {"chromeWalletContinueWithXItems", IDS_WOOTZ_WALLET_CONTINUE_WITH_X_ITEMS},
    {"chromeWalletTopNavExplore", IDS_WOOTZ_WALLET_TOP_NAV_EXPLORE},
    {"chromeWalletWeb3", IDS_WOOTZ_WALLET_WEB_3},
    {"chromeWalletSpenderAddress", IDS_WOOTZ_WALLET_SPENDER_ADDRESS},
    {"chromeWalletTokenIsVerifiedByLists",
     IDS_WOOTZ_WALLET_TOKEN_IS_VERIFIED_BY_LISTS},
    {"chromeWalletTokenIsVerified", IDS_WOOTZ_WALLET_TOKEN_IS_VERIFIED},
    {"chromeWalletTokenIsUnverified", IDS_WOOTZ_WALLET_TOKEN_IS_UNVERIFIED},
    {"chromeWalletUnlimitedAssetAmount",
     IDS_WOOTZ_WALLET_UNLIMITED_ASSET_AMOUNT},
    {"chromeWalletFrom", IDS_WOOTZ_WALLET_FROM},
    {"chromeWalletReceive", IDS_WOOTZ_WALLET_RECEIVE},
    {"chromeWalletChangeAnytimeInSettings",
     IDS_WOOTZ_WALLET_CHANGE_ANYTIME_IN_SETTINGS},
    {"chromeWalletAvailable", IDS_WOOTZ_WALLET_AVAILABLE},
    {"chromeWalletAvailableBalanceDescription",
     IDS_WOOTZ_WALLET_AVAILABLE_BALANCE_DESCRIPTION},
    {"chromeWalletPending", IDS_WOOTZ_WALLET_PENDING},
    {"chromeWalletPendingBalanceDescription",
     IDS_WOOTZ_WALLET_PENDING_BALANCE_DESCRIPTION},
    {"chromeWalletTotalBalanceDescription",
     IDS_WOOTZ_WALLET_TOTAL_BALANCE_DESCRIPTION},
    {"chromeWalletUnavailableBalances", IDS_WOOTZ_WALLET_UNAVAILABLE_BALANCES},
    {"chromeWalletTransactionSimulationTerms",
     IDS_WOOTZ_WALLET_TRANSACTION_SIMULATION_TERMS},
    {"chromeWalletButtonEnable", IDS_WOOTZ_WALLET_BUTTON_ENABLE},
    {"chromeWalletButtonNoThanks", IDS_WOOTZ_WALLET_BUTTON_NO_THANKS},
    {"chromeWalletTransactionSimulationDetectPhishing",
     IDS_WOOTZ_WALLET_TRANSACTION_SIMULATION_DETECT_PHISHING},
    {"chromeWalletTransactionSimulationDetectMalicious",
     IDS_WOOTZ_WALLET_TRANSACTION_SIMULATION_DETECT_MALICIOUS},
    {"chromeWalletTransactionSimulationSeeEstimates",
     IDS_WOOTZ_WALLET_TRANSACTION_SIMULATION_SEE_ESTIMATES},
    {"chromeWalletEnableEnhancedTransactionDetailsTitle",
     IDS_WOOTZ_WALLET_ENABLE_ENHANCED_TRANSACTION_DETAILS_TITLE},
    {"chromeWalletNetworkFees", IDS_WOOTZ_WALLET_NETWORK_FEES},
    {"chromeWalletSolanaSysvarRentProgram",
     IDS_WOOTZ_WALLET_SOLANA_SYSVAR_RENT_PROGRAM},
    {"chromeWalletSolanaMetaDataProgram",
     IDS_WOOTZ_WALLET_SOLANA_META_DATA_PROGRAM},
    {"chromeWalletSolanaAssociatedTokenProgram",
     IDS_WOOTZ_WALLET_SOLANA_ASSOCIATED_TOKEN_PROGRAM},
    {"chromeWalletSolanaTokenProgram", IDS_WOOTZ_WALLET_SOLANA_TOKEN_PROGRAM},
    {"chromeWalletTransactionHasFeeEstimatesError",
     IDS_WOOTZ_WALLET_TRANSACTION_HAS_FEE_ESTIMATES_ERROR},
    {"chromeWalletGasFeeLimitLowerThanBaseFeeWarning",
     IDS_WOOTZ_WALLET_GAS_FEE_LIMIT_LOWER_THAN_BASE_FEE_WARNING},
    {"chromeWalletTokenMintAddress", IDS_WOOTZ_WALLET_TOKEN_MINT_ADDRESS},
    {"chromeWalletActivity", IDS_WOOTZ_WALLET_ACTIVITY},
    {"chromeWalletTokenDecimalsIsRequiredError",
     IDS_WOOTZ_WALLET_TOKEN_DECIMALS_IS_REQUIRED_ERROR},
    {"chromeWalletTokenSymbolIsRequiredError",
     IDS_WOOTZ_WALLET_TOKEN_SYMBOL_IS_REQUIRED_ERROR},
    {"chromeWalletInvalidTokenContractAddressError",
     IDS_WOOTZ_WALLET_INVALID_TOKEN_CONTRACT_ADDRESS_ERROR},
    {"chromeWalletTokenNameIsRequiredError",
     IDS_WOOTZ_WALLET_TOKEN_NAME_IS_REQUIRED_ERROR},
    {"chromeWalletNetworkIsRequiredError",
     IDS_WOOTZ_WALLET_NETWORK_IS_REQUIRED_ERROR},
    {"chromeWalletEnterYourPasswordToStartBackup",
     IDS_WOOTZ_WALLET_ENTER_YOUR_PASSWORD_TO_START_BACKUP},
    {"chromeWalletEnterAPasswordToContinue",
     IDS_WOOTZ_WALLET_ENTER_A_PASSWORD_TO_CONTINUE},
    {"chromeWalletNoTransactionsYetDescription",
     IDS_WOOTZ_WALLET_NO_TRANSACTIONS_YET_DESCRIPTION},
    {"chromeWalletNoTransactionsYet", IDS_WOOTZ_WALLET_NO_TRANSACTIONS_YET},
    {"chromeWalletInvalidMnemonicError", IDS_WALLET_INVALID_MNEMONIC_ERROR},
    {"chromeWalletImportWalletTypeTitle",
     IDS_WOOTZ_WALLET_IMPORT_WALLET_TYPE_TITLE},
    {"chromeWalletImportWalletTypeHotWalletTitle",
     IDS_WOOTZ_WALLET_IMPORT_WALLET_TYPE_HOT_WALLET_TITLE},
    {"chromeWalletImportWalletTypeHotWalletDescription",
     IDS_WOOTZ_WALLET_IMPORT_WALLET_TYPE_HOT_WALLET_DESCRIPTION},
    {"chromeWalletImportWalletTypeHardwareWalletTitle",
     IDS_WOOTZ_WALLET_IMPORT_WALLET_TYPE_HARDWARE_WALLET_TITLE},
    {"chromeWalletImportWalletTypeHardwareWalletDescription",
     IDS_WOOTZ_WALLET_IMPORT_WALLET_TYPE_HARDWARE_WALLET_DESCRIPTION},
    {"chromeWalletRecoveryPhraseLengthError",
     IDS_WOOTZ_WALLET_RECOVERY_PHRASE_LENGTH_ERROR},
    {"chromeWalletOrdinalTwentyFourth", IDS_WOOTZ_WALLET_ORDINAL_TWENTY_FOURTH},
    {"chromeWalletOrdinalTwentyThird", IDS_WOOTZ_WALLET_ORDINAL_TWENTY_THIRD},
    {"chromeWalletOrdinalTwentySecond", IDS_WOOTZ_WALLET_ORDINAL_TWENTY_SECOND},
    {"chromeWalletOrdinalTwentyFirst", IDS_WOOTZ_WALLET_ORDINAL_TWENTY_FIRST},
    {"chromeWalletOrdinalTwentieth", IDS_WOOTZ_WALLET_ORDINAL_TWENTIETH},
    {"chromeWalletOrdinalNineteenth", IDS_WOOTZ_WALLET_ORDINAL_NINETEENTH},
    {"chromeWalletOrdinalEighteenth", IDS_WOOTZ_WALLET_ORDINAL_EIGHTEENTH},
    {"chromeWalletOrdinalSeventeenth", IDS_WOOTZ_WALLET_ORDINAL_SEVENTEENTH},
    {"chromeWalletOrdinalSixteenth", IDS_WOOTZ_WALLET_ORDINAL_SIXTEENTH},
    {"chromeWalletOrdinalFifteenth", IDS_WOOTZ_WALLET_ORDINAL_FIFTEENTH},
    {"chromeWalletOrdinalFourteenth", IDS_WOOTZ_WALLET_ORDINAL_FOURTEENTH},
    {"chromeWalletOrdinalThirteenth", IDS_WOOTZ_WALLET_ORDINAL_THIRTEENTH},
    {"chromeWalletOrdinalTwelfth", IDS_WOOTZ_WALLET_ORDINAL_TWELFTH},
    {"chromeWalletOrdinalSuffixOther", IDS_WOOTZ_WALLET_ORDINAL_SUFFIX_OTHER},
    {"chromeWalletOrdinalSuffixFew", IDS_WOOTZ_WALLET_ORDINAL_SUFFIX_FEW},
    {"chromeWalletOrdinalSuffixTwo", IDS_WOOTZ_WALLET_ORDINAL_SUFFIX_TWO},
    {"chromeWalletOrdinalSuffixOne", IDS_WOOTZ_WALLET_ORDINAL_SUFFIX_ONE},
    {"chromeWalletOrdinalEleventh", IDS_WOOTZ_WALLET_ORDINAL_ELEVENTH},
    {"chromeWalletOrdinalTenth", IDS_WOOTZ_WALLET_ORDINAL_TENTH},
    {"chromeWalletOrdinalNinth", IDS_WOOTZ_WALLET_ORDINAL_NINTH},
    {"chromeWalletOrdinalEighth", IDS_WOOTZ_WALLET_ORDINAL_EIGHTH},
    {"chromeWalletOrdinalSeventh", IDS_WOOTZ_WALLET_ORDINAL_SEVENTH},
    {"chromeWalletOrdinalSixth", IDS_WOOTZ_WALLET_ORDINAL_SIXTH},
    {"chromeWalletOrdinalFifth", IDS_WOOTZ_WALLET_ORDINAL_FIFTH},
    {"chromeWalletOrdinalFourth", IDS_WOOTZ_WALLET_ORDINAL_FOURTH},
    {"chromeWalletOrdinalSecond", IDS_WOOTZ_WALLET_ORDINAL_SECOND},
    {"chromeWalletRemoveAccountModalTitle",
     IDS_WOOTZ_WALLET_REMOVE_ACCOUNT_MODAL_TITLE},
    {"chromeWalletViewDecodedMessage", IDS_WOOTZ_WALLET_VIEW_DECODED_MESSAGE},
    {"chromeWalletViewEncodedMessage", IDS_WOOTZ_WALLET_VIEW_ENCODED_MESSAGE},
    {"chromeWalletNonAsciiCharactersInMessageWarning",
     IDS_WOOTZ_WALLET_NON_ASCII_CHARACTERS_IN_MESSAGE_WARNING},
    {"chromeWalletEnterYourPassword", IDS_WOOTZ_WALLET_ENTER_YOUR_PASSWORD},
    {"chromeWalletEnterYourWootzWalletPassword",
     IDS_WOOTZ_WALLET_ENTER_YOUR_WOOTZ_WALLET_PASSWORD},
    {"chromeWalletClickToSwitch", IDS_WOOTZ_WALLET_CLICK_TO_SWITCH},
    {"chromeWalletMultiChain", IDS_WOOTZ_WALLET_MULTI_CHAIN},
    {"chromeWalletPerksBrowserNative", IDS_WOOTZ_WALLET_PERKS_BROWSER_NATIVE},
    {"chromeWalletPerksTokens", IDS_WOOTZ_WALLET_PERKS_TOKENS},
    {"chromeWallet", IDS_WOOTZ_WALLET},
    {"chromeWalletSearchText", IDS_WOOTZ_WALLET_SEARCH_TEXT},
    {"chromeWalletSideNavCrypto", IDS_WOOTZ_WALLET_SIDE_NAV_CRYPTO},
    {"chromeWalletSideNavRewards", IDS_WOOTZ_WALLET_SIDE_NAV_REWARDS},
    {"chromeWalletSideNavCards", IDS_WOOTZ_WALLET_SIDE_NAV_CARDS},
    {"chromeWalletTopNavPortfolio", IDS_WOOTZ_WALLET_TOP_NAV_PORTFOLIO},
    {"chromeWalletTopTabPrices", IDS_WOOTZ_WALLET_TOP_TAB_PRICES},
    {"chromeWalletTopNavNFTS", IDS_WOOTZ_WALLET_TOP_NAV_N_F_T_S},
    {"chromeWalletTopNavAccounts", IDS_WOOTZ_WALLET_TOP_NAV_ACCOUNTS},
    {"chromeWalletTopNavMarket", IDS_WOOTZ_WALLET_TOP_NAV_MARKET},
    {"chromeWalletChartOneHour", IDS_WOOTZ_WALLET_CHART_ONE_HOUR},
    {"chromeWalletChartOneDay", IDS_WOOTZ_WALLET_CHART_ONE_DAY},
    {"chromeWalletChartOneWeek", IDS_WOOTZ_WALLET_CHART_ONE_WEEK},
    {"chromeWalletChartOneMonth", IDS_WOOTZ_WALLET_CHART_ONE_MONTH},
    {"chromeWalletChartThreeMonths", IDS_WOOTZ_WALLET_CHART_THREE_MONTHS},
    {"chromeWalletChartOneYear", IDS_WOOTZ_WALLET_CHART_ONE_YEAR},
    {"chromeWalletChartAllTime", IDS_WOOTZ_WALLET_CHART_ALL_TIME},
    {"chromeWalletChartOneHourAbbr", IDS_WOOTZ_WALLET_CHART_ONE_HOUR_ABBR},
    {"chromeWalletChartOneDayAbbr", IDS_WOOTZ_WALLET_CHART_ONE_DAY_ABBR},
    {"chromeWalletChartOneWeekAbbr", IDS_WOOTZ_WALLET_CHART_ONE_WEEK_ABBR},
    {"chromeWalletChartOneMonthAbbr", IDS_WOOTZ_WALLET_CHART_ONE_MONTH_ABBR},
    {"chromeWalletChartThreeMonthsAbbr",
     IDS_WOOTZ_WALLET_CHART_THREE_MONTHS_ABBR},
    {"chromeWalletChartOneYearAbbr", IDS_WOOTZ_WALLET_CHART_ONE_YEAR_ABBR},
    {"chromeWalletChartAllTimeAbbr", IDS_WOOTZ_WALLET_CHART_ALL_TIME_ABBR},
    {"chromeWalletAddCoin", IDS_WOOTZ_WALLET_ADD_COIN},
    {"chromeWalletBalance", IDS_WOOTZ_WALLET_BALANCE},
    {"chromeWalletPortfolioAssetNetworkDescription",
     IDS_WOOTZ_WALLET_PORTFOLIO_ASSET_NETWORK_DESCRIPTION},
    {"chromeWalletAccounts", IDS_WOOTZ_WALLET_ACCOUNTS},
    {"chromeWalletSubviewAccount", IDS_WOOTZ_WALLET_SUBVIEW_ACCOUNT},
    {"chromeWalletOwner", IDS_WOOTZ_WALLET_OWNER},
    {"chromeWalletTransactions", IDS_WOOTZ_WALLET_TRANSACTIONS},
    {"chromeWalletPrice", IDS_WOOTZ_WALLET_PRICE},
    {"chromeWalletBack", IDS_WOOTZ_WALLET_BACK},
    {"chromeWalletAddAccount", IDS_WOOTZ_WALLET_ADD_ACCOUNT},
    {"chromeWalletPoweredByCoinGecko", IDS_WOOTZ_WALLET_POWERED_BY_COIN_GECKO},
    {"chromeWalletBuy", IDS_WOOTZ_WALLET_BUY},
    {"chromeWalletSend", IDS_WOOTZ_WALLET_SEND},
    {"chromeWalletSwap", IDS_WOOTZ_WALLET_SWAP},
    {"chromeWalletBridge", IDS_WOOTZ_WALLET_BRIDGE},
    {"chromeWalletReset", IDS_WOOTZ_WALLET_RESET},
    {"chromeWalletSell", IDS_WOOTZ_WALLET_SELL},
    {"chromeWalletNotEnoughBalance", IDS_WOOTZ_WALLET_NOT_ENOUGH_BALANCE},
    {"chromeWalletChooseAssetToSend", IDS_WOOTZ_WALLET_CHOOSE_ASSET_TO_SEND},
    {"chromeWalletChooseAssetToSwap", IDS_WOOTZ_WALLET_CHOOSE_ASSET_TO_SWAP},
    {"chromeWalletEnterRecipientAddress",
     IDS_WOOTZ_WALLET_ENTER_RECIPIENT_ADDRESS},
    {"chromeWalletNotEnoughFunds", IDS_WOOTZ_WALLET_NOT_ENOUGH_FUNDS},
    {"chromeWalletSendHalf", IDS_WOOTZ_WALLET_SEND_HALF},
    {"chromeWalletSendMax", IDS_WOOTZ_WALLET_SEND_MAX},
    {"chromeWalletReviewOrder", IDS_WOOTZ_WALLET_REVIEW_ORDER},
    {"chromeWalletReviewSend", IDS_WOOTZ_WALLET_REVIEW_SEND},
    {"chromeWalletNoAvailableTokens", IDS_WOOTZ_WALLET_NO_AVAILIBLE_TOKENS},
    {"chromeWalletSearchTokens", IDS_WOOTZ_WALLET_SEARCH_TOKENS},
    {"chromeWalletSearchNFTs", IDS_WOOTZ_WALLET_SEARCH_NFTS},
    {"chromeWalletChooseAsset", IDS_WOOTZ_WALLET_CHOOSE_ASSET},
    {"chromeWalletOrdinalsWarningMessage",
     IDS_WOOTZ_WALLET_ORDINALS_WARNING_MESSAGE},
    {"chromeWalletUserUnderstandsLabel",
     IDS_WOOTZ_WALLET_USER_UNDERSTANDS_LABEL},
    {"chromeWalletChooseRecipient", IDS_WOOTZ_WALLET_CHOOSE_RECIPIENT},
    {"chromeWalletMyAddresses", IDS_WOOTZ_WALLET_MY_ADDRESSES},
    {"chromeWalletAddressOrDomainPlaceholder",
     IDS_WOOTZ_WALLET_ADDRESS_OR_DOMAIN_PLACEHOLDER},
    {"chromeWalletSendTo", IDS_WOOTZ_WALLET_SEND_TO},
    {"chromeWalletInvalidDomainExtension",
     IDS_WOOTZ_WALLET_INVALID_DOMAIN_EXTENSION},
    {"chromeWalletChooseAccount", IDS_WOOTZ_WALLET_CHOOSE_ACCOUNT},
    {"chromeWalletMarketPrice", IDS_WOOTZ_WALLET_MARKET_PRICE},
    {"chromeWalletOwned", IDS_WOOTZ_WALLET_OWNED},
    {"chromeWalletNotOwned", IDS_WOOTZ_WALLET_NOT_OWNED},
    {"chromeWalletAmount24H", IDS_WOOTZ_WALLET_AMOUNT_24H},
    {"chromeWalletChooseAssetToBridge", IDS_WOOTZ_WALLET_CHOOSE_ASSET_TO_BRIDGE},
    {"chromeWalletReviewSwap", IDS_WOOTZ_WALLET_REVIEW_SWAP},
    {"chromeWalletChooseQuoteProvider", IDS_WOOTZ_WALLET_CHOOSE_QUOTE_PROVIDER},
    {"chromeWalletQuoteProviderInfo", IDS_WOOTZ_WALLET_QUOTE_PROVIDER_INFO},
    {"chromeWalletNotAvailable", IDS_WOOTZ_WALLET_REVIEW_NOT_AVAILABLE},
    {"chromeWalletUpdate", IDS_WOOTZ_WALLET_REVIEW_UPDATE},
    {"chromeWalletProviderNotSupported",
     IDS_WOOTZ_WALLET_PROVIDER_NOT_SUPPORTED},
    {"chromeWalletChangeProvider", IDS_WOOTZ_WALLET_CHANGE_PROVIDER},
    {"chromeWalletRoute", IDS_WOOTZ_WALLET_ROUTE},
    {"chromeWalletMaxSlippage", IDS_WOOTZ_WALLET_MAX_SLIPPAGE},
    {"chromeWalletMaxSlippageDescription",
     IDS_WOOTZ_WALLET_SLIPPAGE_DESCRIPTION},
    {"chromeWalletPriceImpactDescription",
     IDS_WOOTZ_WALLET_PRICE_IMPACT_DESCRIPTION},
    {"chromeWalletSuggestedValues", IDS_WOOTZ_WALLET_SUGGESTED_VALUES},
    {"chromeWalletMainstreamAssetPairs",
     IDS_WOOTZ_WALLET_MAINSTREAM_ASSET_PAIRS},
    {"chromeWalletStablecoinPairs", IDS_WOOTZ_WALLET_STABLECOIN_PAIRS},
    {"chromeWalletOthers", IDS_WOOTZ_WALLET_OTHERS},
    {"chromeWalletSuggested", IDS_WOOTZ_WALLET_SUGGESTED},
    {"chromeWalletCustom", IDS_WOOTZ_WALLET_CUSTOM},
    {"chromeWalletEstTime", IDS_WOOTZ_WALLET_EST_TIME},
    {"chromeWalletExchangeRate", IDS_WOOTZ_WALLET_EXCHANGE_RATE},
    {"chromeWalletExchangeFor", IDS_WOOTZ_WALLET_EXCHANGE_FOR},
    {"chromeWalletRecipient", IDS_WOOTZ_WALLET_RECIPIENT},
    {"chromeWalletReviewBridge", IDS_WOOTZ_WALLET_REVIEW_BRIDGE},
    {"chromeWalletSlippageToleranceWarning",
     IDS_WOOTZ_WALLET_SLIPPAGE_TOLERANCE_WARNING},
    {"chromeWalletExpiresInTitle", IDS_WOOTZ_WALLET_EXPIRES_IN_TITLE},
    {"chromeWalletSendPlaceholder", IDS_WOOTZ_WALLET_SEND_PLACEHOLDER},
    {"chromeWalletSendNoURLPlaceholder",
     IDS_WOOTZ_WALLET_SEND_NO_URL_PLACEHOLDER},
    {"chromeWalletSwapDisclaimer", IDS_WOOTZ_WALLET_SWAP_DISCLAIMER},
    {"chromeWalletSwapDisclaimerDescription",
     IDS_WOOTZ_WALLET_SWAP_DISCLAIMER_DESCRIPTION},
    {"chromeWalletJupiterSwapDisclaimerDescription",
     IDS_WOOTZ_WALLET_JUPITER_SWAP_DISCLAIMER_DESCRIPTION},
    {"chromeWalletSwapFeesNotice", IDS_WOOTZ_WALLET_SWAP_FEES_NOTICE},
    {"chromeWalletDecimalPlacesError", IDS_WOOTZ_WALLET_DECIMAL_PLACES_ERROR},
    {"chromeWalletCreateAccountDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_DESCRIPTION},
    {"chromeWalletCreateAccountYes", IDS_WOOTZ_WALLET_CREATE_ACCOUNT_YES},
    {"chromeWalletCreateAccountNo", IDS_WOOTZ_WALLET_CREATE_ACCOUNT_NO},
    {"chromeWalletButtonContinue", IDS_WOOTZ_WALLET_BUTTON_CONTINUE},
    {"chromeWalletButtonNext", IDS_WOOTZ_WALLET_BUTTON_NEXT},
    {"chromeWalletButtonVerifyPhrase", IDS_WOOTZ_WALLET_BUTTON_GOT_IT},
    {"chromeWalletButtonCopy", IDS_WOOTZ_WALLET_BUTTON_COPY},
    {"chromeWalletButtonCopied", IDS_WOOTZ_WALLET_BUTTON_COPIED},
    {"chromeWalletButtonVerify", IDS_WOOTZ_WALLET_BUTTON_VERIFY},
    {"chromeWalletButtonClose", IDS_WOOTZ_WALLET_BUTTON_CLOSE},
    {"chromeWalletButtonMore", IDS_WOOTZ_WALLET_BUTTON_MORE},
    {"chromeWalletButtonDone", IDS_WOOTZ_WALLET_BUTTON_DONE},
    {"chromeWalletWelcomeTitle", IDS_WOOTZ_WALLET_WELCOME_TITLE},
    {"chromeWalletWelcomeRestoreButton",
     IDS_WOOTZ_WALLET_WELCOME_RESTORE_BUTTON},
    {"chromeWalletWelcomeDescription", IDS_WOOTZ_WALLET_WELCOME_DESCRIPTION},
    {"chromeWalletWelcomeNewWalletTitle",
     IDS_WOOTZ_WALLET_WELCOME_NEW_WALLET_TITLE},
    {"chromeWalletWelcomeNewWalletDescription",
     IDS_WOOTZ_WALLET_WELCOME_NEW_WALLET_DESCRIPTION},
    {"chromeWalletWelcomeImportWalletTitle",
     IDS_WOOTZ_WALLET_WELCOME_IMPORT_WALLET_TITLE},
    {"chromeWalletWelcomeImportWalletDescription",
     IDS_WOOTZ_WALLET_WELCOME_IMPORT_WALLET_DESCRIPTION},
    {"chromeWalletWelcomeWatchOnlyTitle",
     IDS_WOOTZ_WALLET_WELCOME_WATCH_ONLY_TITLE},
    {"chromeWalletCopyright", IDS_WOOTZ_WALLET_WELCOME_COPYRIGHT},
    {"chromeWalletWelcomeDividerText", IDS_WOOTZ_WALLET_WELCOME_DIVIDER_TEXT},
    {"chromeWalletBackupIntroTitle", IDS_WOOTZ_WALLET_BACKUP_INTRO_TITLE},
    {"chromeWalletBackupIntroTerms", IDS_WOOTZ_WALLET_BACKUP_INTRO_TERMS},
    {"chromeWalletButtonSkip", IDS_WOOTZ_WALLET_BUTTON_SKIP},
    {"chromeWalletButtonCancel", IDS_WOOTZ_WALLET_BUTTON_CANCEL},
    {"chromeWalletButtonSaveChanges", IDS_WOOTZ_WALLET_BUTTON_SAVE_CHANGES},
    {"chromeWalletRecoveryTitle", IDS_WOOTZ_WALLET_RECOVERY_TITLE},
    {"chromeWalletRecoveryDescription", IDS_WOOTZ_WALLET_RECOVERY_DESCRIPTION},
    {"chromeWalletRecoveryWarning1", IDS_WOOTZ_WALLET_RECOVERY_WARNING1},
    {"chromeWalletRecoveryWarning2", IDS_WOOTZ_WALLET_RECOVERY_WARNING2},
    {"chromeWalletRecoveryWarning3", IDS_WOOTZ_WALLET_RECOVERY_WARNING3},
    {"chromeWalletRecoveryTerms", IDS_WOOTZ_WALLET_RECOVERY_TERMS},
    {"chromeWalletVerifyRecoveryTitle", IDS_WOOTZ_WALLET_VERIFY_RECOVERY_TITLE},
    {"chromeWalletVerifyRecoveryDescription",
     IDS_WOOTZ_WALLET_VERIFY_RECOVERY_DESCRIPTION},
    {"chromeWalletVerifyError", IDS_WOOTZ_WALLET_VERIFY_ERROR},
    {"chromeWalletVerifyRecoveryPhraseTitle",
     IDS_WOOTZ_WALLET_VERIFY_RECOVERY_PHRASE_TITLE},
    {"chromeWalletVerifyRecoveryPhraseInstructions",
     IDS_WOOTZ_WALLET_VERIFY_RECOVERY_PHRASE_INSTRUCTIONS},
    {"chromeWalletVerifyPhraseError", IDS_WOOTZ_WALLET_VERIFY_PHRASE_ERROR},
    {"chromeWalletCreatePasswordTitle", IDS_WOOTZ_WALLET_CREATE_PASSWORD_TITLE},
    {"chromeWalletCreatePasswordDescription",
     IDS_WOOTZ_WALLET_CREATE_PASSWORD_DESCRIPTION},
    {"chromeWalletCreatePasswordInput", IDS_WOOTZ_WALLET_CREATE_PASSWORD_INPUT},
    {"chromeWalletConfirmPasswordInput",
     IDS_WOOTZ_WALLET_CONFIRM_PASSWORD_INPUT},
    {"chromeWalletCreatePasswordError", IDS_WOOTZ_WALLET_CREATE_PASSWORD_ERROR},
    {"chromeWalletConfirmPasswordError",
     IDS_WOOTZ_WALLET_CONFIRM_PASSWORD_ERROR},
    {"chromeWalletLockScreenTitle", IDS_WOOTZ_WALLET_LOCK_SCREEN_TITLE},
    {"chromeWalletLockScreenButton", IDS_WOOTZ_WALLET_LOCK_SCREEN_BUTTON},
    {"chromeWalletLockScreenError", IDS_WOOTZ_WALLET_LOCK_SCREEN_ERROR},
    {"chromeWalletUnlockWallet", IDS_WOOTZ_WALLET_UNLOCK_WALLET},
    {"chromeWalletWalletPopupSettings", IDS_WOOTZ_WALLET_WALLET_POPUP_SETTINGS},
    {"chromeWalletWalletPopupLock", IDS_WOOTZ_WALLET_WALLET_POPUP_LOCK},
    {"chromeWalletWalletPopupBackup", IDS_WOOTZ_WALLET_WALLET_POPUP_BACKUP},
    {"chromeWalletWalletPopupConnectedSites",
     IDS_WOOTZ_WALLET_WALLET_POPUP_CONNECTED_SITES},
    {"chromeWalletWalletPopupHideBalances",
     IDS_WOOTZ_WALLET_WALLET_POPUP_HIDE_BALANCES},
    {"chromeWalletWalletPopupShowGraph",
     IDS_WOOTZ_WALLET_WALLET_POPUP_SHOW_GRAPH},
    {"chromeWalletWalletNFTsTab", IDS_WOOTZ_WALLET_WALLET_NFTS_TAB},
    {"chromeWalletBackupWarningText", IDS_WOOTZ_WALLET_BACKUP_WARNING_TEXT},
    {"chromeWalletBackupButton", IDS_WOOTZ_WALLET_BACKUP_BUTTON},
    {"chromeWalletDismissButton", IDS_WOOTZ_WALLET_DISMISS_BUTTON},
    {"chromeWalletDefaultWalletBanner", IDS_WOOTZ_WALLET_DEFAULT_WALLET_BANNER},
    {"chromeWalletRestoreTite", IDS_WOOTZ_WALLET_RESTORE_TITE},
    {"chromeWalletRestoreDescription", IDS_WOOTZ_WALLET_RESTORE_DESCRIPTION},
    {"chromeWalletRestoreError", IDS_WOOTZ_WALLET_RESTORE_ERROR},
    {"chromeWalletRestorePlaceholder", IDS_WOOTZ_WALLET_RESTORE_PLACEHOLDER},
    {"chromeWalletRestoreShowPhrase", IDS_WOOTZ_WALLET_RESTORE_SHOW_PHRASE},
    {"chromeWalletRestoreLegacyCheckBox",
     IDS_WOOTZ_WALLET_RESTORE_LEGACY_CHECK_BOX},
    {"chromeWalletRestoreFormText", IDS_WOOTZ_WALLET_RESTORE_FORM_TEXT},
    {"chromeWalletSkipBackupWarning", IDS_WOOTZ_WALLET_SKIP_BACKUP_WARNING},
    {"chromeWalletSkipBackup", IDS_WALLET_SKIP_BACKUP},
    {"chromeWalletGoBack", IDS_WOOTZ_WALLET_GO_BACK},
    {"chromeWalletToolTipCopyToClipboard",
     IDS_WOOTZ_WALLET_TOOL_TIP_COPY_TO_CLIPBOARD},
    {"chromeWalletToolTipCopiedToClipboard",
     IDS_WOOTZ_WALLET_TOOL_TIP_COPIED_TO_CLIPBOARD},
    {"chromeWalletClickToCopy", IDS_WOOTZ_WALLET_CLICK_TO_COPY},
    {"chromeWalletPasteFromClipboard", IDS_WOOTZ_WALLET_PASTE_FROM_CLIPBOARD},
    {"chromeWalletAccountsPrimary", IDS_WOOTZ_WALLET_ACCOUNTS_PRIMARY},
    {"chromeWalletAccountsSecondary", IDS_WOOTZ_WALLET_ACCOUNTS_SECONDARY},
    {"chromeWalletConnectedHardwareWallets",
     IDS_WOOTZ_WALLET_CONNECTED_HARDWARE_WALLETS},
    {"chromeWalletAccountsAssets", IDS_WOOTZ_WALLET_ACCOUNTS_ASSETS},
    {"chromeWalletAccountsEditVisibleAssets",
     IDS_WOOTZ_WALLET_ACCOUNTS_EDIT_VISIBLE_ASSETS},
    {"chromeWalletAccountBalance", IDS_WOOTZ_WALLET_ACCOUNT_BALANCE},
    {"chromeWalletViewAddressOn", IDS_WOOTZ_WALLET_VIEW_ADDRESS_ON},
    {"chromeWalletNetworkExplorer", IDS_WOOTZ_WALLET_NETWORK_EXPLORER},
    {"chromeWalletAddAccountCreate", IDS_WOOTZ_WALLET_ADD_ACCOUNT_CREATE},
    {"chromeWalletCreateAccount", IDS_WOOTZ_WALLET_CREATE_ACCOUNT},
    {"chromeWalletCreateAccountButton", IDS_WOOTZ_WALLET_CREATE_ACCOUNT_BUTTON},
    {"chromeWalletCreateAccountImportAccount",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_IMPORT_ACCOUNT},
    {"chromeWalletCreateAccountTitle", IDS_WOOTZ_WALLET_CREATE_ACCOUNT_TITLE},
    {"chromeWalletCreateAccountEthereumDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_ETHEREUM_DESCRIPTION},
    {"chromeWalletCreateAccountSolanaDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_SOLANA_DESCRIPTION},
    {"chromeWalletCreateAccountFilecoinDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_FILECOIN_DESCRIPTION},
    {"chromeWalletCreateAccountBitcoinDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_BITCOIN_DESCRIPTION},
    {"chromeWalletCreateAccountZCashDescription",
     IDS_WOOTZ_WALLET_CREATE_ACCOUNT_ZCASH_DESCRIPTION},
    {"chromeWalletFilecoinPrivateKeyProtocol",
     IDS_WOOTZ_WALLET_FILECOIN_PRIVATE_KEY_PROTOCOL},
    {"chromeWalletAddAccountImport", IDS_WOOTZ_WALLET_ADD_ACCOUNT_IMPORT},
    {"chromeWalletAddAccountImportHardware",
     IDS_WOOTZ_WALLET_ADD_ACCOUNT_IMPORT_HARDWARE},
    {"chromeWalletAddAccountHardware", IDS_WOOTZ_WALLET_ADD_ACCOUNT_HARDWARE},
    {"chromeWalletAddAccountConnect", IDS_WOOTZ_WALLET_ADD_ACCOUNT_CONNECT},
    {"chromeWalletAddAccountPlaceholder",
     IDS_WOOTZ_WALLET_ADD_ACCOUNT_PLACEHOLDER},
    {"chromeWalletImportAccountDisclaimer",
     IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_DISCLAIMER},
    {"chromeWalletImportAccountPlaceholder",
     IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_PLACEHOLDER},
    {"chromeWalletImportAccountKey", IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_KEY},
    {"chromeWalletImportAccountFile", IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_FILE},
    {"chromeWalletImportAccountUploadButton",
     IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_UPLOAD_BUTTON},
    {"chromeWalletImportAccountUploadPlaceholder",
     IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_UPLOAD_PLACEHOLDER},
    {"chromeWalletImportAccountError", IDS_WOOTZ_WALLET_IMPORT_ACCOUNT_ERROR},
    {"chromeWalletImportAccount", IDS_WOOTZ_WALLET_IMPORT_ACCOUNT},
    {"chromeWalletConnectHardwareTitle",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_TITLE},
    {"chromeWalletConnectHardwareInfo1",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_INFO1},
    {"chromeWalletConnectHardwareInfo2",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_INFO2},
    {"chromeWalletConnectHardwareWrongApplicationUserHint",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_WRONG_APPLICATION_USER_HINT},
    {"chromeWalletConnectHardwareTrezor",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_TREZOR},
    {"chromeWalletConnectHardwareLedger",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_LEDGER},
    {"chromeWalletConnectHardwareAuthorizationNeeded",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_AUTHORIZATION_NEEDED},
    {"chromeWalletConnectingHardwareWallet",
     IDS_WOOTZ_WALLET_CONNECTING_HARDWARE_WALLET},
    {"chromeWalletAddCheckedAccountsHardwareWallet",
     IDS_WOOTZ_WALLET_ADD_CHECKED_ACCOUNTS_HARDWARE_WALLET},
    {"chromeWalletLoadMoreAccountsHardwareWallet",
     IDS_WOOTZ_WALLET_LOAD_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"chromeWalletLoadingMoreAccountsHardwareWallet",
     IDS_WOOTZ_WALLET_LOADING_MORE_ACCOUNTS_HARDWARE_WALLET},
    {"chromeWalletSearchScannedAccounts",
     IDS_WOOTZ_WALLET_SEARCH_SCANNED_ACCOUNTS},
    {"chromeWalletSwitchHDPathTextHardwareWallet",
     IDS_WOOTZ_WALLET_SWITCH_H_D_PATH_TEXT_HARDWARE_WALLET},
    {"chromeWalletHDPath", IDS_WOOTZ_WALLET_H_D_PATH},
    {"chromeWalletLedgerLiveDerivationPath",
     IDS_WOOTZ_WALLET_LEDGER_LIVE_DERIVATION_PATH},
    {"chromeWalletLedgerLegacyDerivationPath",
     IDS_WOOTZ_WALLET_LEDGER_LEGACY_DERIVATION_PATH},
    {"chromeWalletConnectHardwareSearchNothingFound",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_SEARCH_NOTHING_FOUND},
    {"chromeWalletAuthorizeHardwareWallet",
     IDS_WOOTZ_WALLET_AUTHORIZE_HARDWARE_WALLET},
    {"chromeWalletConnectHardwareWallet",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_WALLET},
    {"chromeWallectConnectHardwareDescription",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_WALLET_DESCRIPTION},
    {"chromeWalletImportHardwareWalletDescription",
     IDS_WOOTZ_WALLET_IMPORT_HARDWARE_WALLET_DESCRIPTION},
    {"chromeWalletConnectHardwareWalletSelectBlockchain",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_WALLET_SELECT_BLOCKCHAIN},
    {"chromeWalletConnectHardwareDeviceDescription",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_DEVICE_DESCRIPTION},
    {"chromeWalletUnknownInternalError",
     IDS_WOOTZ_WALLET_UNKNOWN_INTERNAL_ERROR},
    {"chromeWalletAccountSettingsDetails",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_DETAILS},
    {"chromeWalletAccountSettingsWatchlist",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_WATCHLIST},
    {"chromeWalletAccountSettingsPrivateKey",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_PRIVATE_KEY},
    {"chromeWalletAccountSettingsSave", IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_SAVE},
    {"chromeWalletAccountSettingsRemove",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_REMOVE},
    {"chromeWalletWatchlistAddCustomAsset",
     IDS_WOOTZ_WALLET_WATCHLIST_ADD_CUSTOM_ASSET},
    {"chromeWalletWatchListTokenName", IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_NAME},
    {"chromeWalletWatchListTokenAddress",
     IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_ADDRESS},
    {"chromeWalletWatchListTokenSymbol",
     IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_SYMBOL},
    {"chromeWalletWatchListTokenDecimals",
     IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_DECIMALS},
    {"chromeWalletWatchListAdd", IDS_WOOTZ_WALLET_WATCH_LIST_ADD},
    {"chromeWalletWatchListDoneButton", IDS_WOOTZ_WALLET_WATCH_LIST_DONE_BUTTON},
    {"chromeWalletWatchListNoAsset", IDS_WOOTZ_WALLET_WATCH_LIST_NO_ASSET},
    {"chromeWalletWatchListSearchPlaceholder",
     IDS_WOOTZ_WALLET_WATCH_LIST_SEARCH_PLACEHOLDER},
    {"chromeWalletWatchListError", IDS_WOOTZ_WALLET_WATCH_LIST_ERROR},
    {"chromeWalletCustomTokenExistsError",
     IDS_WOOTZ_WALLET_CUSTOM_TOKEN_EXISTS_ERROR},
    {"chromeWalletWatchListTokenId", IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_ID},
    {"chromeWalletWatchListTokenIdError",
     IDS_WOOTZ_WALLET_WATCH_LIST_TOKEN_ID_ERROR},
    {"chromeWalletWatchListAdvanced", IDS_WOOTZ_WALLET_WATCH_LIST_ADVANCED},
    {"chromeWalletWatchListCoingeckoId",
     IDS_WOOTZ_WALLET_WATCH_LIST_COINGECKO_ID},
    {"chromeWalletIconURL", IDS_WOOTZ_WALLET_ICON_URL},
    {"chromeWalletAddAsset", IDS_WOOTZ_WALLET_ADD_ASSET},
    {"chromeWalletAccountsExport", IDS_WOOTZ_WALLET_ACCOUNTS_EXPORT},
    {"chromeWalletAccountsDeposit", IDS_WOOTZ_WALLET_ACCOUNTS_DEPOSIT},
    {"chromeWalletAccountsRemove", IDS_WOOTZ_WALLET_ACCOUNTS_REMOVE},
    {"chromeWalletAccountSettings", IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS},
    {"chromeWalletNoAvailableAssets", IDS_WOOTZ_WALLET_NO_AVAILABLE_ASSETS},
    {"chromeWalletNoAvailableAssetsDescription",
     IDS_WOOTZ_WALLET_NO_AVAILABLE_ASSETS_DESCRIPTION},
    {"chromeWalletAccountSettingsDisclaimer",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_DISCLAIMER},
    {"chromeWalletFilExportPrivateKeyFormatDescription",
     IDS_WOOTZ_WALLET_FIL_EXPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"chromeWalletFilImportPrivateKeyFormatDescription",
     IDS_WOOTZ_WALLET_FIL_IMPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"chromeWalletBtcImportPrivateKeyFormatDescription",
     IDS_WOOTZ_WALLET_BTC_IMPORT_PRIVATE_KEY_FORMAT_DESCRIPTION},
    {"chromeWalletAccountSettingsShowKey",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_SHOW_KEY},
    {"chromeWalletAccountSettingsHideKey",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_HIDE_KEY},
    {"chromeWalletAccountSettingsUpdateError",
     IDS_WOOTZ_WALLET_ACCOUNT_SETTINGS_UPDATE_ERROR},
    {"chromeWalletPreset25", IDS_WOOTZ_WALLET_PRESET25},
    {"chromeWalletPreset50", IDS_WOOTZ_WALLET_PRESET50},
    {"chromeWalletPreset75", IDS_WOOTZ_WALLET_PRESET75},
    {"chromeWalletPreset100", IDS_WOOTZ_WALLET_PRESET100},
    {"chromeWalletUnsupportedNetwork", IDS_WOOTZ_WALLET_UNSUPPORTED_NETWORK},
    {"chromeWalletNetworkETH", IDS_WOOTZ_WALLET_NETWORK_E_T_H},
    {"chromeWalletNetworkMain", IDS_WOOTZ_WALLET_NETWORK_MAIN},
    {"chromeWalletNetworkTest", IDS_WOOTZ_WALLET_NETWORK_TEST},
    {"chromeWalletNetworkGoerli", IDS_WOOTZ_WALLET_NETWORK_GOERLI},
    {"chromeWalletNetworkSepolia", IDS_WOOTZ_WALLET_NETWORK_SEPOLIA},
    {"chromeWalletNetworkLocalhost", IDS_WOOTZ_WALLET_NETWORK_LOCALHOST},
    {"chromeWalletSelectAccount", IDS_WOOTZ_WALLET_SELECT_ACCOUNT},
    {"chromeWalletSearchAccount", IDS_WOOTZ_WALLET_SEARCH_ACCOUNT},
    {"chromeWalletSelectNetwork", IDS_WOOTZ_WALLET_SELECT_NETWORK},
    {"chromeWalletSelectAsset", IDS_WOOTZ_WALLET_SELECT_ASSET},
    {"chromeWalletSearchAsset", IDS_WOOTZ_WALLET_SEARCH_ASSET},
    {"chromeWalletSwapFrom", IDS_WOOTZ_WALLET_SWAP_FROM},
    {"chromeWalletSwapTo", IDS_WOOTZ_WALLET_SWAP_TO},
    {"chromeWalletSwapEstimate", IDS_WOOTZ_WALLET_SWAP_ESTIMATE},
    {"chromeWalletSwapMarket", IDS_WOOTZ_WALLET_SWAP_MARKET},
    {"chromeWalletSwapLimit", IDS_WOOTZ_WALLET_SWAP_LIMIT},
    {"chromeWalletSwapPriceIn", IDS_WOOTZ_WALLET_SWAP_PRICE_IN},
    {"chromeWalletBuyTitle", IDS_WOOTZ_WALLET_BUY_TITLE},
    {"chromeWalletBuyDescription", IDS_WOOTZ_WALLET_BUY_DESCRIPTION},
    {"chromeWalletBuyContinueButton", IDS_WOOTZ_WALLET_BUY_CONTINUE_BUTTON},
    {"chromeWalletSignTransactionTitle",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_TITLE},
    {"chromeWalletSignWarning", IDS_WOOTZ_WALLET_SIGN_WARNING},
    {"chromeWalletSignWarningTitle", IDS_WOOTZ_WALLET_SIGN_WARNING_TITLE},
    {"chromeWalletSignTransactionMessageTitle",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_MESSAGE_TITLE},
    {"chromeWalletSignTransactionEIP712MessageDomain",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_EIP712_MESSAGE_DOMAIN},
    {"chromeWalletSignTransactionEIP712MessageTitle",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_EIP712_MESSAGE_TITLE},
    {"chromeWalletSignTransactionEIP712MessageHideDetails",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_EIP712_MESSAGE_HIDE_DETAILS},
    {"chromeWalletSignTransactionButton",
     IDS_WOOTZ_WALLET_SIGN_TRANSACTION_BUTTON},
    {"chromeWalletProvideEncryptionKeyTitle",
     IDS_WOOTZ_WALLET_PROVIDE_ENCRYPTION_KEY_TITLE},
    {"chromeWalletProvideEncryptionKeyDescription",
     IDS_WOOTZ_WALLET_PROVIDE_ENCRYPTION_KEY_DESCRIPTION},
    {"chromeWalletProvideEncryptionKeyButton",
     IDS_WOOTZ_WALLET_PROVIDE_ENCRYPTION_KEY_BUTTON},
    {"chromeWalletReadEncryptedMessageTitle",
     IDS_WOOTZ_WALLET_READ_ENCRYPTED_MESSAGE_TITLE},
    {"chromeWalletReadEncryptedMessageDecryptButton",
     IDS_WOOTZ_WALLET_READ_ENCRYPTED_MESSAGE_DECRYPT_BUTTON},
    {"chromeWalletReadEncryptedMessageButton",
     IDS_WOOTZ_WALLET_READ_ENCRYPTED_MESSAGE_BUTTON},
    {"chromeWalletAllowSpendTitle", IDS_WOOTZ_WALLET_ALLOW_SPEND_TITLE},
    {"chromeWalletAllowSpendDescription",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_DESCRIPTION},
    {"chromeWalletAllowSpendBoxTitle", IDS_WOOTZ_WALLET_ALLOW_SPEND_BOX_TITLE},
    {"chromeWalletAllowSpendTransactionFee",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_TRANSACTION_FEE},
    {"chromeWalletAllowSpendEditButton",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_EDIT_BUTTON},
    {"chromeWalletAllowSpendDetailsButton",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_DETAILS_BUTTON},
    {"chromeWalletAllowSpendRejectButton",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_REJECT_BUTTON},
    {"chromeWalletAllowSpendConfirmButton",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_CONFIRM_BUTTON},
    {"chromeWalletAllowSpendCurrentAllowance",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_CURRENT_ALLOWANCE},
    {"chromeWalletAllowSpendProposedAllowance",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_PROPOSED_ALLOWANCE},
    {"chromeWalletAllowSpendUnlimitedWarningTitle",
     IDS_WOOTZ_WALLET_ALLOW_SPEND_UNLIMITED_WARNING_TITLE},
    {"chromeWalletAllowAddNetworkTitle",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_TITLE},
    {"chromeWalletAllowChangeNetworkTitle",
     IDS_WOOTZ_WALLET_ALLOW_CHANGE_NETWORK_TITLE},
    {"chromeWalletAllowChangeNetworkDescription",
     IDS_WOOTZ_WALLET_ALLOW_CHANGE_NETWORK_DESCRIPTION},
    {"chromeWalletAllowChangeNetworkButton",
     IDS_WOOTZ_WALLET_ALLOW_CHANGE_NETWORK_BUTTON},
    {"chromeWalletAllowAddNetworkDescription",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_DESCRIPTION},
    {"chromeWalletAllowAddNetworkLearnMoreButton",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_LEARN_MORE_BUTTON},
    {"chromeWalletAllowAddNetworkName", IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_NAME},
    {"chromeWalletAllowAddNetworkUrl", IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_URL},
    {"chromeWalletAllowAddNetworkDetailsButton",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_DETAILS_BUTTON},
    {"chromeWalletAllowAddNetworkButton",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_BUTTON},
    {"chromeWalletChainId", IDS_WOOTZ_WALLET_CHAIN_ID},
    {"chromeWalletAllowAddNetworkCurrencySymbol",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_CURRENCY_SYMBOL},
    {"chromeWalletAllowAddNetworkExplorer",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_EXPLORER},
    {"chromeWalletAllowAddNetworkNetworkPanelTitle",
     IDS_WOOTZ_WALLET_ALLOW_ADD_NETWORK_PANEL_TITLE},
    {"chromeWalletAllowAddNetworkDetailsPanelTitle",
     IDS_WOOTZ_WALLET_ALLOW_ADD_DETAILS_PANEL_TITLE},
    {"chromeWalletConfirmTransactionTotal",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_TOTAL},
    {"chromeWalletConfirmTransactionGasFee",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_GAS_FEE},
    {"chromeWalletConfirmTransactionTransactionFee",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_TRANSACTION_FEE},
    {"chromeWalletConfirmTransactionBid",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_BID},
    {"chromeWalletConfirmTransactionAmountGas",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_AMOUNT_GAS},
    {"chromeWalletConfirmTransactionAmountFee",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_AMOUNT_FEE},
    {"chromeWalletConfirmTransactionNoData",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_NO_DATA},
    {"chromeWalletConfirmTransactionNext",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_NEXT},
    {"chromeWalletConfirmTransactionFirst",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_FIRST},
    {"chromeWalletConfirmTransactions", IDS_WOOTZ_WALLET_CONFIRM_TRANSACTIONS},
    {"chromeWalletConfirmTransactionAccountCreationFee",
     IDS_WOOTZ_WALLET_CONFIRM_TRANSACTION_ACCOUNT_CREATION_FEE},
    {"chromeWalletTransactionGasLimit", IDS_WOOTZ_WALLET_TRANSACTION_GAS_LIMIT},
    {"chromeWalletTransactionGasPremium",
     IDS_WOOTZ_WALLET_TRANSACTION_GAS_PREMIUM},
    {"chromeWalletTransactionGasFeeCap",
     IDS_WOOTZ_WALLET_TRANSACTION_GAS_FEE_CAP},
    {"chromeWalletPanelTitle", IDS_WOOTZ_WALLET_PANEL_TITLE},
    {"chromeWalletPanelConnected", IDS_WOOTZ_WALLET_PANEL_CONNECTED},
    {"chromeWalletSitePermissionsAccounts",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_ACCOUNTS},
    {"chromeWalletSitePermissionsDisconnect",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_DISCONNECT},
    {"chromeWalletSitePermissionsSwitch",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_SWITCH},
    {"chromeWalletSitePermissionsTrust",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_TRUST},
    {"chromeWalletSitePermissionsRevoke",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_REVOKE},
    {"chromeWalletChangeNetwork", IDS_WOOTZ_WALLET_CHANGE_NETWORK},
    {"chromeWalletChangeAccount", IDS_WOOTZ_WALLET_CHANGE_ACCOUNT},
    {"chromeWalletActive", IDS_WOOTZ_WALLET_ACTIVE},
    {"chromeWalletNotConnected", IDS_WOOTZ_WALLET_NOT_CONNECTED},
    {"chromeWalletConnectedAccounts", IDS_WOOTZ_WALLET_CONNECTED_ACCOUNTS},
    {"chromeWalletAvailableAccounts", IDS_WOOTZ_WALLET_AVAILABLE_ACCOUNTS},
    {"chromeWalletSitePermissionsNewAccount",
     IDS_WOOTZ_WALLET_SITE_PERMISSIONS_NEW_ACCOUNT},
    {"chromeWalletPanelBlocked", IDS_WOOTZ_WALLET_PANEL_BLOCKED},
    {"chromeWalletTitle", IDS_WOOTZ_WALLET_TITLE},
    {"chromeWalletWelcomePanelDescription",
     IDS_WOOTZ_WALLET_WELCOME_PANEL_DESCRIPTION},
    {"chromeWalletLearnMore", IDS_WOOTZ_WALLET_LEARN_MORE},
    {"chromeWalletTransactionDetailBoxFunction",
     IDS_WOOTZ_WALLET_TRANSACTION_DETAIL_BOX_FUNCTION},
    {"chromeWalletTransactionDetailBoxHex",
     IDS_WOOTZ_WALLET_TRANSACTION_DETAIL_BOX_HEX},
    {"chromeWalletTransactionDetailBoxBytes",
     IDS_WOOTZ_WALLET_TRANSACTION_DETAIL_BOX_BYTES},
    {"chromeWalletConnectWithSiteNext", IDS_WOOTZ_WALLET_CONNECT_WITH_SITE_NEXT},
    {"chromeWalletConnectWallet", IDS_WOOTZ_WALLET_CONNECT_WALLET},
    {"chromeWalletConnectWithSite", IDS_WOOTZ_WALLET_CONNECT_WITH_SITE},
    {"chromeWalletConnectPermittedLabel",
     IDS_WOOTZ_WALLET_CONNECT_PERMITTED_LABEL},
    {"chromeWalletConnectNotPermittedLabel",
     IDS_WOOTZ_WALLET_CONNECT_NOT_PERMITTED_LABEL},
    {"chromeWalletConnectPermissionBalanceAndActivity",
     IDS_WOOTZ_WALLET_CONNECT_PERMISSION_BALANCE_AND_ACTIVITY},
    {"chromeWalletConnectPermissionRequestApproval",
     IDS_WOOTZ_WALLET_CONNECT_PERMISSION_REQUEST_APPROVAL},
    {"chromeWalletConnectPermissionAddress",
     IDS_WOOTZ_WALLET_CONNECT_PERMISSION_ADDRESS},
    {"chromeWalletConnectPermissionMoveFunds",
     IDS_WOOTZ_WALLET_CONNECT_PERMISSION_MOVE_FUNDS},
    {"chromeWalletConnectTrustWarning", IDS_WOOTZ_WALLET_CONNECT_TRUST_WARNING},
    {"chromeWalletPermissionDuration", IDS_WOOTZ_WALLET_PERMISSION_DURATION},
    {"chromeWalletPermissionUntilClose",
     IDS_WOOTZ_WALLET_PERMISSION_UNTIL_CLOSE},
    {"chromeWalletPermissionOneDay", IDS_WOOTZ_WALLET_PERMISSION_ONE_DAY},
    {"chromeWalletPermissionOneWeek", IDS_WOOTZ_WALLET_PERMISSION_ONE_WEEK},
    {"chromeWalletPermissionForever", IDS_WOOTZ_WALLET_PERMISSION_FOREVER},
    {"chromeWalletCryptoWalletsDetected",
     IDS_WOOTZ_WALLET_CRYPTO_WALLETS_DETECTED},
    {"chromeWalletLegacyWalletDetected",
     IDS_WOOTZ_WALLET_LEGACY_WALLET_DETECTED},
    {"chromeWalletCryptoWalletsDescriptionTwo",
     IDS_WOOTZ_WALLET_CRYPTO_WALLETS_DESCRIPTION_TWO},
    {"chromeWalletImportWootzLegacyDescription",
     IDS_WOOTZ_WALLET_IMPORT_WOOTZ_LEGACY_DESCRIPTION},
    {"chromeWalletImportWootzLegacyInput",
     IDS_WOOTZ_WALLET_IMPORT_WOOTZ_LEGACY_INPUT},
    {"chromeWalletConnectHardwarePanelConnected",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_CONNECTED},
    {"chromeWalletConnectHardwarePanelDisconnected",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_DISCONNECTED},
    {"chromeWalletConnectHardwarePanelInstructions",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_INSTRUCTIONS},
    {"chromeWalletConnectHardwarePanelConnect",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_CONNECT},
    {"chromeWalletConnectHardwarePanelConfirmation",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_CONFIRMATION},
    {"chromeWalletConnectHardwarePanelOpenApp",
     IDS_WOOTZ_WALLET_CONNECT_HARDWARE_PANEL_OPEN_APP},
    {"chromeWalletTransactionSent", IDS_WOOTZ_WALLET_TRANSACTION_SENT},
    {"chromeWalletTransactionReceived", IDS_WOOTZ_WALLET_TRANSACTION_RECEIVED},
    {"chromeWalletTransactionExplorerMissing",
     IDS_WOOTZ_WALLET_TRANSACTION_EXPLORER_MISSING},
    {"chromeWalletTransactionExplorer", IDS_WOOTZ_WALLET_TRANSACTION_EXPLORER},
    {"chromeWalletTransactionCopyHash", IDS_WOOTZ_WALLET_TRANSACTION_COPY_HASH},
    {"chromeWalletTransactionSpeedup", IDS_WOOTZ_WALLET_TRANSACTION_SPEEDUP},
    {"chromeWalletTransactionCancel", IDS_WOOTZ_WALLET_TRANSACTION_CANCEL},
    {"chromeWalletTransactionRetry", IDS_WOOTZ_WALLET_TRANSACTION_RETRY},
    {"chromeWalletTransactionStatusUnapproved",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_UNAPPROVED},
    {"chromeWalletTransactionStatusApproved",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_APPROVED},
    {"chromeWalletTransactionStatusRejected",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_REJECTED},
    {"chromeWalletTransactionStatusSubmitted",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_SUBMITTED},
    {"chromeWalletTransactionStatusConfirmed",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_CONFIRMED},
    {"chromeWalletTransactionStatusError",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_ERROR},
    {"chromeWalletTransactionStatusDropped",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_DROPPED},
    {"chromeWalletTransactionStatusSigned",
     IDS_WOOTZ_WALLET_TRANSACTION_STATUS_SIGNED},
    {"chromeWalletOn", IDS_WOOTZ_WALLET_ON},
    {"chromeWalletRecentTransactions", IDS_WOOTZ_WALLET_RECENT_TRANSACTIONS},
    {"chromeWalletTransactionDetailHash",
     IDS_WOOTZ_WALLET_TRANSACTION_DETAIL_HASH},
    {"chromeWalletTransactionDetailNetwork",
     IDS_WOOTZ_WALLET_TRANSACTION_DETAIL_NETWORK},
    {"chromeWalletTransactionPlaceholder",
     IDS_WOOTZ_WALLET_TRANSACTION_PLACEHOLDER},
    {"chromeWalletTransactionApproveUnlimited",
     IDS_WOOTZ_WALLET_TRANSACTION_APPROVE_UNLIMITED},
    {"chromeWalletEditGasTitle1", IDS_WOOTZ_WALLET_EDIT_GAS_TITLE1},
    {"chromeWalletEditGasTitle2", IDS_WOOTZ_WALLET_EDIT_GAS_TITLE2},
    {"chromeWalletEditGasDescription", IDS_WOOTZ_WALLET_EDIT_GAS_DESCRIPTION},
    {"chromeWalletEditGasLow", IDS_WOOTZ_WALLET_EDIT_GAS_LOW},
    {"chromeWalletEditGasOptimal", IDS_WOOTZ_WALLET_EDIT_GAS_OPTIMAL},
    {"chromeWalletEditGasHigh", IDS_WOOTZ_WALLET_EDIT_GAS_HIGH},
    {"chromeWalletEditGasLimit", IDS_WOOTZ_WALLET_EDIT_GAS_LIMIT},
    {"chromeWalletEditGasPerGasPrice", IDS_WOOTZ_WALLET_EDIT_GAS_PER_GAS_PRICE},
    {"chromeWalletEditGasPerTipLimit", IDS_WOOTZ_WALLET_EDIT_GAS_PER_TIP_LIMIT},
    {"chromeWalletEditGasPerPriceLimit",
     IDS_WOOTZ_WALLET_EDIT_GAS_PER_PRICE_LIMIT},
    {"chromeWalletEditGasMaxFee", IDS_WOOTZ_WALLET_EDIT_GAS_MAX_FEE},
    {"chromeWalletEditGasMaximumFee", IDS_WOOTZ_WALLET_EDIT_GAS_MAXIMUM_FEE},
    {"chromeWalletEditGasBaseFee", IDS_WOOTZ_WALLET_EDIT_GAS_BASE_FEE},
    {"chromeWalletEditGasGwei", IDS_WOOTZ_WALLET_EDIT_GAS_GWEI},
    {"chromeWalletEditGasSetCustom", IDS_WOOTZ_WALLET_EDIT_GAS_SET_CUSTOM},
    {"chromeWalletEditGasSetSuggested", IDS_WOOTZ_WALLET_EDIT_GAS_SET_SUGGESTED},
    {"chromeWalletEditGasZeroGasPriceWarning",
     IDS_WOOTZ_WALLET_EDIT_GAS_ZERO_GAS_PRICE_WARNING},
    {"chromeWalletAdvancedTransactionSettings",
     IDS_WOOTZ_WALLET_ADVANCED_TRANSACTION_SETTINGS},
    {"chromeWalletAdvancedTransactionSettingsPlaceholder",
     IDS_WOOTZ_WALLET_ADVANCED_TRANSACTION_SETTINGS_PLACEHOLDER},
    {"chromeWalletEditNonce", IDS_WOOTZ_WALLET_EDIT_NONCE},
    {"chromeWalletEditNonceInfo", IDS_WOOTZ_WALLET_EDIT_NONCE_INFO},
    {"chromeWalletEditPermissionsTitle",
     IDS_WOOTZ_WALLET_EDIT_PERMISSIONS_TITLE},
    {"chromeWalletEditPermissionsDescription",
     IDS_WOOTZ_WALLET_EDIT_PERMISSIONS_DESCRIPTION},
    {"chromeWalletEditPermissionsButton",
     IDS_WOOTZ_WALLET_EDIT_PERMISSIONS_BUTTON},
    {"chromeWalletEditPermissionsProposedAllowance",
     IDS_WOOTZ_WALLET_EDIT_PERMISSIONS_PROPOSED_ALLOWANCE},
    {"chromeWalletEditPermissionsCustomAllowance",
     IDS_WOOTZ_WALLET_EDIT_PERMISSIONS_CUSTOM_ALLOWANCE},
    {"chromeWalletNotValidEthAddress", IDS_WOOTZ_WALLET_NOT_VALID_ETH_ADDRESS},
    {"chromeWalletNotValidSolAddress", IDS_WOOTZ_WALLET_NOT_VALID_SOL_ADDRESS},
    {"chromeWalletNotValidAddress", IDS_WOOTZ_WALLET_NOT_VALID_ADDRESS},
    {"chromeWalletNotDomain", IDS_WOOTZ_WALLET_NOT_DOMAIN},
    {"chromeWalletSameAddressError", IDS_WOOTZ_WALLET_SAME_ADDRESS_ERROR},
    {"chromeWalletContractAddressError",
     IDS_WOOTZ_WALLET_CONTRACT_ADDRESS_ERROR},
    {"chromeWalletFailedChecksumTitle", IDS_WOOTZ_WALLET_FAILED_CHECKSUM_TITLE},
    {"chromeWalletFailedChecksumDescription",
     IDS_WOOTZ_WALLET_FAILED_CHECKSUM_DESCRIPTION},
    {"chromeWalletHowToSolve", IDS_WOOTZ_WALLET_HOW_TO_SOLVE},
    {"chromeWalletAddressMissingChecksumInfoWarning",
     IDS_WOOTZ_WALLET_ADDRESS_MISSING_CHECKSUM_INFO_WARNING},
    {"chromeWalletNotValidChecksumAddressError",
     IDS_WOOTZ_WALLET_NOT_VALID_CHECKSUM_ADDRESS_ERROR},
    {"chromeWalletMissingGasLimitError",
     IDS_WOOTZ_WALLET_MISSING_GAS_LIMIT_ERROR},
    {"chromeWalletZeroBalanceError", IDS_WOOTZ_WALLET_ZERO_BALANCE_ERROR},
    {"chromeWalletAddressRequiredError",
     IDS_WOOTZ_WALLET_ADDRESS_REQUIRED_ERROR},
    {"chromeWalletInvalidZcashUnifiedRecipientAddress",
     IDS_WOOTZ_WALLET_INVALID_ZCASH_UNIFIED_RECIPIENT_ADDRESS},
    {"chromeWalletChecksumModalTitle", IDS_WOOTZ_WALLET_CHECKSUM_MODAL_TITLE},
    {"chromeWalletChecksumModalDescription",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_DESCRIPTION},
    {"chromeWalletChecksumModalStepOneTitle",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_STEP_ONE_TITLE},
    {"chromeWalletChecksumModalStepOneDescription",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_STEP_ONE_DESCRIPTION},
    {"chromeWalletChecksumModalStepTwoTitle",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_STEP_TWO_TITLE},
    {"chromeWalletChecksumModalStepTwoDescription",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_STEP_TWO_DESCRIPTION},
    {"chromeWalletChecksumModalNeedHelp",
     IDS_WOOTZ_WALLET_CHECKSUM_MODAL_NEED_HELP},
    {"chromeWalletQueueOf", IDS_WOOTZ_WALLET_QUEUE_OF},
    {"chromeWalletQueueNext", IDS_WOOTZ_WALLET_QUEUE_NEXT},
    {"chromeWalletQueueFirst", IDS_WOOTZ_WALLET_QUEUE_FIRST},
    {"chromeWalletQueueRejectAll", IDS_WOOTZ_WALLET_QUEUE_REJECT_ALL},
    {"chromeWalletSwapInsufficientBalance",
     IDS_WOOTZ_WALLET_SWAP_INSUFFICIENT_BALANCE},
    {"chromeWalletSwapInsufficientFundsForGas",
     IDS_WOOTZ_WALLET_SWAP_INSUFFICIENT_FUNDS_FOR_GAS},
    {"chromeWalletSwapInsufficientLiquidity",
     IDS_WOOTZ_WALLET_SWAP_INSUFFICIENT_LIQUIDITY},
    {"chromeWalletSwapInsufficientAllowance",
     IDS_WOOTZ_WALLET_SWAP_INSUFFICIENT_ALLOWANCE},
    {"chromeWalletSwapUnknownError", IDS_WOOTZ_WALLET_SWAP_UNKNOWN_ERROR},
    {"chromeWalletSwapReviewSpend", IDS_WOOTZ_WALLET_SWAP_REVIEW_SPEND},
    {"chromeWalletSwapReviewReceive", IDS_WOOTZ_WALLET_SWAP_REVIEW_RECEIVE},
    {"chromeWalletSwapReviewHeader", IDS_WOOTZ_WALLET_SWAP_REVIEW_HEADER},
    {"chromeWalletSolanaSwap", IDS_WOOTZ_WALLET_SOLANA_SWAP},
    {"chromeWalletUnlockError", IDS_WOOTZ_WALLET_UNLOCK_ERROR},
    {"chromeWalletDeviceUnknownScheme", IDS_WOOTZ_WALLET_UNKNOWN_SCHEME_ERROR},
    {"chromeWalletApprovalTransactionIntent",
     IDS_WOOTZ_WALLET_APPROVAL_TRANSACTION_INTENT},
    {"chromeWalletNoAccountsWithABalance",
     IDS_WOOTZ_WALLET_NO_ACCOUNTS_WITH_A_BALANCE},
    {"chromeWalletNoAccountsWithABalanceDescription",
     IDS_WOOTZ_WALLET_NO_ACCOUNTS_WITH_A_BALANCE_DESCRIPTION},
    {"chromeWalletLedgerFilecoinUnlockError",
     IDS_WOOTZ_WALLET_LEDGER_FILECOIN_UNLOCK_ERROR},
    {"chromeWalletLedgerValidationError",
     IDS_WOOTZ_WALLET_LEDGER_VALIDATION_ERROR},
    {"chromeWalletHardwareAccountNotFound",
     IDS_WOOTZ_WALLET_HARDWARE_ACCOUNT_NOT_FOUND_ERROR},
    {"chromeWalletCreateBridgeError",
     IDS_WOOTZ_WALLET_HARDWARE_CREATE_BRIDGE_ERROR},
    {"chromeWalletProcessTransactionError",
     IDS_WOOTZ_WALLET_HARDWARE_PROCESS_TRANSACTION_ERROR},
    {"chromeWalletApproveTransactionError",
     IDS_WOOTZ_WALLET_HARDWARE_APPROVE_TRANSACTION_ERROR},
    {"chromeWalletTransactionNotFoundSignError",
     IDS_WOOTZ_WALLET_HARDWARE_TRANSACTION_NOT_FOUND_ERROR},
    {"chromeWalletSignOnDeviceError",
     IDS_WOOTZ_WALLET_HARDWARE_TRANSACTION_DEVICE_ERROR},
    {"chromeWalletNoMessageToSignError",
     IDS_WOOTZ_WALLET_HARDWARE_TRANSACTION_NO_MESSAGE_TO_SIGN_ERROR},
    {"chromeWalletProcessMessageError",
     IDS_WOOTZ_WALLET_HARDWARE_SIGN_MESSAGE_ERROR},
    {"chromeWalletHardwareOperationUnsupportedError",
     IDS_WOOTZ_WALLET_HARDWARE_OPERATION_UNSUPPORTED_ERROR},
    {"chromeWalletUnknownKeyringError",
     IDS_WOOTZ_WALLET_HARDWARE_UNKNOWN_KEYRING_ERROR},
    {"chromeWalletBridgeCommandInProgress",
     IDS_WOOTZ_WALLET_HARDWARE_COMMAND_IN_PROGRESS_ERROR},
    {"chromeWalletBridgeNotReady",
     IDS_WOOTZ_WALLET_HARDWARE_BRIDGE_NOT_READY_ERROR},
    {"chromeWalletAddSuggestedTokenTitle",
     IDS_WOOTZ_WALLET_ADD_SUGGESTED_TOKEN_TITLE},
    {"chromeWalletAddSuggestedTokenDescription",
     IDS_WOOTZ_WALLET_ADD_SUGGESTED_TOKEN_DESCRIPTION},
    {"chromeWalletNFTDetailBlockchain", IDS_WOOTZ_WALLET_NFT_DETAIL_BLOCKCHAIN},
    {"chromeWalletNFTDetailTokenStandard",
     IDS_WOOTZ_WALLET_NFT_DETAIL_TOKEN_STANDARD},
    {"chromeWalletNFTDetailTokenID", IDS_WOOTZ_WALLET_NFT_DETAIL_TOKEN_ID},
    {"chromeWalletNFTDetailContractAddress",
     IDS_WOOTZ_WALLET_NFT_DETAIL_CONTRACT_ADDRESS},
    {"chromeWalletNFTDetailDescription",
     IDS_WOOTZ_WALLET_NFT_DETAIL_DESCRIPTION},
    {"chromeWalletNFTDetailImageAddress",
     IDS_WOOTZ_WALLET_NFT_DETAIL_IMAGE_ADDRESS},
    {"chromeWalletNFTDetailsOverview", IDS_WOOTZ_WALLET_NFT_DETAILS_OVERVIEW},
    {"chromeWalletNFTDetailsOwnedBy", IDS_WOOTZ_WALLET_NFT_DETAILS_OWNED_BY},
    {"chromeWalletNFTDetailsViewAccount",
     IDS_WOOTZ_WALLET_NFT_DETAILS_VIEW_ACCOUNT},
    {"chromeWalletNFTDetailsPinningStatusLabel",
     IDS_WOOTZ_WALLET_NFT_DETAILS_PINNING_STATUS_LABEL},
    {"chromeWalletNFTDetailsCid", IDS_WOOTZ_WALLET_NFT_DETAILS_CID},
    {"chromeWalletNFTDetailsNotAvailable",
     IDS_WOOTZ_WALLET_NFT_DETAILS_NOT_AVAILABLE},
    {"chromeWalletNFTDetailsProperties",
     IDS_WOOTZ_WALLET_NFT_DETAILS_PROPERTIES},
    {"chromeWalletTrezorSignTypedDataError",
     IDS_WOOTZ_WALLET_TREZOR_SIGN_TYPED_DATA_ERROR},
    {"chromeWalletSweepstakesTitle", IDS_WOOTZ_WALLET_SWEEPSTAKES_TITLE},
    {"chromeWalletSweepstakesDescription",
     IDS_WOOTZ_WALLET_SWEEPSTAKES_DESCRIPTION},
    {"chromeWalletSweepstakesCallToAction",
     IDS_WOOTZ_WALLET_SWEEPSTAKES_CALL_TO_ACTION},
    {"chromeWalletNotValidFilAddress", IDS_WOOTZ_WALLET_NOT_VALID_FIL_ADDRESS},
    {"chromeWalletBuyWithRamp", IDS_WOOTZ_WALLET_BUY_WITH_RAMP},
    {"chromeWalletSellWithProvider", IDS_WOOTZ_WALLET_SELL_WITH_PROVIDER},
    {"chromeWalletBuyDisclaimer", IDS_WOOTZ_WALLET_BUY_DISCLAIMER},
    {"chromeWalletBuyWithSardine", IDS_WOOTZ_WALLET_BUY_WITH_SARDINE},
    {"chromeWalletBuyWithTransak", IDS_WOOTZ_WALLET_BUY_WITH_TRANSAK},
    {"chromeWalletBuyWithStripe", IDS_WOOTZ_WALLET_BUY_WITH_STRIPE},
    {"chromeWalletBuyWithCoinbase", IDS_WOOTZ_WALLET_BUY_WITH_COINBASE},
    {"chromeWalletBuyRampNetworkName", IDS_WOOTZ_WALLET_BUY_RAMP_NETWORK_NAME},
    {"chromeWalletBuySardineName", IDS_WOOTZ_WALLET_BUY_SARDINE_NAME},
    {"chromeWalletBuyTransakName", IDS_WOOTZ_WALLET_BUY_TRANSAK_NAME},
    {"chromeWalletBuyStripeName", IDS_WOOTZ_WALLET_BUY_STRIPE_NAME},
    {"chromeWalletBuyCoinbaseName", IDS_WOOTZ_WALLET_BUY_COINBASE_NAME},
    {"chromeWalletBuyRampDescription", IDS_WOOTZ_WALLET_BUY_RAMP_DESCRIPTION},
    {"chromeWalletBuySardineDescription",
     IDS_WOOTZ_WALLET_BUY_SARDINE_DESCRIPTION},
    {"chromeWalletBuyTransakDescription",
     IDS_WOOTZ_WALLET_BUY_TRANSAK_DESCRIPTION},
    {"chromeWalletBuyStripeDescription",
     IDS_WOOTZ_WALLET_BUY_STRIPE_DESCRIPTION},
    {"chromeWalletBuyCoinbaseDescription",
     IDS_WOOTZ_WALLET_BUY_COINBASE_DESCRIPTION},
    {"chromeWalletNetworkFilterAll", IDS_WOOTZ_WALLET_NETWORK_FILTER_ALL},
    {"chromeWalletAssetFilterLowToHigh",
     IDS_WOOTZ_WALLET_ASSET_FILTER_LOW_TO_HIGH},
    {"chromeWalletAssetFilterHighToLow",
     IDS_WOOTZ_WALLET_ASSET_FILTER_HIGH_TO_LOW},
    {"chromeWalletAssetFilterAToZ", IDS_WOOTZ_WALLET_ASSET_FILTER_A_TO_Z},
    {"chromeWalletAssetFilterZToA", IDS_WOOTZ_WALLET_ASSET_FILTER_Z_TO_A},
    {"chromeWalletNone", IDS_WOOTZ_WALLET_NONE},
    {"chromeWalletNetworks", IDS_WOOTZ_WALLET_NETWORKS},
    {"chromeWalletPortfolioGroupByTitle",
     IDS_WOOTZ_WALLET_PORTFOLIO_GROUP_BY_TITLE},
    {"chromeWalletPortfolioGroupByDescription",
     IDS_WOOTZ_WALLET_PORTFOLIO_GROUP_BY_DESCRIPTION},
    {"chromeWalletPortfolioFiltersTitle",
     IDS_WOOTZ_WALLET_PORTFOLIO_FILTERS_TITLE},
    {"chromeWalletPortfolioNftsFiltersTitle",
     IDS_WOOTZ_WALLET_PORTFOLIO_NFTS_FILTERS_TITLE},
    {"chromeWalletSortAssets", IDS_WOOTZ_WALLET_SORT_ASSETS},
    {"chromeWalletSortAssetsDescription",
     IDS_WOOTZ_WALLET_SORT_ASSETS_DESCRIPTION},
    {"chromeWalletHideSmallBalances", IDS_WOOTZ_WALLET_SMALL_BALANCES},
    {"chromeWalletHideSmallBalancesDescription",
     IDS_WOOTZ_WALLET_SMALL_BALANCES_DESCRIPTION},
    {"chromeWalletSelectAccounts", IDS_WOOTZ_WALLET_SELECT_ACCOUNTS},
    {"chromeWalletSelectNetworks", IDS_WOOTZ_WALLET_SELECT_NETWORKS},
    {"chromeWalletSelectAll", IDS_WOOTZ_WALLET_SELECT_ALL},
    {"chromeWalletDeselectAll", IDS_WOOTZ_WALLET_DESELECT_ALL},
    {"chromeWalletPrimaryNetworks", IDS_WOOTZ_WALLET_PRIMARY_NETWORKS},
    {"chromeWalletETHAccountDescription",
     IDS_WOOTZ_WALLET_ETH_ACCOUNT_DESCRIPTION},
    {"chromeWalletSOLAccountDescription",
     IDS_WOOTZ_WALLET_SOL_ACCOUNT_DESCRIPTION},
    {"chromeWalletFILAccountDescription",
     IDS_WOOTZ_WALLET_FIL_ACCOUNT_DESCRIPTION},
    {"chromeWalletBTCMainnetAccountDescription",
     IDS_WOOTZ_WALLET_BTC_MAINNET_ACCOUNT_DESCRIPTION},
    {"chromeWalletBTCTestnetAccountDescription",
     IDS_WOOTZ_WALLET_BTC_TESTNET_ACCOUNT_DESCRIPTION},
    {"chromeWalletZECAccountDescription",
     IDS_WOOTZ_WALLET_ZEC_ACCOUNT_DESCRIPTION},
    {"chromeWalletZECTestnetAccountDescription",
     IDS_WOOTZ_WALLET_ZEC_TESTNET_ACCOUNT_DESCRIPTION},
    {"chromeWalletShowNetworkLogoOnNftsTitle",
     IDS_WOOTZ_WALLET_SHOW_NETWORK_LOGO_ON_NFTS_TITLE},
    {"chromeWalletShowNetworkLogoOnNftsDescription",
     IDS_WOOTZ_WALLET_SHOW_NETWORK_LOGO_ON_NFTS_DESCRIPTION},
    {"chromeWalletShowSpamNftsTitle", IDS_WOOTZ_WALLET_SHOW_SPAM_NFTS_TITLE},
    {"chromeWalletShowSpamNftsDescription",
     IDS_WOOTZ_WALLET_SHOW_SPAM_NFTS_DESCRIPTION},
    {"chromeWalletPortfolioSettings", IDS_WOOTZ_WALLET_PORTFOLIO_SETTINGS},
    {"chromeWalletAccountFilterAllAccounts",
     IDS_WOOTZ_WALLET_ACCOUNT_FILTER_ALL_ACCOUNTS},
    {"chromeWalletTransactionSubmittedTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_SUBMITTED_TITLE},
    {"chromeWalletTransactionSubmittedDescription",
     IDS_WOOTZ_WALLET_TRANSACTION_SUBMITTED_DESCRIPTION},
    {"chromeWalletTransactionSignedTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_SIGNED_TITLE},
    {"chromeWalletTransactionSignedDescription",
     IDS_WOOTZ_WALLET_TRANSACTION_SIGNED_DESCRIPTION},
    {"chromeWalletTransactionFailedHeaderTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_HEADER_TITLE},
    {"chromeWalletTransactionFailedTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_TITLE},
    {"chromeWalletTransactionFailedDescription",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_DESCRIPTION},
    {"chromeWalletTransactionFailedSwapNextCTA",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_SWAP_NEXT_CTA},
    {"chromeWalletTransactionFailedNextCTA",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_NEXT_CTA},
    {"chromeWalletTransactionFailedViewErrorCTA",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_VIEW_ERROR_CTA},
    {"chromeWalletTransactionFailedReceiptCTA",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_RECEIPT_CTA},
    {"chromeWalletTransactionFailedModalTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_MODAL_TITLE},
    {"chromeWalletTransactionFailedModalSubtitle",
     IDS_WOOTZ_WALLET_TRANSACTION_FAILED_MODAL_SUBTITLE},
    {"chromeWalletTransactionCompleteSwapHeaderTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_COMPLETE_SWAP_HEADER_TITLE},
    {"chromeWalletTransactionCompleteTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_COMPLETE_TITLE},
    {"chromeWalletTransactionCompleteDescription",
     IDS_WOOTZ_WALLET_TRANSACTION_COMPLETE_DESCRIPTION},
    {"chromeWalletTransactionCompleteReceiptCTA",
     IDS_WOOTZ_WALLET_TRANSACTION_COMPLETE_RECEIPT_CTA},
    {"chromeWalletTransactionConfirmingTitle",
     IDS_WOOTZ_WALLET_TRANSACTION_CONFIRMING_TITLE},
    {"chromeWalletTransactionConfirmingDescription",
     IDS_WOOTZ_WALLET_TRANSACTION_CONFIRMING_DESCRIPTION},
    {"chromeWalletTransactionConfirmingText",
     IDS_WOOTZ_WALLET_TRANSACTION_CONFIRMING_TEXT},
    {"chromeWalletTransactionIntentDappInteraction",
     IDS_WOOTZ_WALLET_TRANSACTION_INTENT_DAPP_INTERACTION},
    {"chromeWalletTransactionIntentSend",
     IDS_WOOTZ_WALLET_TRANSACTION_INTENT_SEND},
    {"chromeWalletTransactionIntentSwap",
     IDS_WOOTZ_WALLET_TRANSACTION_INTENT_SWAP},
    {"chromeWalletSignInWithWootzWallet",
     IDS_WOOTZ_WALLET_SIGN_IN_WITH_WOOTZ_WALLET},
    {"chromeWalletSignInWithWootzWalletMessage",
     IDS_WOOTZ_WALLET_SIGN_IN_WITH_WOOTZ_WALLET_MESSAGE},
    {"chromeWalletSeeDetails", IDS_WOOTZ_WALLET_SEE_DETAILS},
    {"chromeWalletSignIn", IDS_WOOTZ_WALLET_SIGN_IN},
    {"chromeWalletOrigin", IDS_WOOTZ_WALLET_ORIGIN},
    {"chromeWalletAddress", IDS_WOOTZ_WALLET_ADDRESS},
    {"chromeWalletStatement", IDS_WOOTZ_WALLET_STATEMENT},
    {"chromeWalletUri", IDS_WOOTZ_WALLET_URI},
    {"chromeWalletVersion", IDS_WOOTZ_WALLET_VERSION},
    {"chromeWalletNonce", IDS_WOOTZ_WALLET_NONCE},
    {"chromeWalletIssuedAt", IDS_WOOTZ_WALLET_ISSUED_AT},
    {"chromeWalletExpirationTime", IDS_WOOTZ_WALLET_EXPIRATION_TIME},
    {"chromeWalletNotBefore", IDS_WOOTZ_WALLET_NOT_BEFORE},
    {"chromeWalletRequestId", IDS_WOOTZ_WALLET_REQUEST_ID},
    {"chromeWalletResources", IDS_WOOTZ_WALLET_RESOURCES},
    {"chromeWalletSecurityRiskDetected",
     IDS_WOOTZ_WALLET_SECURITY_RISK_DETECTED},
    {"chromeWalletEditGasLimitError", IDS_WOOTZ_WALLET_EDIT_GAS_LIMIT_ERROR},
    {"chromeWalletApproveTransaction", IDS_WOOTZ_WALLET_APPROVE_TRANSACTION},
    {"chromeWalletSolanaSystemProgram", IDS_WOOTZ_WALLET_SOLANA_SYSTEM_PROGRAM},
    {"chromeWalletSolanaConfigProgram", IDS_WOOTZ_WALLET_SOLANA_CONFIG_PROGRAM},
    {"chromeWalletSolanaStakeProgram", IDS_WOOTZ_WALLET_SOLANA_STAKE_PROGRAM},
    {"chromeWalletSolanaVoteProgram", IDS_WOOTZ_WALLET_SOLANA_VOTE_PROGRAM},
    {"chromeWalletSolanaBPFLoader", IDS_WOOTZ_WALLET_SOLANA_BP_FLOADER},
    {"chromeWalletSolanaAccounts", IDS_WOOTZ_WALLET_SOLANA_ACCOUNTS},
    {"chromeWalletSolanaData", IDS_WOOTZ_WALLET_SOLANA_DATA},
    {"chromeWalletSolanaProgramID", IDS_WOOTZ_WALLET_SOLANA_PROGRAM_ID},
    {"chromeWalletSolanaMaxRetries", IDS_WOOTZ_WALLET_SOLANA_MAX_RETRIES},
    {"chromeWalletSolanaPreflightCommitment",
     IDS_WOOTZ_WALLET_SOLANA_PREFLIGHT_COMMITMENT},
    {"chromeWalletSolanaSkipPreflight", IDS_WOOTZ_WALLET_SOLANA_SKIP_PREFLIGHT},
    {"chromeWalletSolanaAddressLookupTableAccount",
     IDS_WOOTZ_WALLET_SOLANA_ADDRESS_LOOKUP_TABLE_ACCOUNT},
    {"chromeWalletSolanaAddressLookupTableIndex",
     IDS_WOOTZ_WALLET_SOLANA_ADDRESS_LOOKUP_TABLE_INDEX},
    {"chromeWalletSolanaEd25519Program",
     IDS_WOOTZ_WALLET_SOLANA_ED25519_PROGRAM},
    {"chromeWalletSolanaSecp256k1Program",
     IDS_WOOTZ_WALLET_SOLANA_SECP256K1_PROGRAM},
    {"chromeWalletNetworkFilterSecondary",
     IDS_WOOTZ_WALLET_NETWORK_FILTER_SECONDARY},
    {"chromeWalletNetworkFilterTestNetworks",
     IDS_WOOTZ_WALLET_NETWORK_FILTER_TEST_NETWORKS},
    {"chromeWalletSelectCurrency", IDS_WOOTZ_WALLET_SELECT_CURRENCY},
    {"chromeWalletSearchCurrency", IDS_WOOTZ_WALLET_SEARCH_CURRENCY},
    {"chromeWalletHelpCenter", IDS_WOOTZ_WALLET_HELP_CENTER},
    {"chromeWalletHelpCenterText", IDS_WOOTZ_WALLET_HELP_CENTER_TEXT},
    {"chromeWalletBuyTapBuyNotSupportedMessage",
     IDS_WOOTZ_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"chromeWalletAuroraModalTitle", IDS_WOOTZ_WALLET_AURORA_MODAL_TITLE},
    {"chromeWalletAuroraModalDescription",
     IDS_WOOTZ_WALLET_AURORA_MODAL_DESCRIPTION},
    {"chromeWalletAuroraModalLearnMore",
     IDS_WOOTZ_WALLET_AURORA_MODAL_LEARN_MORE},
    {"chromeWalletAuroraModalLearnMoreAboutRisk",
     IDS_WOOTZ_WALLET_AURORA_MODAL_LEARN_MORE_ABOUT_RISK},
    {"chromeWalletAuroraModalDontShowAgain",
     IDS_WOOTZ_WALLET_AURORA_MODAL_DONT_SHOW_AGAIN},
    {"chromeWalletAuroraModalOPenButtonText",
     IDS_WOOTZ_WALLET_AURORA_MODAL_OPEN_BUTTON_TEXT},
    {"chromeWalletBridgeToAuroraButton",
     IDS_WOOTZ_WALLET_BRIDGE_TO_AURORA_BUTTON},
    {"chromeWalletPasswordStrengthTooltipHeading",
     IDS_WOOTZ_WALLET_PASSWORD_STRENGTH_TOOLTIP_HEADING},
    {"chromeWalletPasswordStrengthTooltipIsLongEnough",
     IDS_WOOTZ_WALLET_PASSWORD_STRENGTH_TOOLTIP_IS_LONG_ENOUGH},
    {"chromeWalletPasswordMatch", IDS_WOOTZ_WALLET_PASSWORD_MATCH},
    {"chromeWalletPasswordIsStrong", IDS_WOOTZ_WALLET_PASSWORD_IS_STRONG},
    {"chromeWalletPasswordIsMediumStrength",
     IDS_WOOTZ_WALLET_PASSWORD_IS_MEDIUM_STRENGTH},
    {"chromeWalletPasswordIsWeak", IDS_WOOTZ_WALLET_PASSWORD_IS_WEAK},
    {"chromeWalletAutoLockTitle", IDS_WOOTZ_WALLET_AUTO_LOCK_TITLE},
    {"chromeWalletAutoLockDurationMinutes",
     IDS_WOOTZ_WALLET_AUTO_LOCK_DURATION_MINUTES},
    {"chromeWalletAutoLockDurationHours",
     IDS_WOOTZ_WALLET_AUTO_LOCK_DURATION_HOURS},
    {"chromeWalletCreatingWallet", IDS_WOOTZ_WALLET_CREATING_WALLET},
    {"chromeWalletOnboardingRecoveryPhraseBackupIntroTitle",
     IDS_WOOTZ_WALLET_ONBOARDING_RECOVERY_PHRASE_BACKUP_INTRO_TITLE},
    {"chromeWalletOnboardingRecoveryPhraseBackupIntroDescription",
     IDS_WOOTZ_WALLET_ONBOARDING_RECOVERY_PHRASE_BACKUP_INTRO_DESCRIPTION},
    {"chromeWalletRecoveryPhraseBackupWarning",
     IDS_WOOTZ_WALLET_RECOVERY_PHRASE_BACKUP_WARNING},
    {"chromeWalletRecoveryPhraseBackupWarningImportant",
     IDS_WOOTZ_WALLET_RECOVERY_PHRASE_BACKUP_WARNING_IMPORTANT},
    {"chromeWalletRecoveryWordInstructions",
     IDS_WOOTZ_WALLET_RECOVERY_WORD_INSTRUCTIONS},
    {"chromeWalletVerifyRecoveryPhraseGoBack",
     IDS_WOOTZ_WALLET_VERIFY_RECOVERY_PHRASE_GO_BACK},
    {"chromeWalletRecoveryPhraseBackupTitle",
     IDS_WOOTZ_WALLET_RECOVERY_PHRASE_BACKUP_TITLE},
    {"chromeWalletCopiedToClipboard", IDS_WOOTZ_WALLET_COPIED_TO_CLIPBOARD},
    {"chromeWalletClickToSeeRecoveryPhrase",
     IDS_WOOTZ_WALLET_CLICK_TO_SEE_RECOVERY_PHRASE},
    {"chromeWalletOrdinalFirst", IDS_WOOTZ_WALLET_ORDINAL_FIRST},
    {"chromeWalletOrdinalThird", IDS_WOOTZ_WALLET_ORDINAL_THIRD},
    {"chromeWalletOnboardingSuccessTitle",
     IDS_WOOTZ_WALLET_ONBOARDING_SUCCESS_TITLE},
    {"chromeWalletOnboardingSuccessDescription",
     IDS_WOOTZ_WALLET_ONBOARDING_SUCCESS_DESCRIPTION},
    {"chromeWalletOnboardingSuccessGoToPortfolio",
     IDS_WOOTZ_WALLET_ONBOARDING_SUCCESS_GO_TO_PORTFOLIO},
    {"chromeWalletArticleLinkWhatsARecoveryPhrase",
     IDS_WOOTZ_WALLET_ARTICLE_LINK_WHATS_A_RECOVERY_PHRASE},
    {"chromeWalletImportOrRestoreWalletTitle",
     IDS_WOOTZ_WALLET_IMPORT_OR_RESTORE_WALLET_TITLE},
    {"chromeWalletImportOrRestoreDescription",
     IDS_WOOTZ_WALLET_IMPORT_OR_RESTORE_DESCRIPTION},
    {"chromeWalletRestoreMyWootzWallet",
     IDS_WOOTZ_WALLET_RESTORE_MY_WOOTZ_WALLET},
    {"chromeWalletRestoreMyWootzWalletInstructions",
     IDS_WOOTZ_WALLET_RESTORE_MY_WOOTZ_WALLET_INSTRUCTIONS},
    {"chromeWalletRestoreMyWootzWalletDescription",
     IDS_WOOTZ_WALLET_RESTORE_MY_WOOTZ_WALLET_DESCRIPTION},
    {"chromeWalletImportFromMetaMask", IDS_WOOTZ_WALLET_IMPORT_FROM_META_MASK},
    {"chromeWalletImportFromMetaMaskDescription",
     IDS_WOOTZ_WALLET_IMPORT_FROM_META_MASK_DESCRIPTION},
    {"chromeWalletImportFromMetaMaskSeedInstructions",
     IDS_WOOTZ_WALLET_IMPORT_FROM_META_MASK_SEED_INSTRUCTIONS},
    {"chromeWalletCreateWalletInsteadLink",
     IDS_WOOTZ_WALLET_CREATE_WALLET_INSTEAD_LINK},
    {"chromeWalletRestoreAlternateLength",
     IDS_WOOTZ_WALLET_RESTORE_ALTERNATE_LENGTH},
    {"chromeWalletRestoreWalletError", IDS_WOOTZ_WALLET_RESTORE_WALLET_ERROR},
    {"chromeWalletImportWithRecoveryPhrase",
     IDS_WOOTZ_WALLET_IMPORT_WITH_RECOVERY_PHRASE},
    {"chromeWalletMetamaskDetected", IDS_WOOTZ_WALLET_METAMASK_DETECTED},
    {"chromeWalletUsePassword", IDS_WOOTZ_WALLET_USE_PASSWORD},
    {"chromeWalletRecoveryPhraseWord", IDS_WOOTZ_WALLET_RECOVERY_PHRASE_WORD},
    {"chromeWalletImportPasswordError", IDS_WOOTZ_WALLET_IMPORT_PASSWORD_ERROR},
    {"chromeWalletMetaMaskExtensionDetected",
     IDS_WOOTZ_WALLET_METAMASK_EXTENSION_DETECTED},
    {"chromeWalletMetaMaskExtensionImportDescription",
     IDS_WOOTZ_WALLET_METAMASK_EXTENSION_IMPORT_DESCRIPTION},
    {"chromeWalletMetaMaskPasswordInputPlaceholder",
     IDS_WOOTZ_WALLET_METAMASK_PASSWORD_INPUT_PLACEHOLDER},
    {"chromeWalletInputLabelPassword", IDS_WOOTZ_WALLET_INPUT_LABEL_PASSWORD},
    {"chromeWalletLearnAboutMyWallet", IDS_WOOTZ_WALLET_LEARN_ABOUT_MY_WALLET},
    {"chromeWalletDisclosuresTitle", IDS_WOOTZ_WALLET_DISCLOSURES_TITLE},
    {"chromeWalletDisclosuresDescription",
     IDS_WOOTZ_WALLET_DISCLOSURES_DESCRIPTION},
    {"chromeWalletSelfCustodyDisclosureCheckboxText",
     IDS_WOOTZ_WALLET_SELF_CUSTODY_DISCLOSURE_CHECKBOX_TEXT},
    {"chromeWalletTermsOfServiceCheckboxText",
     IDS_WOOTZ_WALLET_TERMS_OF_SERVICE_CHECKBOX_TEXT},
    {"chromeWalletBuyCryptoButton", IDS_WOOTZ_WALLET_BUY_CRYPTO_BUTTON},
    {"chromeWalletDepositCryptoButton", IDS_WOOTZ_WALLET_DEPOSIT_CRYPTO_BUTTON},
    {"chromeWalletCheckingInstalledExtensions",
     IDS_WOOTZ_WALLET_CHECKING_INSTALLED_EXTENSIONS},
    {"chromeWalletImportFromLegacy", IDS_WOOTZ_WALLET_IMPORT_FROM_LEGACY},
    {"chromeWalletBuySelectAsset", IDS_WOOTZ_WALLET_BUY_SELECT_ASSET},
    {"chromeWalletFundWalletTitle", IDS_WOOTZ_WALLET_FUND_WALLET_TITLE},
    {"chromeWalletDepositFundsTitle", IDS_WOOTZ_WALLET_DEPOSIT_FUNDS_TITLE},
    {"chromeWalletDepositX", IDS_WOOTZ_WALLET_DEPOSIT_X},
    {"chromeWalletDepositSolSplTokens", IDS_WOOTZ_WALLET_DEPOSIT_SOL_SPL_TOKENS},
    {"chromeWalletDepositErc", IDS_WOOTZ_WALLET_DEPOSIT_ERC},
    {"chromeWalletDepositOnlySendOnXNetwork",
     IDS_WOOTZ_WALLET_DEPOSIT_ONLY_SEND_ON_X_NETWORK},
    {"chromeWalletFundWalletDescription",
     IDS_WOOTZ_WALLET_FUND_WALLET_DESCRIPTION},
    {"chromeWalletLearnMoreAboutWootzWallet",
     IDS_WOOTZ_WALLET_LEARN_MORE_ABOUT_WOOTZ_WALLET},
    {"chromeWalletMarketDataAllAssetsFilter",
     IDS_WOOTZ_WALLET_MARKET_DATA_ALL_ASSETS_FILTER},
    {"chromeWalletMarketDataTradableFilter",
     IDS_WOOTZ_WALLET_MARKET_DATA_TRADABLE_FILTER},
    {"chromeWalletMarketDataAssetsColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_ASSETS_COLUMN},
    {"chromeWalletMarketDataPriceColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_PRICE_COLUMN},
    {"chromeWalletMarketData24HrColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_24Hr_COLUMN},
    {"chromeWalletMarketDataMarketCapColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_MARKETCAP_COLUMN},
    {"chromeWalletMarketDataVolumeColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_VOLUME_COLUMN},
    {"chromeWalletMarketDataNoAssetsFound",
     IDS_WOOTZ_WALLET_MARKET_DATA_NO_ASSETS_FOUND},
    {"chromeWalletInformation", IDS_WOOTZ_WALLET_INFORMATION},
    {"chromeWalletRankStat", IDS_WOOTZ_WALLET_RANK_STAT},
    {"chromeWalletVolumeStat", IDS_WOOTZ_WALLET_VOLUME_STAT},
    {"chromeWalletMarketCapStat", IDS_WOOTZ_WALLET_MARKET_CAP_STAT},
    {"chromeWalletBuyTapBuyNotSupportedMessage",
     IDS_WOOTZ_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"chromeWalletHelpCenterText", IDS_WOOTZ_WALLET_HELP_CENTER_TEXT},
    {"chromeWalletMarketDataAllAssetsFilter",
     IDS_WOOTZ_WALLET_MARKET_DATA_ALL_ASSETS_FILTER},
    {"chromeWalletMarketDataTradableFilter",
     IDS_WOOTZ_WALLET_MARKET_DATA_TRADABLE_FILTER},
    {"chromeWalletMarketDataAssetsColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_ASSETS_COLUMN},
    {"chromeWalletMarketDataPriceColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_PRICE_COLUMN},
    {"chromeWalletMarketData24HrColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_24Hr_COLUMN},
    {"chromeWalletMarketDataMarketCapColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_MARKETCAP_COLUMN},
    {"chromeWalletMarketDataVolumeColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_VOLUME_COLUMN},
    {"chromeWalletMarketDataBuyDepositColumn",
     IDS_WOOTZ_WALLET_MARKET_DATA_BUY_DEPOSIT_COLUMN},
    {"chromeWalletMarketDataNoAssetsFound",
     IDS_WOOTZ_WALLET_MARKET_DATA_NO_ASSETS_FOUND},
    {"chromeWalletInformation", IDS_WOOTZ_WALLET_INFORMATION},
    {"chromeWalletRankStat", IDS_WOOTZ_WALLET_RANK_STAT},
    {"chromeWalletVolumeStat", IDS_WOOTZ_WALLET_VOLUME_STAT},
    {"chromeWalletMarketCapStat", IDS_WOOTZ_WALLET_MARKET_CAP_STAT},
    {"chromeWalletBuyTapBuyNotSupportedMessage",
     IDS_WOOTZ_WALLET_BUY_TAB_BUY_NOT_SUPPORTED_MESSAGE},
    {"chromeWalletSearchingForDomain", IDS_WOOTZ_WALLET_SEARCHING_FOR_DOMAIN},
    {"chromeWalletEnsOffChainLookupTitle",
     IDS_WOOTZ_WALLET_ENS_OFF_CHAIN_LOOKUP_TITLE},
    {"chromeWalletEnsOffChainLookupDescription",
     IDS_WOOTZ_WALLET_ENS_OFF_CHAIN_LOOKUP_DESCRIPTION},
    {"chromeWalletEnsOffChainButton", IDS_WOOTZ_WALLET_ENS_OFF_CHAIN_BUTTON},
    {"chromeWalletPortfolioTokenDetailsMenuLabel",
     IDS_WOOTZ_WALLET_PORTFOLIO_TOKEN_DETAILS_MENU_LABEL},
    {"chromeWalletPortfolioViewOnExplorerMenuLabel",
     IDS_WOOTZ_WALLET_PORTFOLIO_VIEW_ON_EXPLORER_MENU_LABEL},
    {"chromeWalletPortfolioHideTokenMenuLabel",
     IDS_WOOTZ_WALLET_PORTFOLIO_VIEW_HIDE_TOKEN_LABEL},
    {"chromeWalletHideTokenModalTitle", IDS_WOOTZ_WALLET_HIDE_TOKEN_MODAL_TITLE},
    {"chromeWalletTokenContractAddress",
     IDS_WOOTZ_WALLET_TOKEN_CONTRACT_ADDRESS},
    {"chromeWalletTokenDecimal", IDS_WOOTZ_WALLET_TOKEN_DECIMAL},
    {"chromeWalletMakeTokenVisibleInstructions",
     IDS_WOOTZ_WALLET_MAKE_TOKEN_VISIBLE_INSTRUCTIONS},
    {"chromeWalletConfirmHidingToken", IDS_WOOTZ_WALLET_CONFIRM_HIDING_TOKEN},
    {"chromeWalletCancelHidingToken", IDS_WOOTZ_WALLET_CANCEL_HIDING_TOKEN},
    {"chromeWalletMyAssets", IDS_WOOTZ_WALLET_MY_ASSETS},
    {"chromeWalletAvailableAssets", IDS_WOOTZ_WALLET_AVAILABLE_ASSETS},
    {"chromeWalletDidntFindAssetEndOfList",
     IDS_WOOTZ_WALLET_DIDNT_FIND_ASSET_END_OF_LIST},
    {"chromeWalletDidntFindAssetInList",
     IDS_WOOTZ_WALLET_DIDNT_FIND_ASSET_IN_LIST},
    {"chromeWalletAssetNotFound", IDS_WOOTZ_WALLET_ASSET_NOT_FOUND},
    {"chromeWalletRequestFeatureButtonText",
     IDS_WOOTZ_WALLET_REQUEST_FEATURE_BUTTON_TEXT},
    {"chromeWalletEnsOffchainProceedWithYes",
     IDS_WOOTZ_WALLET_ENS_OFFCHAIN_PROCEED_WITH_YES},
    {"chromeWalletEnsOffchainProceedWithNo",
     IDS_WOOTZ_WALLET_ENS_OFFCHAIN_PROCEED_WITH_NO},
    {"chromeWalletEnsOffchainDontShowAgain",
     IDS_WOOTZ_WALLET_ENS_OFFCHAIN_DONT_SHOW_AGAIN},
    {"chromeWalletEnsOffchainWarning", IDS_WOOTZ_WALLET_ENS_OFFCHAIN_WARNING},
    {"chromeWalletAddAssetTokenTabTitle",
     IDS_WOOTZ_WALLET_ADD_ASSET_TOKEN_TAB_TITLE},
    {"chromeWalletAddAssetNftTabTitle",
     IDS_WOOTZ_WALLET_ADD_ASSET_NFT_TAB_TITLE},
    {"chromeWalletNftFetchingError", IDS_WOOTZ_WALLET_NFT_FETCHING_ERROR},
    {"chromeWalletEditToken", IDS_WOOTZ_WALLET_EDIT_TOKEN},
    {"chromeWalletFEVMAddressTranslationTitle",
     IDS_WOOTZ_WALLET_FEVM_ADDRESS_TRANSLATION_TITLE},
    {"chromeWalletFEVMAddressTranslationDescription",
     IDS_WOOTZ_WALLET_FEVM_ADDRESS_TRANSLATION_DESCRIPTION},

    // Wootz Swap
    {"chromeSwap", IDS_WOOTZ_SWAP},
    {"chromeSwapApproveToken", IDS_WOOTZ_SWAP_APPROVE_TOKEN},
    {"chromeSwapInsufficientBalance", IDS_WOOTZ_SWAP_INSUFFICIENT_BALANCE},
    {"chromeSwapInsufficientLiquidity", IDS_WOOTZ_SWAP_INSUFFICIENT_LIQUIDITY},
    {"chromeSwapSelectToken", IDS_WOOTZ_SWAP_SELECT_TOKEN},
    {"chromeSwapHalf", IDS_WOOTZ_SWAP_HALF},
    {"chromeSwapMax", IDS_WOOTZ_SWAP_MAX},
    {"chromeSwapEnterAnAmount", IDS_WOOTZ_SWAP_ENTER_AN_AMOUNT},
    {"chromeWalletFetchingQuote", IDS_WOOTZ_WALLET_FETCHING_QUOTE},
    {"chromeWalletReceiveEstimate", IDS_WOOTZ_WALLET_RECEIVE_ESTIMATE},
    {"chromeWalletFromToken", IDS_WOOTZ_WALLET_FROM_TOKEN},
    {"chromeWalletToToken", IDS_WOOTZ_WALLET_TO_TOKEN},
    {"chromeWalletNewQuoteIn", IDS_WOOTZ_WALLET_NEW_QUOTE_IN},
    {"chromeSwapBalance", IDS_WOOTZ_SWAP_BALANCE},
    {"chromeSwapSelectAToken", IDS_WOOTZ_SWAP_SELECT_A_TOKEN},
    {"chromeSwapShowTokensWithZeroBalances",
     IDS_WOOTZ_SWAP_SHOW_TOKENS_WITH_ZERO_BALANCES},
    {"chromeSwapHideTokensWithZeroBalances",
     IDS_WOOTZ_SWAP_HIDE_TOKENS_WITH_ZERO_BALANCES},
    {"chromeSwapSearchToken", IDS_WOOTZ_SWAP_SEARCH_TOKEN},
    {"chromeSwapOption", IDS_WOOTZ_SWAP_OPTION},
    {"chromeSwapPriceImpact", IDS_WOOTZ_SWAP_PRICE_IMPACT},
    {"chromeSwapMinimumReceivedAfterSlippage",
     IDS_WOOTZ_SWAP_MINIMUM_RECEIVED_AFTER_SLIPPAGE},
    {"chromeSwapNetworkFee", IDS_WOOTZ_SWAP_NETWORK_FEE},
    {"chromeSwapWootzFee", IDS_WOOTZ_SWAP_WOOTZ_FEE},
    {"chromeSwapFree", IDS_WOOTZ_SWAP_FREE},
    {"chromeSwapSwapAndSend", IDS_WOOTZ_SWAP_SWAP_AND_SEND},
    {"chromeSwapNoExtraFees", IDS_WOOTZ_SWAP_NO_EXTRA_FEES},
    {"chromeSwapConfirmAddress", IDS_WOOTZ_SWAP_CONFIRM_ADDRESS},
    {"chromeSwapAddressInputePlaceholder",
     IDS_WOOTZ_SWAP_ADDRESS_INPUT_PLACEHOLDER},
    {"chromeSwapSelectAccount", IDS_WOOTZ_SWAP_SELECT_ACCOUNT},
    {"chromeSwapToAccount", IDS_WOOTZ_SWAP_TO_ACCOUNT},
    {"chromeSwapToAddress", IDS_WOOTZ_SWAP_TO_ADDRESS},
    {"chromeSwapSlow", IDS_WOOTZ_SWAP_SLOW},
    {"chromeSwapAverage", IDS_WOOTZ_SWAP_AVERAGE},
    {"chromeSwapFast", IDS_WOOTZ_SWAP_FAST},
    {"chromeSwapGwei", IDS_WOOTZ_SWAP_GWEI},
    {"chromeSwapSlippageTolerance", IDS_WOOTZ_SWAP_SLIPPAGE_TOLERANCE},
    {"chromeSwapExchanges", IDS_WOOTZ_SWAP_EXCHANGES},
    {"chromeSwapDirectRouteTitle", IDS_WOOTZ_SWAP_DIRECT_ROUTE_TITLE},
    {"chromeSwapDirectRouteDescription",
     IDS_WOOTZ_SWAP_DIRECT_ROUTE_DESCRIPTION},
    {"chromeSwapNetworkFeeDescription", IDS_WOOTZ_SWAP_NETWORK_FEE_DESCRIPTION},
    {"chromeSwapCoinGeckoCheaper", IDS_WOOTZ_SWAP_COINGECKO_CHEAPER},
    {"chromeSwapCoinGeckoWithin", IDS_WOOTZ_SWAP_COINGECKO_WITHIN},
    {"chromeSwapCoinGeckoExpensive", IDS_WOOTZ_SWAP_COINGECKO_EXPENSIVE},
    {"chromeSwapAPI", IDS_WOOTZ_SWAP_API},
    {"chromeSwapName", IDS_WOOTZ_SWAP_NAME},
    {"chromeSwapDisconnectWallet", IDS_WOOTZ_SWAP_DISCONNECT_WALLET},
    {"chromeSwapAdvanced", IDS_WOOTZ_SWAP_ADVANCED},
    {"chromeSwapAccounts", IDS_WOOTZ_SWAP_ACCOUNTS},
    {"chromeSwapWallet", IDS_WOOTZ_SWAP_WALLET},
    {"chromeSwapBest", IDS_WOOTZ_SWAP_BEST},
    {"chromeSwapHelpCenter", IDS_WOOTZ_SWAP_HELP_CENTER},
    {"chromeSwapPrivacyPolicy", IDS_WOOTZ_SWAP_PRIVACY_POLICY},
    {"chromeSwapPrivacyDescription", IDS_WOOTZ_SWAP_PRIVACY_DESCRIPTION},
    {"chromeSwapV2Disclaimer", IDS_WOOTZ_SWAP_V2_DISCLAIMER},
    {"chromeSwapV2Privacy", IDS_WOOTZ_SWAP_V2_PRIVACY},
    {"chromeSwapChangeNetwork", IDS_WOOTZ_SWAP_CHANGE_NETWORK},

    {"chromeNftsTabImportNft", IDS_WOOTZ_WALLET_NFTS_TAB_IMPORT_NFT},
    {"chromeNftsTabEmptyStateHeading",
     IDS_WOOTZ_WALLET_NFTS_TAB_EMPTY_STATE_HEADING},
    {"chromeNftsTabEmptyStateSubHeading",
     IDS_WOOTZ_WALLET_NFTS_TAB_EMPTY_STATE_SUBHEADING},
    {"chromeNftsTabEmptyStateDisclaimer",
     IDS_WOOTZ_WALLET_NFTS_TAB_EMPTY_STATE_DISCLAIMER},
    {"chromeNftsTabHide", IDS_WOOTZ_WALLET_NFTS_TAB_HIDE},
    {"chromeNftsTabUnhide", IDS_WOOTZ_WALLET_NFTS_TAB_UNHIDE},
    {"chromeNftsTabEdit", IDS_WOOTZ_WALLET_NFTS_TAB_EDIT},
    {"chromeWalletNftUnspam", IDS_WOOTZ_WALLET_NFT_UNSPAM},
    {"chromeWalletNftJunk", IDS_WOOTZ_WALLET_NFT_JUNK},
    {"chromeWalletRemoveNftModalHeader",
     IDS_WOOTZ_WALLET_REMOVE_NFT_MODAL_HEADER},
    {"chromeWalletRemoveNftModalDescription",
     IDS_WOOTZ_WALLET_REMOVE_NFT_MODAL_DESCRIPTION},
    {"chromeWalletRemoveNftModalCancel",
     IDS_WOOTZ_WALLET_REMOVE_NFT_MODAL_CANCEL},
    {"chromeWalletRemoveNftModalConfirm",
     IDS_WOOTZ_WALLET_REMOVE_NFT_MODAL_CONFIRM},
    {"chromeWalletNftMoveToSpam", IDS_WOOTZ_WALLET_NFT_MOVE_TO_SPAM},
    {"chromeNftsTab", IDS_WOOTZ_WALLET_NFTS_TAB},
    {"chromeNftsTabHidden", IDS_WOOTZ_WALLET_NFTS_TAB_HIDDEN},
    {"chromeNftsTabCollected", IDS_WOOTZ_WALLET_NFTS_TAB_COLLECTED},
    {"chromeNftsTabRemove", IDS_WOOTZ_WALLET_NFTS_TAB_REMOVE},
    {"chromeWalletAddNftModalTitle", IDS_WOOTZ_WALLET_ADD_NFT_MODAL_TITLE},
    {"chromeWalletEditNftModalTitle", IDS_WOOTZ_WALLET_EDIT_NFT_MODAL_TITLE},
    {"chromeWalletEnableNftAutoDiscoveryModalHeader",
     IDS_WOOTZ_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_HEADER},
    {"chromeWalletEnableNftAutoDiscoveryModalDescription",
     IDS_WOOTZ_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_DESCRIPTION},
    {"chromeWalletEnableNftAutoDiscoveryModalConfirm",
     IDS_WOOTZ_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_CONFIRM},
    {"chromeWalletEnableNftAutoDiscoveryModalCancel",
     IDS_WOOTZ_WALLET_ENABLE_NFT_AUTODISCOVERY_MODAL_CANCEL},
    {"chromeWalletAutoDiscoveryEmptyStateHeading",
     IDS_WOOTZ_WALLET_AUTO_DISCOVERY_EMPTY_STATE_HEADING},
    {"chromeWalletAutoDiscoveryEmptyStateSubHeading",
     IDS_WOOTZ_WALLET_AUTO_DISCOVERY_EMPTY_STATE_SUB_HEADING},
    {"chromeWalletAutoDiscoveryEmptyStateFooter",
     IDS_WOOTZ_WALLET_AUTO_DISCOVERY_EMPTY_STATE_FOOTER},
    {"chromeWalletAutoDiscoveryEmptyStateActions",
     IDS_WOOTZ_WALLET_AUTO_DISCOVERY_EMPTY_STATE_ACTIONS},
    {"chromeWalletAutoDiscoveryEmptyStateRefresh",
     IDS_WOOTZ_WALLET_AUTO_DISCOVERY_EMPTY_STATE_REFRESH},
    {"chromeWalletUphold", IDS_WOOTZ_WALLET_UPHOLD},
    {"chromeWalletGemini", IDS_WOOTZ_WALLET_GEMINI},
    {"chromeWalletZebpay", IDS_WOOTZ_WALLET_ZEBPAY},
    {"chromeWalletBitflyer", IDS_WOOTZ_WALLET_BITFLYER},
    {"chromeWalletRewardsAccount", IDS_WOOTZ_WALLET_REWARDS_ACCOUNT},
    {"chromeWalletWootzRewardsTitle", IDS_WOOTZ_WALLET_WOOTZ_REWARDS_TITLE},
    {"chromeWalletWootzRewardsDescription",
     IDS_WOOTZ_WALLET_WOOTZ_REWARDS_DESCRIPTION},
    {"chromeWalletWootzRewardsLoggedOutDescription",
     IDS_WOOTZ_WALLET_WOOTZ_REWARDS_LOGGED_OUT_DESCRIPTION},
    {"chromeWalletLogIn", IDS_WOOTZ_WALLET_LOG_IN},
    {"chromeWalletViewOn", IDS_WOOTZ_WALLET_VIEW_ON},
    {"chromeWalletRewardsSettings", IDS_WOOTZ_WALLET_REWARDS_SETTINGS},
    {"chromeWalletPlatforms", IDS_WOOTZ_WALLET_PLATFORMS},
    {"chromeWalletNoDappsFound", IDS_WOOTZ_WALLET_NO_DAPPS_FOUND},
    {"chromeWalletActiveWallets", IDS_WOOTZ_WALLET_ACTIVE_WALLETS},
    {"chromeWalletVisitDapp", IDS_WOOTZ_WALLET_VISIT_DAPP},
    {"chromeWalletFilters", IDS_WOOTZ_WALLET_FILTERS},
    {"chromeWalletClearFilters", IDS_WOOTZ_WALLET_CLEAR_FILTERS},
    {"chromeWalletShowMore", IDS_WOOTZ_WALLET_SHOW_MORE}};

// 0x swap constants
inline constexpr char kZeroExGoerliBaseAPIURL[] =
    "https://goerli.api.0x.wallet.wootz.com";
inline constexpr char kZeroExPolygonBaseAPIURL[] =
    "https://polygon.api.0x.wallet.wootz.com";
inline constexpr char kZeroExBinanceSmartChainBaseAPIURL[] =
    "https://bsc.api.0x.wallet.wootz.com";
inline constexpr char kZeroExAvalancheBaseAPIURL[] =
    "https://avalanche.api.0x.wallet.wootz.com";
inline constexpr char kZeroExFantomBaseAPIURL[] =
    "https://fantom.api.0x.wallet.wootz.com";
inline constexpr char kZeroExCeloBaseAPIURL[] =
    "https://celo.api.0x.wallet.wootz.com";
inline constexpr char kZeroExOptimismBaseAPIURL[] =
    "https://optimism.api.0x.wallet.wootz.com";
inline constexpr char kZeroExArbitrumBaseAPIURL[] =
    "https://arbitrum.api.0x.wallet.wootz.com";
inline constexpr char kZeroExBaseBaseAPIURL[] =
    "https://base.api.0x.wallet.wootz.com";
inline constexpr char kZeroExEthereumBaseAPIURL[] =
    "https://api.0x.wallet.wootz.com";
inline constexpr char kEVMFeeRecipient[] =
    "0xbd9420A98a7Bd6B89765e5715e169481602D9c3d";
inline constexpr char kAffiliateAddress[] =
    "0xbd9420A98a7Bd6B89765e5715e169481602D9c3d";

// Jupiter swap constants
inline constexpr char kJupiterBaseAPIURL[] = "https://jupiter.wallet.wootz.com";
inline constexpr char kJupiterReferralKey[] =
    "7yke2kxg6ewNsun61qBkdsLdxuXcUiB8CMB47Zv39Aoy";
inline constexpr char kJupiterReferralProgram[] =
    "REFER4ZgmyYx9c6He5XfaTMiGfdLwRnkV4RPp9t9iF3";
inline constexpr char kJupiterReferralProgramHeader[] = "referral_ata";
inline constexpr char kWrappedSolanaMintAddress[] =
    "So11111111111111111111111111111111111111112";

// Blowfish simulations constants
inline constexpr char kBlowfishBaseAPIURL[] =
    "https://blowfish.wallet.wootz.com";
inline constexpr char kBlowfishAPIVersionHeader[] = "X-Api-Version";
inline constexpr char kBlowfishAPIVersion[] = "2023-06-05";

// LiFi constants
inline constexpr char kLiFiBaseAPIURL[] = "https://lifi.wallet.wootz.com";
inline constexpr char kLiFiIntegratorID[] = "chrome";
inline constexpr char kLiFiNativeEVMAssetContractAddress[] =
    "0x0000000000000000000000000000000000000000";
inline constexpr char kLiFiNativeSVMAssetContractAddress[] =
    "So11111111111111111111111111111111111111112";

// LiFi // 0x common constants
inline constexpr char kNativeEVMAssetContractAddress[] =
    "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";

constexpr int64_t kBlockTrackerDefaultTimeInSeconds = 20;
constexpr int64_t kLogTrackerDefaultTimeInSeconds = 20;
constexpr int64_t kSolanaBlockTrackerTimeInSeconds = 2;

// Ankr constants
inline constexpr char kAnkrAdvancedAPIBaseURL[] =
    "https://multichain.ankr.wallet.wootz.com/";

// Unstoppable domains record key for ethereum address.
inline constexpr char kCryptoEthAddressKey[] = "crypto.ETH.address";
// Unstoppable domains record key for solana address.
inline constexpr char kCryptoSolAddressKey[] = "crypto.SOL.address";
// Unstoppable domains record key for filecoin address.
inline constexpr char kCryptoFilAddressKey[] = "crypto.FIL.address";

// ERC-165 identifier for ERC721 interface.
inline constexpr char kERC1155InterfaceId[] = "0xd9b67a26";
inline constexpr char kERC1155MetadataInterfaceId[] = "0x0e89341c";
inline constexpr char kERC721InterfaceId[] = "0x80ac58cd";
inline constexpr char kERC721MetadataInterfaceId[] = "0x5b5e139f";

inline constexpr char kBitcoinPrefKey[] = "bitcoin";
inline constexpr char kZCashPrefKey[] = "zcash";
inline constexpr char kEthereumPrefKey[] = "ethereum";
inline constexpr char kFilecoinPrefKey[] = "filecoin";
inline constexpr char kSolanaPrefKey[] = "solana";

inline constexpr char kEthereumBlockTagEarliest[] = "earliest";
inline constexpr char kEthereumBlockTagLatest[] = "latest";

inline constexpr char kBitcoinTestnetRpcEndpoint[] =
    "https://blockstream.info/testnet/api/";

inline constexpr char kMeldRpcEndpoint[] = "https://api-meld.wallet.wootz.com";
inline constexpr char kMeldRpcVersionHeader[] = "Meld-Version";
inline constexpr char kMeldRpcVersion[] = "2023-05-26";

const std::string GetSardineNetworkName(const std::string& chain_id);
const base::flat_map<std::string, std::string>&
GetEthBalanceScannerContractAddresses();
const std::vector<std::string>& GetEthSupportedNftInterfaces();
// Returns the URL for the Ratios service.
const std::string GetAssetRatioBaseURL();
const base::flat_map<std::string, std::string>& GetAnkrBlockchains();
// https://docs.rs/solana-program/1.18.10/src/solana_program/clock.rs.html#129-131
inline constexpr int kSolanaValidBlockHeightThreshold = 150;
}  // namespace wootz_wallet

#endif  // WOOTZ_COMPONENTS_WOOTZ_WALLET_BROWSER_WOOTZ_WALLET_CONSTANTS_H_
