// Copyright (c) 2023 The Wootz Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

#include "components/webui/webui_resources.h"

#include <vector>

#include "base/containers/flat_map.h"
#include "base/no_destructor.h"
#include "base/strings/utf_string_conversions.h"
#include "components/constants/url_constants.h"
#include "build/build_config.h"
#include "components/grit/wootz_components_resources.h"
#include "components/grit/wootz_components_strings.h"
#include "components/grit/components_resources.h"
#include "ui/base/l10n/l10n_util.h"
#include "ui/base/webui/resource_path.h"
#include "ui/base/webui/web_ui_util.h"

// #if !BUILDFLAG(IS_ANDROID) && !BUILDFLAG(IS_IOS)
// #include "brave/components/brave_rewards/resources/grit/brave_rewards_resources.h"
// #endif

namespace wootz {

base::span<const webui::ResourcePath> GetWebUIResources(
    std::string_view webui_name) {
  static const base::NoDestructor<
      base::flat_map<std::string_view, std::vector<webui::ResourcePath>>>
      kResources{{
// #if !BUILDFLAG(IS_ANDROID) && !BUILDFLAG(IS_IOS)
//           {"newtab",
//            {{"img/toolbar/menu_btn.svg", IDR_WOOTZ_COMMON_TOOLBAR_IMG},
//             // Hash path is the MD5 of the file contents,
//             // webpack image loader does this
//             {"fd85070af5114d6ac462c466e78448e4.svg", IDR_WOOTZ_NEW_TAB_IMG1},
//             {"314e7529efec41c8867019815f4d8dad.svg", IDR_WOOTZ_NEW_TAB_IMG4},
//             {"6c337c63662ee0ba4e57f6f8156d69ce.svg", IDR_WOOTZ_NEW_TAB_IMG2},
//             // New tab Backgrounds
//             {"dylan-malval_sea-min.webp", IDR_WOOTZ_NEW_TAB_BACKGROUND1},
//             // private tab
//             {"c168145d6bf1abf2c0322636366f7dbe.svg",
//              IDR_WOOTZ_PRIVATE_TAB_TOR_IMG},
//             {"dbdc336ccc651b8a7c925b3482d6e65a.svg",
//              IDR_WOOTZ_PRIVATE_TAB_IMG}}},
//           {"rewards",
//            {
//                {"favicon.ico", IDR_WOOTZ_REWARDS_FAVICON},
//            }},
//           {"welcome", {{"favicon.ico", IDR_WOOTZ_WELCOME_PAGE_FAVICON}}},
// #endif
          {"adblock", {}},
      }};

  if (auto it = kResources->find(webui_name); it != kResources->end()) {
    return it->second;
  }
  return {};
}  // NO-LINT (readability/fn_size)

base::span<const webui::LocalizedString> GetWebUILocalizedStrings(
    std::string_view webui_name) {
  static const base::NoDestructor<
      base::flat_map<std::string_view, std::vector<webui::LocalizedString>>>
      kLocalizedStrings{{
          {"newtab",
           {
               {"adsTrackersBlocked",
                IDS_WOOTZ_NEW_TAB_TOTAL_ADS_TRACKERS_BLOCKED},
               {"httpsUpgraded", IDS_WOOTZ_NEW_TAB_TOTAL_HTTPS_UPGRADES},
               {"estimatedTimeSaved", IDS_WOOTZ_NEW_TAB_TOTAL_TIME_SAVED},
               {"estimatedBandwidthSaved",
                IDS_WOOTZ_NEW_TAB_ESTIMATED_BANDWIDTH_SAVED},
               {"thumbRemoved", IDS_WOOTZ_NEW_TAB_THUMB_REMOVED},
               {"undoRemoved", IDS_WOOTZ_NEW_TAB_UNDO_REMOVED},
               {"close", IDS_WOOTZ_NEW_TAB_CLOSE},
               {"restoreAll", IDS_WOOTZ_NEW_TAB_RESTORE_ALL},
               {"second", IDS_WOOTZ_NEW_TAB_SECOND},
               {"seconds", IDS_WOOTZ_NEW_TAB_SECONDS},
               {"minute", IDS_WOOTZ_NEW_TAB_MINUTE},
               {"minutes", IDS_WOOTZ_NEW_TAB_MINUTES},
               {"hour", IDS_WOOTZ_NEW_TAB_HOUR},
               {"hours", IDS_WOOTZ_NEW_TAB_HOURS},
               {"day", IDS_WOOTZ_NEW_TAB_DAY},
               {"days", IDS_WOOTZ_NEW_TAB_DAYS},
               {"B", IDS_WOOTZ_NEW_TAB_BYTES},
               {"KB", IDS_WOOTZ_NEW_TAB_KILOBYTES},
               {"MB", IDS_WOOTZ_NEW_TAB_MEGABYTES},
               {"GB", IDS_WOOTZ_NEW_TAB_GIGABYTES},
               {"photoBy", IDS_WOOTZ_NEW_TAB_PHOTO_BY},
               {"hide", IDS_WOOTZ_NEW_TAB_HIDE},
               {"dashboardSettingsTitle",
                IDS_WOOTZ_NEW_TAB_DASHBOARD_SETTINGS_TITLE},
               {"customize", IDS_WOOTZ_NEW_TAB_CUSTOMIZE},
               {"showBackgroundImage", IDS_WOOTZ_NEW_TAB_SHOW_BACKGROUND_IMAGE},
               {"wootzBackgroundImageOptionTitle",
                IDS_WOOTZ_NEW_TAB_WOOTZ_BACKGROUND_IMAGE_OPTION_TITLE},
               {"customBackgroundImageOptionTitle",
                IDS_WOOTZ_NEW_TAB_CUSTOM_BACKGROUND_IMAGE_OPTION_TITLE},
               {"customBackgroundImageOptionUploadLabel",
                IDS_WOOTZ_NEW_TAB_CUSTOM_BACKGROUND_IMAGE_OPTION_UPLOAD_LABEL},
               {"showWootzStats", IDS_WOOTZ_NEW_TAB_SHOW_WOOTZ_STATS},
               {"showClock", IDS_WOOTZ_NEW_TAB_SHOW_CLOCK},
               {"clockFormat", IDS_WOOTZ_NEW_TAB_CLOCK_FORMAT},
               {"clockFormatDefault", IDS_WOOTZ_NEW_TAB_CLOCK_FORMAT_DEFAULT},
               {"clockFormat12", IDS_WOOTZ_NEW_TAB_CLOCK_FORMAT_12},
               {"clockFormat24", IDS_WOOTZ_NEW_TAB_CLOCK_FORMAT_24},
               {"addTopSiteDialogTitle",
                IDS_WOOTZ_NEW_TAB_ADD_TOP_SITE_DIALOG_TITLE},
               {"editTopSiteDialogTitle",
                IDS_WOOTZ_NEW_TAB_EDIT_TOP_SITE_DIALOG_TITLE},
               {"editSiteTileMenuItem",
                IDS_WOOTZ_NEW_TAB_EDIT_SITE_TILE_MENU_ITEM},
               {"removeTileMenuItem", IDS_WOOTZ_NEW_TAB_REMOVE_TILE_MENU_ITEM},
               {"addTopSiteDialogURLLabel",
                IDS_WOOTZ_NEW_TAB_ADD_TOP_SITE_DIALOG_URL_LABEL},
               {"addTopSiteDialogURLInputPlaceHolder",
                IDS_WOOTZ_NEW_TAB_ADD_TOP_SITE_DIALOG_URL_INPUT_PLACEHOLDER},
               {"addTopSiteDialogNameLabel",
                IDS_WOOTZ_NEW_TAB_ADD_TOP_SITE_DIALOG_NAME_LABEL},
               {"addTopSiteDialogNameInputPlaceHolder",
                IDS_WOOTZ_NEW_TAB_ADD_TOP_SITE_DIALOG_NAME_INPUT_PLACEHOLDER},
               {"addTopSiteDialogSaveButtonLabel",
                IDS_WOOTZ_NEW_TAB_ADD_TOP_SITE_DIALOG_SAVE_BUTTON_LABEL},
               {"addTopSiteDialogCancelButtonLabel",
                IDS_WOOTZ_NEW_TAB_ADD_TOP_SITE_DIALOG_CANCEL_BUTTON_LABEL},
               {"showTopSites", IDS_WOOTZ_NEW_TAB_SHOW_TOP_SITES},
               {"showFavoritesLabel", IDS_WOOTZ_NEW_TAB_SHOW_FAVORITES_LABEL},
               {"showFavoritesDesc", IDS_WOOTZ_NEW_TAB_SHOW_FAVORITES_DESC},
               {"showFrecencyLabel", IDS_WOOTZ_NEW_TAB_SHOW_FRECENCY_LABEL},
               {"showFrecencyDesc", IDS_WOOTZ_NEW_TAB_SHOW_FRECENCY_DESC},
               {"addSiteMenuLabel", IDS_WOOTZ_NEW_TAB_ADD_SITE_MENU_LABEL},
               {"showFrecencyMenuLabel",
                IDS_WOOTZ_NEW_TAB_SHOW_FRECENCY_MENU_LABEL},
               {"showFavoritesMenuLabel",
                IDS_WOOTZ_NEW_TAB_SHOW_FAVORITES_MENU_LABEL},
               {"searchCustomizeList", IDS_WOOTZ_NEW_TAB_SEARCH_CUSTOMIZE_LIST},
               {"searchWootzPlaceholder",
                IDS_WOOTZ_NEW_TAB_SEARCH_WOOTZ_PLACEHOLDER},
               {"searchHide", IDS_WOOTZ_NEW_TAB_SEARCH_HIDE_SEARCH},
               {"searchAskLeo", IDS_OMNIBOX_ASK_LEO_DESCRIPTION},
               {"searchNonWootzPlaceholder",
                IDS_WOOTZ_NEW_TAB_SEARCH_NON_WOOTZ_PLACEHOLDER},
               {"searchShowSetting", IDS_WOOTZ_NEW_TAB_SEARCH_SHOW_SETTING},
               {"searchEnableSearchEnginesTitle",
                IDS_WOOTZ_NEW_TAB_SEARCH_ENABLE_SEARCH_ENGINES_TITLE},
               {"searchCustomizeSearchEngines",
                IDS_WOOTZ_NEW_TAB_SEARCH_CUSTOMIZE_SEARCH_ENGINES},
               {"searchEnableSuggestionsPromptTitle",
                IDS_WOOTZ_NEW_TAB_SEARCH_ENABLE_SEARCH_SUGGESTIONS_TITLE},
               {"searchEnableSuggestionsPromptExplanation",
                IDS_WOOTZ_NEW_TAB_SEARCH_ENABLE_SEARCH_SUGGESTIONS_EXPLANATION},
               {"searchEnableSuggestionsPromptEnable",
                IDS_WOOTZ_NEW_TAB_SEARCH_ENABLE_SEARCH_SUGGESTIONS_ENABLE},
               {"searchEnableSuggestionsPromptDismiss",
                IDS_WOOTZ_NEW_TAB_SEARCH_ENABLE_SEARCH_SUGGESTIONS_DISMISS},
               {"showRewards", IDS_WOOTZ_NEW_TAB_SHOW_REWARDS},
               {"cards", IDS_WOOTZ_NEW_TAB_SHOW_CARDS},
               {"brandedWallpaperOptIn",
                IDS_WOOTZ_NEW_TAB_BRANDED_WALLPAPER_OPT_IN},
               {"sponsoredImageEarningTitle",
                IDS_WOOTZ_NEW_TAB_SPONSORED_IMAGE_EARNING_TITLE},
               {"sponsoredImageEnableRewards",
                IDS_WOOTZ_NEW_TAB_SPONSORED_IMAGE_ENABLE_REWARDS},
               {"sponsoredImageNotEarningTitle",
                IDS_WOOTZ_NEW_TAB_SPONSORED_IMAGE_NOT_EARNING_TITLE},
               {"sponsoredImageOffRewardsOnDescription",
                IDS_WOOTZ_NEW_TAB_SPONSORED_IMAGE_OFF_REWARDS_ON_DESCRPTION},
               {"sponsoredImageOnDescription",
                IDS_WOOTZ_NEW_TAB_SPONSORED_IMAGE_ON_DESCRIPTION},
               {"sponsoredImageOnRewardsOnNoCustodianDescription",
                IDS_WOOTZ_NEW_TAB_SPONSORED_IMAGE_ON_REWARDS_ON_NO_CUSTODIAN_DESCRIPTION},
               {"sponsoredImageRewardsOffDescription",
                IDS_WOOTZ_NEW_TAB_SPONSORED_IMAGE_REWARDS_OFF_DESCRIPTION},
               {"topSitesTitle", IDS_WOOTZ_NEW_TAB_TOP_SITES},
               {"statsTitle", IDS_WOOTZ_NEW_TAB_STATS},
               {"clockTitle", IDS_WOOTZ_NEW_TAB_CLOCK},
               {"searchTitle", IDS_WOOTZ_NEW_TAB_SEARCH},
               {"backgroundImageTitle", IDS_WOOTZ_NEW_TAB_BACKGROUND_IMAGE},
               {"settingsNavigateBack", IDS_WOOTZ_NEW_TAB_SETTINGS_BACK},
               {"wootzBackgroundsTitle", IDS_WOOTZ_NEW_TAB_WOOTZ_BACKGROUND},
               {"solidColorTitle", IDS_WOOTZ_NEW_TAB_SOLID_COLOR},
               {"gradientColorTitle", IDS_WOOTZ_NEW_TAB_GRADIENT_COLOR},
               {"refreshBackgroundOnNewTab",
                IDS_WOOTZ_NEW_TAB_REFRESH_BACKGROUND_ON_NEW_TAB},
               {"rewardsOpenPanel", IDS_WOOTZ_NEW_TAB_REWARDS_OPEN_PANEL},

               // search promotion
               {"searchPromotionNTPPopupTitle1",
                IDS_WOOTZ_NEW_TAB_SEARCH_PROMOTION_POPUP_TITLE_1},
               {"searchPromotionNTPPopupTitle2",
                IDS_WOOTZ_NEW_TAB_SEARCH_PROMOTION_POPUP_TITLE_2},
               {"searchPromotionNTPPopupDesc",
                IDS_WOOTZ_NEW_TAB_SEARCH_PROMOTION_POPUP_DESC},
               {"searchPromotionNTPPopupBottom",
                IDS_WOOTZ_NEW_TAB_SEARCH_PROMOTION_POPUP_BOTTOM},
               {"searchPromotionSearchBoxPlaceholderLabel",
                IDS_WOOTZ_NEW_TAB_SEARCH_PROMOTION_SEARCH_BOX_PLACEHOLDER},

               {"wootzNewsTitle", IDS_WOOTZ_NEWS_TITLE},
               {"wootzNewsStatusFetching", IDS_WOOTZ_NEWS_STATUS_FETCHING},
               {"wootzNewsActionRefresh", IDS_WOOTZ_NEWS_ACTION_REFRESH},
               {"wootzNewsScrollHint", IDS_WOOTZ_NEWS_SCROLL_HINT},
               {"wootzNewsResetAction", IDS_WOOTZ_NEWS_RESET_ACTION},
               {"wootzNewsResetConfirm", IDS_WOOTZ_NEWS_RESET_CONFIRM},
               {"wootzNewsCategoryNameAll", IDS_WOOTZ_NEWS_CATEGORY_NAME_ALL},
               {"wootzNewsSourcesTitle", IDS_WOOTZ_NEWS_SOURCES_TITLE},
               {"wootzNewsDisableSourceCommand",
                IDS_WOOTZ_NEWS_DISABLE_SOURCE_COMMAND},
               {"promoted", IDS_WOOTZ_NEWS_PROMOTED},
               {"ad", IDS_WOOTZ_NEWS_DISPLAY_AD_LABEL},

               {"wootzNewsIntroTitle", IDS_WOOTZ_NEWS_INTRO_TITLE},
               {"wootzNewsIntroDescription", IDS_WOOTZ_NEWS_INTRO_DESCRIPTION},
               {"wootzNewsIntroDescriptionTwo",
                IDS_WOOTZ_NEWS_INTRO_DESCRIPTION_TWO},
               {"wootzNewsOptInActionLabel",
                IDS_WOOTZ_NEWS_OPT_IN_ACTION_LABEL},
               {"wootzNewsOptOutActionLabel",
                IDS_WOOTZ_NEWS_OPT_OUT_ACTION_LABEL},
               {"wootzNewsBackToDashboard", IDS_WOOTZ_NEWS_BACK_TO_DASHBOARD},
               {"wootzNewsBackButton", IDS_WOOTZ_NEWS_BACK_BUTTON},
               {"wootzNewsSearchPlaceholderLabel",
                IDS_WOOTZ_NEWS_SEARCH_PLACEHOLDER_LABEL},
               {"wootzNewsChannelsHeader",
                IDS_WOOTZ_NEWS_BROWSE_CHANNELS_HEADER},
               {"wootzNewsViewAllButton", IDS_WOOTZ_NEWS_VIEW_ALL_BUTTON},
               {"wootzNewsAllSourcesHeader", IDS_WOOTZ_NEWS_ALL_SOURCES_HEADER},
               {"wootzNewsFeedsHeading", IDS_WOOTZ_NEWS_FEEDS_HEADING},
               {"wootzNewsFollowButtonFollowing",
                IDS_WOOTZ_NEWS_FOLLOW_BUTTON_FOLLOWING},
               {"wootzNewsFollowButtonNotFollowing",
                IDS_WOOTZ_NEWS_FOLLOW_BUTTON_NOT_FOLLOWING},
               {"wootzNewsDirectSearchButton",
                IDS_WOOTZ_NEWS_DIRECT_SEARCH_BUTTON},
               {"wootzNewsDirectSearchNoResults",
                IDS_WOOTZ_NEWS_DIRECT_SEARCH_NO_RESULTS},
               {"wootzNewsSearchResultsNoResults",
                IDS_WOOTZ_NEWS_SEARCH_RESULTS_NO_RESULTS},
               {"wootzNewsSearchResultsLocalResults",
                IDS_WOOTZ_NEWS_SEARCH_RESULTS_LOCAL_RESULTS},
               {"wootzNewsSearchResultsDirectResults",
                IDS_WOOTZ_NEWS_SEARCH_RESULTS_DIRECT_RESULTS},
               {"wootzNewsSearchQueryTooShort",
                IDS_WOOTZ_NEWS_SEARCH_QUERY_TOO_SHORT},
               {"wootzNewsSuggestionsTitle", IDS_WOOTZ_NEWS_SUGGESTIONS_TITLE},
               {"wootzNewsSuggestionsSubtitle",
                IDS_WOOTZ_NEWS_SUGGESTIONS_SUBTITLE},
               {"wootzNewsErrorHeading", IDS_WOOTZ_NEWS_ERROR_HEADING},
               {"wootzNewsErrorMessage", IDS_WOOTZ_NEWS_ERROR_MESSAGE},
               {"wootzNewsErrorActionLabel", IDS_WOOTZ_NEWS_ERROR_ACTION_LABEL},
               {"wootzNewsNoContentHeading", IDS_WOOTZ_NEWS_NO_CONTENT_HEADING},
               {"wootzNewsNoContentMessage", IDS_WOOTZ_NEWS_NO_CONTENT_MESSAGE},
               {"wootzNewsNoContentActionLabel",
                IDS_WOOTZ_NEWS_NO_CONTENT_ACTION_LABEL},
               {"wootzNewsPopularTitle", IDS_WOOTZ_NEWS_POPULAR_TITLE},
               {"wootzNewsNewsPeek", IDS_WOOTZ_NEWS_NEWS_PEEK},
               {"wootzNewsForYouFeed", IDS_WOOTZ_NEWS_FOR_YOU_FEED},
               {"wootzNewsFollowingFeed", IDS_WOOTZ_NEWS_FOLLOWING_FEED},
               {"wootzNewsPublishersHeading",
                IDS_WOOTZ_NEWS_PUBLISHERS_HEADING},
               {"wootzNewsShowAll", IDS_WOOTZ_NEWS_SHOW_ALL},
               {"wootzNewsShowLess", IDS_WOOTZ_NEWS_SHOW_LESS},
               {"wootzNewsAdvertBadge", IDS_WOOTZ_NEWS_ADVERT_BADGE},
               {"wootzNewsHideContentFrom", IDS_WOOTZ_NEWS_HIDE_CONTENT_FROM},
               {"wootzNewsSourcesRecommendation",
                IDS_WOOTZ_NEWS_SOURCES_RECOMMENDATION},
               {"wootzNewsNoArticlesTitle", IDS_WOOTZ_NEWS_NO_ARTICLES_TITLE},
               {"wootzNewsNoArticlesMessage",
                IDS_WOOTZ_NEWS_NO_ARTICLES_MESSAGE},
               {"wootzNewsOfflineTitle", IDS_WOOTZ_NEWS_OFFLINE_TITLE},
               {"wootzNewsOfflineMessage", IDS_WOOTZ_NEWS_OFFLINE_MESSAGE},
               {"wootzNewsCustomizeFeed", IDS_WOOTZ_NEWS_CUSTOMIZE_FEED},
               {"wootzNewsRefreshFeed", IDS_WOOTZ_NEWS_REFRESH_FEED},
               {"wootzNewsOpenArticlesIn", IDS_WOOTZ_NEWS_OPEN_ARTICLES_IN},
               {"wootzNewsOpenArticlesInNewTab",
                IDS_WOOTZ_NEWS_OPEN_ARTICLES_IN_NEW_TAB},
               {"wootzNewsOpenArticlesInCurrentTab",
                IDS_WOOTZ_NEWS_OPEN_ARTICLES_IN_CURRENT_TAB},
               {"wootzNewsCaughtUp", IDS_WOOTZ_NEWS_CAUGHT_UP},
               {"wootzNewsNewContentAvailable",
                IDS_WOOTZ_NEWS_NEW_CONTENT_AVAILABLE},

               // Wootz News Channels
               {"wootzNewsChannel-Wootz", IDS_WOOTZ_NEWS_CHANNEL_WOOTZ},
               {"wootzNewsChannel-Business", IDS_WOOTZ_NEWS_CHANNEL_BUSINESS},
               {"wootzNewsChannel-Cars", IDS_WOOTZ_NEWS_CHANNEL_CARS},
               {"wootzNewsChannel-Celebrities",
                IDS_WOOTZ_NEWS_CHANNEL_CELEBRITIES},
               {"wootzNewsChannel-Crypto", IDS_WOOTZ_NEWS_CHANNEL_CRYPTO},
               {"wootzNewsChannel-Culture", IDS_WOOTZ_NEWS_CHANNEL_CULTURE},
               {"wootzNewsChannel-Education", IDS_WOOTZ_NEWS_CHANNEL_EDUCATION},
               {"wootzNewsChannel-Entertainment",
                IDS_WOOTZ_NEWS_CHANNEL_ENTERTAINMENT},
               {"wootzNewsChannel-Fashion", IDS_WOOTZ_NEWS_CHANNEL_FASHION},
               {"wootzNewsChannel-Film and TV",
                IDS_WOOTZ_NEWS_CHANNEL_FILM_AND_TV},
               {"wootzNewsChannel-Food", IDS_WOOTZ_NEWS_CHANNEL_FOOD},
               {"wootzNewsChannel-Fun", IDS_WOOTZ_NEWS_CHANNEL_FUN},
               {"wootzNewsChannel-Gaming", IDS_WOOTZ_NEWS_CHANNEL_GAMING},
               {"wootzNewsChannel-Health", IDS_WOOTZ_NEWS_CHANNEL_HEALTH},
               {"wootzNewsChannel-Home", IDS_WOOTZ_NEWS_CHANNEL_HOME},
               {"wootzNewsChannel-Lifestyle", IDS_WOOTZ_NEWS_CHANNEL_LIFESTYLE},
               {"wootzNewsChannel-Music", IDS_WOOTZ_NEWS_CHANNEL_MUSIC},
               {"wootzNewsChannel-Politics", IDS_WOOTZ_NEWS_CHANNEL_POLITICS},
               {"wootzNewsChannel-Regional News",
                IDS_WOOTZ_NEWS_CHANNEL_REGIONAL_NEWS},
               {"wootzNewsChannel-Science", IDS_WOOTZ_NEWS_CHANNEL_SCIENCE},
               {"wootzNewsChannel-Sports", IDS_WOOTZ_NEWS_CHANNEL_SPORTS},
               {"wootzNewsChannel-Travel", IDS_WOOTZ_NEWS_CHANNEL_TRAVEL},
               {"wootzNewsChannel-Technology",
                IDS_WOOTZ_NEWS_CHANNEL_TECHNOLOGY},
               {"wootzNewsChannel-Top News", IDS_WOOTZ_NEWS_CHANNEL_TOP_NEWS},
               {"wootzNewsChannel-Top Sources",
                IDS_WOOTZ_NEWS_CHANNEL_TOP_SOURCES},
               {"wootzNewsChannel-UK News", IDS_WOOTZ_NEWS_CHANNEL_UK_NEWS},
               {"wootzNewsChannel-US News", IDS_WOOTZ_NEWS_CHANNEL_US_NEWS},
               {"wootzNewsChannel-Weather", IDS_WOOTZ_NEWS_CHANNEL_WEATHER},
               {"wootzNewsChannel-World News",
                IDS_WOOTZ_NEWS_CHANNEL_WORLD_NEWS},

               {"addWidget", IDS_WOOTZ_NEW_TAB_WIDGET_ADD},
               {"hideWidget", IDS_WOOTZ_NEW_TAB_WIDGET_HIDE},
               {"rewardsWidgetDesc", IDS_WOOTZ_NEW_TAB_REWARDS_WIDGET_DESC},
               {"cardsToggleTitle", IDS_WOOTZ_NEW_TAB_CARDS_TITLE},
               {"cardsToggleDesc", IDS_WOOTZ_NEW_TAB_CARDS_DESC},
               {"editCardsTitle", IDS_EDIT_CARDS_TITLE},
               {"wootzRewardsTitle", IDS_WOOTZ_NEW_TAB_WOOTZ_REWARDS_TITLE},
// #if !BUILDFLAG(IS_ANDROID) && !BUILDFLAG(IS_IOS)
//                // Private Tab - General
//                {"learnMore", IDS_WOOTZ_PRIVATE_NEW_TAB_LEARN_MORE},
//                {"done", IDS_WOOTZ_PRIVATE_NEW_TAB_DONE},
//                {"headerLabel", IDS_WOOTZ_PRIVATE_NEW_TAB_THIS_IS_A},

//                // Private Tab - Header Private Window
//                {"headerTitle", IDS_WOOTZ_PRIVATE_NEW_TAB_PRIVATE_WINDOW},
//                {"headerText", IDS_WOOTZ_PRIVATE_NEW_TAB_PRIVATE_WINDOW_DESC},
//                {"headerText1", IDS_WOOTZ_PRIVATE_NEW_TAB_PRIVATE_WINDOW_DESC1},
//                {"headerText2", IDS_WOOTZ_PRIVATE_NEW_TAB_PRIVATE_WINDOW_DESC2},
//                {"headerButton",
//                 IDS_WOOTZ_PRIVATE_NEW_TAB_PRIVATE_WINDOW_BUTTON},

//                // Private Tab - Header Private Window with Tor
//                {"headerTorTitle", IDS_WOOTZ_PRIVATE_NEW_TAB_PRIVATE_WINDOW_TOR},
//                {"headerTorText",
//                 IDS_WOOTZ_PRIVATE_NEW_TAB_PRIVATE_WINDOW_TOR_DESC},

//                // Private Tab - Box for DDG
//                {"boxDdgButton", IDS_WOOTZ_PRIVATE_NEW_TAB_BOX_DDG_BUTTON},

//                // Private Tab - Box for Tor
//                {"boxTorLabel", IDS_WOOTZ_PRIVATE_NEW_TAB_BOX_TOR_LABEL},
//                {"boxTorLabel2", IDS_WOOTZ_PRIVATE_NEW_TAB_BOX_TOR_LABEL_2},
//                {"boxTorTitle", IDS_WOOTZ_PRIVATE_NEW_TAB_BOX_TOR_TITLE},

//                // Private Tab - Private Window with Tor - Tor Box
//                {"boxTorText", IDS_WOOTZ_PRIVATE_NEW_TAB_BOX_TOR_TEXT_1},

//                // Private Tab - Private Window - Tor Box
//                {"boxTorText2", IDS_WOOTZ_PRIVATE_NEW_TAB_BOX_TOR_TEXT_2},
//                {"boxTorButton", IDS_WOOTZ_PRIVATE_NEW_TAB_BOX_TOR_BUTTON},
// #endif  // !BUILDFLAG(IS_ANDROID)

               // Rewards widget
               {"rewardsAboutRewards", IDS_REWARDS_WIDGET_ABOUT_REWARDS},
               {"rewardsWootzRewards", IDS_REWARDS_WIDGET_WOOTZ_REWARDS},
               {"rewardsConnectAccount", IDS_REWARDS_CONNECT_ACCOUNT},
               {"rewardsConnectAccountText", IDS_REWARDS_CONNECT_ACCOUNT_TEXT},
               {"rewardsContinue", IDS_REWARDS_WIDGET_CONTINUE},
               {"rewardsEarningsTitle", IDS_REWARDS_ESTIMATED_EARNINGS_TITLE},
               {"rewardsEarningInfoText", IDS_REWARDS_WIDGET_EARNING_INFO_TEXT},
               {"rewardsHowDoesItWork", IDS_REWARDS_WIDGET_HOW_DOES_IT_WORK},
               {"rewardsLearnMore", IDS_REWARDS_LEARN_MORE},
               {"rewardsManageAds", IDS_REWARDS_WALLET_MANAGE_ADS},
               {"rewardsNotNow", IDS_REWARDS_NOT_NOW},
               {"rewardsOptInHeader", IDS_REWARDS_WIDGET_OPT_IN_HEADER},
               {"rewardsOptInTerms", IDS_WOOTZ_REWARDS_ONBOARDING_TERMS},
               {"rewardsOptInText", IDS_REWARDS_WIDGET_OPT_IN_TEXT},
               {"rewardsLogInToSeeBalance", IDS_REWARDS_LOG_IN_TO_SEE_BALANCE},
               {"rewardsPaymentCheckStatus", IDS_REWARDS_PAYMENT_CHECK_STATUS},
               {"rewardsPaymentCompleted", IDS_REWARDS_PAYMENT_COMPLETED},
               {"rewardsPaymentPending", IDS_REWARDS_PAYMENT_PENDING},
               {"rewardsPaymentProcessing", IDS_REWARDS_PAYMENT_PROCESSING},
               {"rewardsPaymentSupport", IDS_REWARDS_PAYMENT_SUPPORT},
               {"rewardsSelectCountryHeader",
                IDS_REWARDS_WIDGET_SELECT_COUNTRY_HEADER},
               {"rewardsSelectCountryText",
                IDS_REWARDS_WIDGET_SELECT_COUNTRY_TEXT},
               {"rewardsSelfCustodyInviteHeader",
                IDS_REWARDS_SELF_CUSTODY_INVITE_HEADER},
               {"rewardsSelfCustodyInviteText",
                IDS_REWARDS_SELF_CUSTODY_INVITE_TEXT},
               {"rewardsTosUpdateHeading", IDS_REWARDS_TOS_UPDATE_HEADING},
               {"rewardsTosUpdateText", IDS_REWARDS_TOS_UPDATE_TEXT},
               {"rewardsTosUpdateLinkText", IDS_REWARDS_TOS_UPDATE_LINK_TEXT},
               {"rewardsTosUpdateButtonLabel",
                IDS_REWARDS_TOS_UPDATE_BUTTON_LABEL},
               {"rewardsSettings", IDS_REWARDS_WIDGET_SETTINGS},
               {"rewardsStartUsingRewards",
                IDS_REWARDS_WIDGET_START_USING_REWARDS},
               {"rewardsBalanceTitle", IDS_REWARDS_WIDGET_BALANCE_TITLE},
               {"rewardsWidgetWootzRewards", IDS_WOOTZ_UI_WOOTZ_REWARDS},
               {"rewardsBrowserCannotReceiveAds",
                IDS_REWARDS_BROWSER_CANNOT_RECEIVE_ADS},
               {"rewardsBrowserNeedsUpdateToSeeAds",
                IDS_REWARDS_BROWSER_NEEDS_UPDATE_TO_SEE_ADS},
               {"rewardsVBATNoticeText1", IDS_REWARDS_VBAT_NOTICE_TEXT1},
               {"rewardsVBATNoticeTitle1", IDS_REWARDS_VBAT_NOTICE_TITLE1},

               {"loading", IDS_WOOTZ_REWARDS_LOADING_LABEL},

               // Wootz Talk  Widget
               {"wootzTalkWidgetTitle", IDS_WOOTZ_TALK_WIDGET_TITLE},
               {"wootzTalkWidgetWelcomeTitle",
                IDS_WOOTZ_TALK_WIDGET_WELCOME_TITLE},
               {"wootzTalkWidgetStartButton",
                IDS_WOOTZ_TALK_WIDGET_START_BUTTON},
               {"wootzTalkWidgetAboutData", IDS_WOOTZ_TALK_WIDGET_ABOUT_DATA},
           }},
          {"wallet",
           {{"wootzWalletsWelcome", IDS_WOOTZ_WALLET_WELCOME},
            {"wootzWalletsDisclosureOne", IDS_WOOTZ_WALLET_DISCLOSURE_ONE},
            {"wootzWalletsDisclosureTwo", IDS_WOOTZ_WALLET_DISCLOSURE_TWO},
            {"wootzWalletsDisclosureThree", IDS_WOOTZ_WALLET_DISCLOSURE_THREE},
            {"wootzWalletsDisclosureFour", IDS_WOOTZ_WALLET_DISCLOSURE_FOUR},
            {"wootzWalletsWootzRewards", IDS_WOOTZ_WALLET_WOOTZ_REWARDS},
            {"wootzWalletsDownloading", IDS_WOOTZ_WALLET_DOWNLOADING},
            {"wootzWalletsDisclosureConfirm",
             IDS_WOOTZ_WALLET_DISCLOSURE_CONFIRM}}},
        //   {"rewards",
        //    {
        //        {"adsCurrentEarnings",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_CURRENT_EARNINGS},
        //        {"adsDescription", IDS_WOOTZ_REWARDS_LOCAL_ADS_DESCRIPTION},
        //        {"adsDescriptionEarn",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_DESCRIPTION_EARN},
        //        {"adsTotalReceivedLabel",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_TOTAL_RECEIVED},
        //        {"adsNotSupportedRegion",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_NOT_SUPPORTED_REGION},
        //        {"adsNotSupportedDevice",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_NOT_SUPPORTED_DEVICE},
        //        {"adsPaymentDate", IDS_WOOTZ_REWARDS_LOCAL_ADS_PAYMENT_DATE},
        //        {"adsPerHour", IDS_WOOTZ_REWARDS_LOCAL_ADS_PER_HOUR},
        //        {"adsPerHour0", IDS_WOOTZ_REWARDS_LOCAL_ADS_PER_HOUR_0},
        //        {"adsPerHour1", IDS_WOOTZ_REWARDS_LOCAL_ADS_PER_HOUR_1},
        //        {"adsPerHour2", IDS_WOOTZ_REWARDS_LOCAL_ADS_PER_HOUR_2},
        //        {"adsPerHour3", IDS_WOOTZ_REWARDS_LOCAL_ADS_PER_HOUR_3},
        //        {"adsPerHour4", IDS_WOOTZ_REWARDS_LOCAL_ADS_PER_HOUR_4},
        //        {"adsPerHour5", IDS_WOOTZ_REWARDS_LOCAL_ADS_PER_HOUR_5},
        //        {"adsPerHour10", IDS_WOOTZ_REWARDS_LOCAL_ADS_PER_HOUR_10},
        //        {"adsSubdivisionTargetingTitle",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_TITLE},
        //        {"adsSubdivisionTargetingDescription",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_DESCRIPTION},
        //        {"adsSubdivisionTargetingLearn",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_LEARN},
        //        {"adsSubdivisionTargetingAutoDetectedAs",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_AUTO_DETECTED_AS},
        //        {"adsSubdivisionTargetingAutoDetect",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_AUTO_DETECT},
        //        {"adsSubdivisionTargetingDisable",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_DISABLE},
        //        {"adsSubdivisionTargetingDisabled",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_SUBDIVISION_TARGETING_DISABLED},
        //        {"adsTitle", IDS_WOOTZ_REWARDS_LOCAL_ADS_TITLE},
        //        {"newTabAdCountLabel", IDS_WOOTZ_REWARDS_NEW_TAB_AD_COUNT_LABEL},
        //        {"notificationAdCountLabel",
        //         IDS_WOOTZ_REWARDS_NOTIFICATION_AD_COUNT_LABEL},
        //        {"searchAdCountLabel", IDS_WOOTZ_REWARDS_SEARCH_AD_COUNT_LABEL},
        //        {"searchAdInfo", IDS_WOOTZ_REWARDS_SEARCH_AD_INFO},
        //        {"searchAdConnectedInfo",
        //         IDS_WOOTZ_REWARDS_SEARCH_AD_CONNECTED_INFO},
        //        {"newsAdCountLabel", IDS_WOOTZ_REWARDS_NEWS_AD_COUNT_LABEL},
        //        {"newsAdInfo", IDS_WOOTZ_REWARDS_NEWS_AD_INFO},
        //        {"newsAdInfoDisabled", IDS_WOOTZ_REWARDS_NEWS_AD_INFO_DISABLED},
        //        {"appErrorTitle", IDS_REWARDS_APP_ERROR_TITLE},

        //        {"bat", IDS_WOOTZ_UI_BAT_REWARDS_TEXT},
        //        {"contributionTitle", IDS_WOOTZ_REWARDS_LOCAL_CONTR_TITLE},
        //        {"contributionDesc", IDS_WOOTZ_REWARDS_LOCAL_CONTR_DESC},
        //        {"contributionMonthly", IDS_WOOTZ_REWARDS_LOCAL_CONTR_MONTHLY},
        //        {"contributionNextDate",
        //         IDS_WOOTZ_REWARDS_LOCAL_CONTR_NEXT_DATE},
        //        {"contributionSites", IDS_WOOTZ_REWARDS_LOCAL_CONTR_SITES},
        //        {"contributionVisitSome",
        //         IDS_WOOTZ_REWARDS_LOCAL_CONTR_VISIT_SOME},
        //        {"contributionMinTime", IDS_WOOTZ_REWARDS_LOCAL_CONTR_MIN_TIME},
        //        {"contributionMinVisits",
        //         IDS_WOOTZ_REWARDS_LOCAL_CONTR_MIN_VISITS},
        //        {"contributionOther", IDS_WOOTZ_REWARDS_LOCAL_CONTR_OTHER},
        //        {"contributionVisit1", IDS_WOOTZ_REWARDS_LOCAL_CONTR_VISIT_1},
        //        {"contributionVisit5", IDS_WOOTZ_REWARDS_LOCAL_CONTR_VISIT_5},
        //        {"contributionVisit10", IDS_WOOTZ_REWARDS_LOCAL_CONTR_VISIT_10},
        //        {"contributionTime5", IDS_WOOTZ_REWARDS_LOCAL_CONTR_TIME_5},
        //        {"contributionTime8", IDS_WOOTZ_REWARDS_LOCAL_CONTR_TIME_8},
        //        {"contributionTime60", IDS_WOOTZ_REWARDS_LOCAL_CONTR_TIME_60},
        //        {"contributionUpTo", IDS_WOOTZ_REWARDS_LOCAL_CONTR_UP_TO},

        //        {"disconnectWalletFailed",
        //         IDS_WOOTZ_REWARDS_LOCAL_SERVER_DISCONNECT_FAILED},
        //        {"donationTitle", IDS_WOOTZ_REWARDS_LOCAL_DONAT_TITLE},
        //        {"donationDesc", IDS_WOOTZ_REWARDS_LOCAL_DONAT_DESC},
        //        {"donationDescLearnMore",
        //         IDS_WOOTZ_REWARDS_LOCAL_DONAT_DESC_LEARN_MORE},
        //        {"donationTotalDonations",
        //         IDS_WOOTZ_REWARDS_LOCAL_DONAT_TOTAL_DONATIONS},
        //        {"donationVisitSome", IDS_WOOTZ_REWARDS_LOCAL_DONAT_VISIT_SOME},
        //        {"monthlyTipsTitle", IDS_WOOTZ_REWARDS_LOCAL_MONTHLY_TIPS_TITLE},
        //        {"monthlyTipsDesc", IDS_WOOTZ_REWARDS_LOCAL_MONTHLY_TIPS_DESC},
        //        {"monthlyTipsEmpty", IDS_WOOTZ_REWARDS_LOCAL_MONTHLY_TIPS_EMPTY},
        //        {"nextContribution", IDS_WOOTZ_REWARDS_LOCAL_NEXT_CONTRIBUTION},
        //        {"redirectModalSomethingWentWrong",
        //         IDS_REWARDS_AUTHORIZE_UNEXPECTED_ERROR_TITLE},
        //        {"redirectModalUnableToCompleteRequest",
        //         IDS_REWARDS_AUTHORIZE_UNEXPECTED_ERROR_TEXT},
        //        {"redirectModalClose",
        //         IDS_WOOTZ_REWARDS_LOCAL_REDIRECT_MODAL_CLOSE},
        //        {"redirectModalDeviceLimitReachedText",
        //         IDS_REWARDS_AUTHORIZE_DEVICE_LIMIT_REACHED_TEXT},
        //        {"redirectModalDeviceLimitReachedTitle",
        //         IDS_REWARDS_AUTHORIZE_DEVICE_LIMIT_REACHED_TITLE},
        //        {"redirectModalFlaggedWalletText1",
        //         IDS_REWARDS_AUTHORIZE_FLAGGED_WALLET_TEXT_1},
        //        {"redirectModalFlaggedWalletText2",
        //         IDS_REWARDS_AUTHORIZE_FLAGGED_WALLET_TEXT_2},
        //        {"redirectModalFlaggedWalletText3",
        //         IDS_REWARDS_AUTHORIZE_FLAGGED_WALLET_TEXT_3},
        //        {"redirectModalFlaggedWalletText4",
        //         IDS_REWARDS_AUTHORIZE_FLAGGED_WALLET_TEXT_4},
        //        {"redirectModalFlaggedWalletTitle",
        //         IDS_REWARDS_AUTHORIZE_FLAGGED_WALLET_TITLE},
        //        {"redirectModalKYCRequiredTitle",
        //         IDS_REWARDS_AUTHORIZE_KYC_REQUIRED_TITLE},
        //        {"redirectModalKYCRequiredText",
        //         IDS_REWARDS_AUTHORIZE_KYC_REQUIRED_TEXT},
        //        {"redirectModalMismatchedCountriesText",
        //         IDS_REWARDS_AUTHORIZE_MISMATCHED_COUNTRIES_TEXT},
        //        {"redirectModalMismatchedCountriesTitle",
        //         IDS_REWARDS_AUTHORIZE_MISMATCHED_COUNTRIES_TITLE},
        //        {"redirectModalMismatchedProviderAccountsText",
        //         IDS_REWARDS_AUTHORIZE_MISMATCHED_PROVIDER_ACCOUNTS_TEXT},
        //        {"redirectModalMismatchedProviderAccountsTitle",
        //         IDS_REWARDS_AUTHORIZE_MISMATCHED_PROVIDER_ACCOUNTS_TITLE},
        //        {"redirectModalProviderUnavailableText1",
        //         IDS_REWARDS_AUTHORIZE_PROVIDER_UNAVAILABLE_TEXT_1},
        //        {"redirectModalProviderUnavailableText2",
        //         IDS_REWARDS_AUTHORIZE_PROVIDER_UNAVAILABLE_TEXT_2},
        //        {"redirectModalProviderUnavailableTitle",
        //         IDS_REWARDS_AUTHORIZE_PROVIDER_UNAVAILABLE_TITLE},
        //        {"redirectModalRegionNotSupportedText1",
        //         IDS_REWARDS_AUTHORIZE_REGION_NOT_SUPPORTED_TEXT_1},
        //        {"redirectModalRegionNotSupportedText2",
        //         IDS_REWARDS_AUTHORIZE_REGION_NOT_SUPPORTED_TEXT_2},
        //        {"redirectModalRegionNotSupportedTitle",
        //         IDS_REWARDS_AUTHORIZE_REGION_NOT_SUPPORTED_TITLE},
        //        {"redirectModalUpholdBATNotAllowedText",
        //         IDS_REWARDS_AUTHORIZE_UPHOLD_BAT_NOT_ALLOWED_TEXT},
        //        {"redirectModalUpholdBATNotAllowedTitle",
        //         IDS_REWARDS_AUTHORIZE_UPHOLD_BAT_NOT_ALLOWED_TITLE},
        //        {"redirectModalUpholdInsufficientCapabilitiesText",
        //         IDS_REWARDS_AUTHORIZE_UPHOLD_INSUFFICIENT_CAPABILITIES_TEXT},
        //        {"redirectModalUpholdInsufficientCapabilitiesTitle",
        //         IDS_REWARDS_AUTHORIZE_UPHOLD_INSUFFICIENT_CAPABILITIES_TITLE},
        //        {"redirectModalWalletOwnershipVerificationFailureText",
        //         IDS_REWARDS_AUTHORIZE_SIGNATURE_VERIFICATION_ERROR_TEXT},
        //        {"redirectModalWalletOwnershipVerificationFailureTitle",
        //         IDS_REWARDS_AUTHORIZE_SIGNATURE_VERIFICATION_ERROR_TITLE},
        //        {"tosAndPp", IDS_WOOTZ_REWARDS_LOCAL_TOS_AND_PP},

        //        {"click", IDS_WOOTZ_REWARDS_LOCAL_ADS_CONFIRMATION_TYPE_CLICK},
        //        {"dismiss",
        //         IDS_WOOTZ_REWARDS_LOCAL_ADS_CONFIRMATION_TYPE_DISMISS},
        //        {"landed", IDS_WOOTZ_REWARDS_LOCAL_ADS_CONFIRMATION_TYPE_LANDED},
        //        {"view", IDS_WOOTZ_REWARDS_LOCAL_ADS_CONFIRMATION_TYPE_VIEW},

        //        {"rewardsBrowserCannotReceiveAds",
        //         IDS_REWARDS_BROWSER_CANNOT_RECEIVE_ADS},
        //        {"rewardsBrowserNeedsUpdateToSeeAds",
        //         IDS_REWARDS_BROWSER_NEEDS_UPDATE_TO_SEE_ADS},

        //        {"activityCopy", IDS_WOOTZ_UI_ACTIVITY_COPY},
        //        {"activityNote", IDS_WOOTZ_UI_ACTIVITY_NOTE},
        //        {"ads", IDS_WOOTZ_UI_ADS},
        //        {"adsCurrentlyViewing", IDS_WOOTZ_UI_ADS_CURRENTLY_VIEWING},
        //        {"adsHistoryNone", IDS_WOOTZ_UI_ADS_HISTORY_NONE},
        //        {"adsHistorySubTitle", IDS_WOOTZ_UI_ADS_HISTORY_SUBTITLE},
        //        {"adsHistoryTitle", IDS_WOOTZ_UI_ADS_HISTORY_TITLE},
        //        {"all", IDS_WOOTZ_UI_ADS_ALL},
        //        {"amount", IDS_WOOTZ_UI_AMOUNT},
        //        {"autoContribute", IDS_WOOTZ_UI_WOOTZ_CONTRIBUTE_TITLE},
        //        {"autoContributeTransaction",
        //         IDS_WOOTZ_UI_WOOTZ_CONTRIBUTE_TRANSACTION},
        //        {"wootzRewards", IDS_WOOTZ_UI_WOOTZ_REWARDS},
        //        {"cancel", IDS_WOOTZ_UI_CANCEL},
        //        {"captchaDrag", IDS_WOOTZ_UI_CAPTCHA_DRAG},
        //        {"captchaTarget", IDS_WOOTZ_UI_CAPTCHA_TARGET},
        //        {"category", IDS_WOOTZ_UI_ADS_CATEGORY},
        //        {"contribute", IDS_WOOTZ_UI_CONTRIBUTE},
        //        {"date", IDS_WOOTZ_UI_DATE},
        //        {"deposits", IDS_WOOTZ_UI_DEPOSITS},
        //        {"description", IDS_WOOTZ_UI_DESCRIPTION},
        //        {"donation", IDS_WOOTZ_UI_DONATION},
        //        {"done", IDS_WOOTZ_UI_DONE},
        //        {"earningsAds", IDS_WOOTZ_UI_EARNINGS_ADS},
        //        {"earningsViewDepositHistory",
        //         IDS_WOOTZ_UI_EARNINGS_VIEW_DEPOSIT_HISTORY},
        //        {"excludeSite", IDS_WOOTZ_UI_EXCLUDE_SITE},
        //        {"excludedSitesText", IDS_WOOTZ_UI_EXCLUDED_SITES},
        //        {"import", IDS_WOOTZ_UI_IMPORT},
        //        {"learnMore", IDS_WOOTZ_UI_LEARN_MORE},
        //        {"markAsInappropriate", IDS_WOOTZ_UI_ADS_MARK_AS_INAPPROPRIATE},
        //        {"markAsInappropriateChecked",
        //         IDS_WOOTZ_UI_ADS_MARK_AS_INAPPROPRIATE_CHECKED},
        //        {"monthlyTipsBang", IDS_WOOTZ_UI_MONTHLY_TIPS_BANG},
        //        {"monthlyTips", IDS_WOOTZ_UI_MONTHLY_TIPS},
        //        {"noActivity", IDS_WOOTZ_UI_NO_ACTIVITY},
        //        {"noAdsHistory", IDS_WOOTZ_UI_ADS_NO_ADS_HISTORY},
        //        {"off", IDS_WOOTZ_UI_OFF},
        //        {"ok", IDS_WOOTZ_UI_OK},
        //        {"on", IDS_WOOTZ_UI_ON},
        //        {"onboardingEarnHeader",
        //         IDS_WOOTZ_REWARDS_ONBOARDING_EARN_HEADER},
        //        {"onboardingEarnText", IDS_WOOTZ_REWARDS_ONBOARDING_EARN_TEXT},
        //        {"onboardingStartUsingRewards",
        //         IDS_WOOTZ_REWARDS_ONBOARDING_START_USING_REWARDS},
        //        {"onboardingStartUsingRewardsTextOnly",
        //         IDS_WOOTZ_REWARDS_ONBOARDING_START_USING_REWARDS_TEXT_ONLY},
        //        {"onboardingTerms", IDS_WOOTZ_REWARDS_ONBOARDING_TERMS},
        //        {"oneTimeDonation", IDS_WOOTZ_UI_ONE_TIME_DONATION},
        //        {"openAdsHistory", IDS_WOOTZ_UI_OPEN_ADS_HISTORY},
        //        {"optOutTooltip", IDS_WOOTZ_UI_ADS_OPT_OUT_TOOLTIP},
        //        {"payment", IDS_WOOTZ_UI_PAYMENT},
        //        {"pinnedSitesHeader", IDS_WOOTZ_UI_PAYMENT_PINNED_SITES_HEADER},
        //        {"pinnedSitesMsg", IDS_WOOTZ_UI_PAYMENT_PINNED_SITES_MSG},
        //        {"pinnedSitesOne", IDS_WOOTZ_UI_PAYMENT_PINNED_SITES_ONE},
        //        {"pinnedSitesTwo", IDS_WOOTZ_UI_PAYMENT_PINNED_SITES_TWO},
        //        {"pinnedSitesThree", IDS_WOOTZ_UI_PAYMENT_PINNED_SITES_THREE},
        //        {"pinnedSitesFour", IDS_WOOTZ_UI_PAYMENT_PINNED_SITES_FOUR},
        //        {"pleaseNote", IDS_WOOTZ_UI_PLEASE_NOTE},
        //        {"print", IDS_WOOTZ_UI_PRINT},
        //        {"processingRequest", IDS_REWARDS_AUTHORIZE_PROCESSING_TEXT},
        //        {"processorWootzTokens", IDS_WOOTZ_UI_PROCESSOR_WOOTZ_TOKENS},
        //        {"processorUphold", IDS_WOOTZ_UI_PROCESSOR_UPHOLD},
        //        {"processorBitflyer", IDS_WOOTZ_UI_PROCESSOR_BITFLYER},
        //        {"processorGemini", IDS_WOOTZ_UI_PROCESSOR_GEMINI},
        //        {"recurring", IDS_WOOTZ_UI_RECURRING},
        //        {"recurringDonations", IDS_WOOTZ_UI_RECURRING_DONATIONS},
        //        {"relaunch", IDS_WOOTZ_UI_RELAUNCH},
        //        {"remove", IDS_WOOTZ_UI_REMOVE},
        //        {"removeAdFromSaved", IDS_WOOTZ_UI_REMOVE_AD_FROM_SAVED},
        //        {"reset", IDS_WOOTZ_UI_RESET},
        //        {"resetWallet", IDS_WOOTZ_UI_RESET_WALLET},
        //        {"clearExcludeList", IDS_WOOTZ_UI_CLEAR_EXCLUDE_LIST},
        //        {"reviewSitesMsg", IDS_WOOTZ_UI_REVIEW_SITE_MSG},
        //        {"rewardsConnectAccount", IDS_REWARDS_CONNECT_ACCOUNT},
        //        {"rewardsContribute", IDS_WOOTZ_UI_REWARDS_CONTRIBUTE},
        //        {"rewardsContributeAttention",
        //         IDS_WOOTZ_UI_REWARDS_CONTRIBUTE_ATTENTION},
        //        {"rewardsLearnMore", IDS_REWARDS_LEARN_MORE},
        //        {"rewardsLogInToSeeBalance", IDS_REWARDS_LOG_IN_TO_SEE_BALANCE},
        //        {"rewardsPaymentCheckStatus", IDS_REWARDS_PAYMENT_CHECK_STATUS},
        //        {"rewardsPaymentCompleted", IDS_REWARDS_PAYMENT_COMPLETED},
        //        {"rewardsPaymentPending", IDS_REWARDS_PAYMENT_PENDING},
        //        {"rewardsPaymentProcessing", IDS_REWARDS_PAYMENT_PROCESSING},
        //        {"rewardsPaymentSupport", IDS_REWARDS_PAYMENT_SUPPORT},
        //        {"rewardsResetConsent", IDS_WOOTZ_UI_REWARDS_RESET_CONSENT},
        //        {"rewardsResetText", IDS_WOOTZ_UI_REWARDS_RESET_TEXT},
        //        {"rewardsSummary", IDS_WOOTZ_UI_REWARDS_SUMMARY},
        //        {"rewardsTosUpdateHeading", IDS_REWARDS_TOS_UPDATE_HEADING},
        //        {"rewardsTosUpdateText", IDS_REWARDS_TOS_UPDATE_TEXT},
        //        {"rewardsTosUpdateLinkText", IDS_REWARDS_TOS_UPDATE_LINK_TEXT},
        //        {"rewardsTosUpdateButtonLabel",
        //         IDS_REWARDS_TOS_UPDATE_BUTTON_LABEL},
        //        {"rewardsVBATNoticeText1", IDS_REWARDS_VBAT_NOTICE_TEXT1},
        //        {"rewardsVBATNoticeTitle1", IDS_REWARDS_VBAT_NOTICE_TITLE1},
        //        {"saved", IDS_WOOTZ_UI_ADS_SAVED},
        //        {"saveAd", IDS_WOOTZ_UI_ADS_SAVE_AD},
        //        {"seeAllItems", IDS_WOOTZ_UI_SEE_ALL_ITEMS},
        //        {"sendTip", IDS_WOOTZ_UI_SEND_TIP},
        //        {"settings", IDS_WOOTZ_UI_SETTINGS},
        //        {"site", IDS_WOOTZ_UI_SITE},
        //        {"tipOnLike", IDS_WOOTZ_UI_TIP_ON_LIKE},
        //        {"token", IDS_WOOTZ_UI_TOKEN},
        //        {"tokens", IDS_WOOTZ_UI_TOKENS},
        //        {"total", IDS_WOOTZ_UI_TOTAL},
        //        {"transactions", IDS_WOOTZ_UI_TRANSACTIONS},
        //        {"type", IDS_WOOTZ_UI_TYPE},
        //        {"unsupportedRegionNoticeHeader",
        //         IDS_WOOTZ_REWARDS_UNSUPPORTED_REGION_NOTICE_HEADER},
        //        {"unsupportedRegionNoticeSubheader",
        //         IDS_WOOTZ_REWARDS_UNSUPPORTED_REGION_NOTICE_SUBHEADER},
        //        {"unsupportedRegionNoticeLearnMore",
        //         IDS_WOOTZ_REWARDS_UNSUPPORTED_REGION_NOTICE_LEARN_MORE},
        //        {"unsupportedRegionNoticeText1",
        //         IDS_WOOTZ_REWARDS_UNSUPPORTED_REGION_NOTICE_TEXT_1},
        //        {"unsupportedRegionNoticeText2",
        //         IDS_WOOTZ_REWARDS_UNSUPPORTED_REGION_NOTICE_TEXT_2},
        //        {"verifiedPublisher", IDS_WOOTZ_UI_VERIFIED_PUBLISHER},
        //        {"viewDetails", IDS_WOOTZ_UI_VIEW_DETAILS},
        //        {"viewMonthly", IDS_WOOTZ_UI_VIEW_MONTHLY},
        //        {"walletActivity", IDS_WOOTZ_UI_WALLET_ACTIVITY},
        //        {"walletBalance", IDS_WOOTZ_UI_WALLET_BALANCE},
        //        {"yourWallet", IDS_WOOTZ_UI_YOUR_WALLET},

        //        {"excludedSites", IDS_WOOTZ_UI_EXCLUDED_SITES_TEXT},
        //        {"removeFromExcluded", IDS_WOOTZ_UI_REMOVE_FROM_EXCLUDED},
        //        {"rewardsExcludedText1", IDS_WOOTZ_UI_REWARDS_EXCLUDED_TEXT_1},
        //        {"rewardsExcludedText2", IDS_WOOTZ_UI_REWARDS_EXCLUDED_TEXT_2},
        //        {"showAll", IDS_WOOTZ_UI_SHOW_ALL},
        //        {"viewedSites", IDS_WOOTZ_UI_VIEWED_SITES},

        //        {"promoLearnMore", IDS_WOOTZ_UI_PROMO_LEARN_MORE},
        //        {"promoDismiss", IDS_WOOTZ_UI_PROMO_DISMISS},

        //        {"bitflyerVerificationPromoTitle",
        //         IDS_WOOTZ_UI_BITFLYER_VERIFICATION_PROMO_TITLE},
        //        {"bitflyerVerificationPromoInfo",
        //         IDS_WOOTZ_UI_BITFLYER_VERIFICATION_PROMO_INFO},

        //        {"wootzCreatorsPromoTitle",
        //         IDS_WOOTZ_UI_WOOTZ_CREATORS_PROMO_TITLE},
        //        {"wootzCreatorsPromoInfo1",
        //         IDS_WOOTZ_UI_WOOTZ_CREATORS_PROMO_INFO_1},
        //        {"wootzCreatorsPromoInfo2",
        //         IDS_WOOTZ_UI_WOOTZ_CREATORS_PROMO_INFO_2},

        //        {"tapNetworkTitle", IDS_WOOTZ_UI_TAP_NETWORK_TITLE},
        //        {"tapNetworkInfo", IDS_WOOTZ_UI_TAP_NETWORK_INFO},
        //        {"tapNetworkDisclaimer", IDS_WOOTZ_UI_TAP_NETWORK_DISCLAIMER},

        //        {"upholdPromoTitle", IDS_WOOTZ_UI_UPHOLD_PROMO_TITLE},
        //        {"upholdPromoInfo", IDS_WOOTZ_UI_UPHOLD_PROMO_INFO},

        //        {"connectAccountText", IDS_REWARDS_CONNECT_ACCOUNT_TEXT},
        //        {"learnMore", IDS_REWARDS_LEARN_MORE},
        //        {"connectWalletCustodialHeader",
        //         IDS_REWARDS_CONNECT_CUSTODIAL_TITLE},
        //        {"connectWalletCustodialTooltip",
        //         IDS_REWARDS_CONNECT_CUSTODIAL_TOOLTIP},
        //        {"connectWalletSelfCustodyHeader",
        //         IDS_REWARDS_CONNECT_SELF_CUSTODY_TITLE},
        //        {"connectWalletSelfCustodyTooltip",
        //         IDS_REWARDS_CONNECT_SELF_CUSTODY_TOOLTIP},
        //        {"connectWalletSelfCustodyNote",
        //         IDS_REWARDS_CONNECT_SELF_CUSTODY_NOTE},
        //        {"connectWalletHeader", IDS_REWARDS_CONNECT_TITLE},
        //        {"connectWalletLearnMore",
        //         IDS_REWARDS_CONNECT_REGIONS_LEARN_MORE_TEXT},
        //        {"connectWalletProviderNotAvailable",
        //         IDS_REWARDS_CONNECT_PROVIDER_NOT_AVAILABLE},
        //        {"connectWalletText", IDS_REWARDS_CONNECT_TEXT},
        //        {"connectWalletSolanaLabel",
        //         IDS_REWARDS_CONNECT_SOLANA_BUTTON_LABEL},
        //        {"connectWalletSolanaMessage",
        //         IDS_REWARDS_CONNECT_SOLANA_MESSAGE},
        //        {"connectWalletSelfCustodyTerms",
        //         IDS_REWARDS_CONNECT_SELF_CUSTODY_TERMS},
        //        {"connectWalletSelfCustodyError",
        //         IDS_REWARDS_CONNECT_SELF_CUSTODY_ERROR},
        //        {"connectWalletLoginText", IDS_REWARDS_CONNECT_LOGIN_TEXT},
        //        {"newBadgeText", IDS_REWARDS_NEW_BADGE_TEXT},
        //        {"contributionPendingUntil",
        //         IDS_WOOTZ_REWARDS_CONTRIBUTION_PENDING_UNTIL},

        //        {"walletAccountLink", IDS_REWARDS_WALLET_ACCOUNT_LINK},
        //        {"walletAutoContribute", IDS_REWARDS_WALLET_AUTO_CONTRIBUTE},
        //        {"walletDisconnected", IDS_REWARDS_WALLET_DISCONNECTED},
        //        {"walletEstimatedEarnings",
        //         IDS_REWARDS_ESTIMATED_EARNINGS_TITLE},
        //        {"walletLogIntoYourAccount",
        //         IDS_REWARDS_WALLET_LOG_INTO_YOUR_ACCOUNT},
        //        {"walletMonthlyTips", IDS_REWARDS_WALLET_MONTHLY_TIPS},
        //        {"walletOneTimeTips", IDS_REWARDS_WALLET_ONE_TIME_TIPS},
        //        {"walletRewardsFromAds", IDS_REWARDS_WALLET_REWARDS_FROM_ADS},
        //        {"walletRewardsSummary", IDS_REWARDS_WALLET_REWARDS_SUMMARY},
        //        {"walletUnverified", IDS_REWARDS_WALLET_UNVERIFIED},
        //        {"walletViewStatement", IDS_REWARDS_WALLET_VIEW_STATEMENT},
        //        {"walletVerified", IDS_REWARDS_WALLET_VERIFIED},
        //        {"walletBalanceTitle", IDS_REWARDS_WALLET_BALANCE_TITLE},
        //        {"walletEarningInfoText", IDS_REWARDS_WIDGET_EARNING_INFO_TEXT},

        //        {"loading", IDS_WOOTZ_REWARDS_LOADING_LABEL},
        //    }},
          {"adblock",
           {
               {"additionalFiltersTitle", IDS_ADBLOCK_ADDITIONAL_FILTERS_TITLE},
               {"additionalFiltersWarning",
                IDS_ADBLOCK_ADDITIONAL_FILTERS_WARNING},
               {"adsBlocked", IDS_ADBLOCK_TOTAL_ADS_BLOCKED},
               {"customFiltersTitle", IDS_ADBLOCK_CUSTOM_FILTERS_TITLE},
               {"customFiltersInstructions",
                IDS_ADBLOCK_CUSTOM_FILTERS_INSTRUCTIONS},
               {"customListSubscriptionsTitle",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_TITLE},
               {"customListSubscriptionsInstructions",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_INSTRUCTIONS},
               {"customListSubscriptionsDisclaimer",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_DISCLAIMER},

               {"customListSubscriptionsEnterSubscriptionUrlPlaceholder",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_ENTER_SUBSCRIPTION_URL_PLACEHOLDER},
               {"customListSubscriptionsSubmitNewSubscription",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_SUBMIT_NEW_SUBSCRIPTION},
               {"customListSubscriptionsCancelAddSubscription",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_CANCEL_ADD_SUBSCRIPTION},
               {"customListSubscriptionsAddNewFilterList",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_ADD_NEW_FILTER_LIST},
               {"customListSubscriptionsTableFilterListColumn",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_TABLE_FILTER_LIST_COLUMN},
               {"customListSubscriptionsTableLastUpdatedColumn",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_TABLE_LAST_UPDATED_COLUMN},
               {"customListSubscriptionsTriggerUpdate",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_TRIGGER_UPDATE},
               {"customListSubscriptionsViewListSource",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_VIEW_LIST_SOURCE},
               {"customListSubscriptionsUnsubscribe",
                IDS_ADBLOCK_CUSTOM_LIST_SUBSCRIPTIONS_UNSUBSCRIBE},
           }},
          {"rewards-internals",
           {
               {"adDiagnosticId", IDS_WOOTZ_REWARDS_INTERNALS_AD_DIAGNOSTIC_ID},
               {"adDiagnosticInfo",
                IDS_WOOTZ_REWARDS_INTERNALS_AD_DIAGNOSTIC_INFO},
               {"adsNotInitialized",
                IDS_WOOTZ_REWARDS_INTERNALS_ADS_NOT_INITIALIZED},
               {"amount", IDS_WOOTZ_REWARDS_INTERNALS_AMOUNT},
               {"autoRefresh", IDS_WOOTZ_REWARDS_INTERNALS_AUTO_REFRESH},
               {"balanceInfo", IDS_WOOTZ_REWARDS_INTERNALS_BALANCE_INFO},
               {"bat", IDS_WOOTZ_UI_BAT_TEXT},
               {"bootStamp", IDS_WOOTZ_REWARDS_INTERNALS_BOOT_STAMP},
               {"clearButton", IDS_WOOTZ_REWARDS_INTERNALS_CLEAR_BUTTON},
               {"contributedAmount",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTED_AMOUNT},
               {"contributionCreatedAt",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTED_CREATED_AT},
               {"contribution", IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION},
               {"contributionProcessor",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_PROCESSOR},
               {"contributionStep",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP},
               {"contributionStepAutoContributeTableEmpty",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_AUTO_CONTRIBUTE_TABLE_EMPTY},
               {"contributionStepNotEnoughFunds",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_NOT_ENOUGH_FUNDS},
               {"contributionStepFailed",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_FAILED},
               {"contributionStepCompleted",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_COMPLETED},
               {"contributionStepNo",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_NO},
               {"contributionStepStart",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_START},
               {"contributionStepPrepare",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_PREPARE},
               {"contributionStepReserve",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_RESERVE},
               {"contributionStepExternalTransaction",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_EXTERNAL_TRANSACTION},
               {"contributionStepCreds",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_CREDS},
               {"contributionStepRewardsOff",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_REWARDS_OFF},
               {"contributionStepAutoContributeOff",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_AUTO_CONTRIBUTE_OFF},
               {"contributionStepRetryCount",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_STEP_RETRY_COUNT},
               {"eventLogKey", IDS_WOOTZ_REWARDS_INTERNALS_EVENT_LOG_KEY},
               {"eventLogValue", IDS_WOOTZ_REWARDS_INTERNALS_EVENT_LOG_VALUE},
               {"eventLogTime", IDS_WOOTZ_REWARDS_INTERNALS_EVENT_LOG_TIME},
               {"mainDisclaimer", IDS_WOOTZ_REWARDS_INTERNALS_MAIN_DISCLAIMER},
               {"logDisclaimer", IDS_WOOTZ_REWARDS_INTERNALS_LOG_DISCLAIMER},
               {"rewardsTypeAuto",
                IDS_WOOTZ_REWARDS_INTERNALS_REWARDS_TYPE_AUTO},
               {"rewardsTypeOneTimeTip",
                IDS_WOOTZ_REWARDS_INTERNALS_REWARDS_TYPE_ONE_TIME_TIP},
               {"rewardsTypeRecurringTip",
                IDS_WOOTZ_REWARDS_INTERNALS_REWARDS_TYPE_RECURRING_TIP},
               {"contributionType",
                IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTION_TYPE},
               {"contributions", IDS_WOOTZ_REWARDS_INTERNALS_CONTRIBUTIONS},
               {"externalWalletType",
                IDS_WOOTZ_REWARDS_INTERNALS_EXTERNAL_WALLET_TYPE},
               {"externalWalletAccount",
                IDS_WOOTZ_REWARDS_INTERNALS_EXTERNAL_WALLET_ACCOUNT},
               {"downloadButton", IDS_WOOTZ_REWARDS_INTERNALS_DOWNLOAD_BUTTON},
               {"externalWallet", IDS_WOOTZ_REWARDS_INTERNALS_EXTERNAL_WALLET},
               {"invalid", IDS_WOOTZ_REWARDS_INTERNALS_INVALID},
               {"keyInfoSeed", IDS_WOOTZ_REWARDS_INTERNALS_KEY_INFO_SEED},
               {"logNotice", IDS_WOOTZ_REWARDS_INTERNALS_LOG_NOTICE},
               {"mainTitle", IDS_WOOTZ_REWARDS_INTERNALS_MAIN_TITLE},
               {"notSet", IDS_WOOTZ_REWARDS_INTERNALS_NOT_SET},
               {"personaId", IDS_WOOTZ_REWARDS_INTERNALS_PERSONA_ID},
               {"processorWootzTokens", IDS_WOOTZ_UI_PROCESSOR_WOOTZ_TOKENS},
               {"processorUphold", IDS_WOOTZ_UI_PROCESSOR_UPHOLD},
               {"processorBitflyer", IDS_WOOTZ_UI_PROCESSOR_BITFLYER},
               {"processorGemini", IDS_WOOTZ_UI_PROCESSOR_GEMINI},
               {"processorZebPay", IDS_WOOTZ_UI_PROCESSOR_ZEBPAY},
               {"processorSolana", IDS_WOOTZ_UI_PROCESSOR_SOLANA},
               {"refreshButton", IDS_WOOTZ_REWARDS_INTERNALS_REFRESH_BUTTON},
               {"retryCount", IDS_WOOTZ_REWARDS_INTERNALS_RETRY_COUNT},
               {"rewardsCountry", IDS_WOOTZ_REWARDS_INTERNALS_REWARDS_COUNTRY},
               {"tabAdDiagnostics",
                IDS_WOOTZ_REWARDS_INTERNALS_TAB_AD_DIAGNOSTICS},
               {"tabGeneralInfo", IDS_WOOTZ_REWARDS_INTERNALS_TAB_GENERAL_INFO},
               {"tabLogs", IDS_WOOTZ_REWARDS_INTERNALS_TAB_LOGS},
               {"tabContributions",
                IDS_WOOTZ_REWARDS_INTERNALS_TAB_CONTRIBUTIONS},
               {"tabEventLogs", IDS_WOOTZ_REWARDS_INTERNALS_TAB_EVENT_LOGS},
               {"totalAmount", IDS_WOOTZ_REWARDS_INTERNALS_TOTAL_AMOUNT},
               {"totalBalance", IDS_WOOTZ_REWARDS_INTERNALS_TOTAL_BALANCE},
               {"userId", IDS_WOOTZ_REWARDS_INTERNALS_USER_ID},
               {"valid", IDS_WOOTZ_REWARDS_INTERNALS_VALID},
               {"walletAddress", IDS_WOOTZ_REWARDS_INTERNALS_WALLET_ADDRESS},
               {"walletHistory", IDS_WOOTZ_REWARDS_INTERNALS_WALLET_HISTORY},
               {"walletInfo", IDS_WOOTZ_REWARDS_INTERNALS_WALLET_INFO},
               {"walletNotCreated",
                IDS_WOOTZ_REWARDS_INTERNALS_WALLET_NOT_CREATED},
               {"walletPaymentId",
                IDS_WOOTZ_REWARDS_INTERNALS_WALLET_PAYMENT_ID},
               {"walletStatus", IDS_WOOTZ_REWARDS_INTERNALS_WALLET_STATUS},
               {"walletStatusNotConnected",
                IDS_WOOTZ_REWARDS_INTERNALS_WALLET_STATUS_NOT_CONNECTED},
               {"walletStatusConnected",
                IDS_WOOTZ_REWARDS_INTERNALS_WALLET_STATUS_CONNECTED},
               {"walletStatusDisconnected",
                IDS_WOOTZ_REWARDS_INTERNALS_WALLET_STATUS_DISCONNECTED},
               {"walletCreationEnvironment",
                IDS_WOOTZ_REWARDS_INTERNALS_WALLET_CREATION_ENVIRONMENT},
               {"currentEnvironment",
                IDS_WOOTZ_REWARDS_INTERNALS_CURRENT_ENVIRONMENT},

               {"loading", IDS_WOOTZ_REWARDS_LOADING_LABEL},
           }},
          {
// #if BUILDFLAG(ENABLE_TOR)
//               "tor-internals",
//               {
//                   {"tabGeneralInfo", IDS_TOR_INTERNALS_TAB_GENERAL_INFO},
//                   {"tabLogs", IDS_TOR_INTERNALS_TAB_LOGS},
//                   {"torControlEvents", IDS_TOR_INTERNALS_TOR_CONTROL_EVENTS},
//                   {"torVersion", IDS_TOR_INTERNALS_TOR_VERSION},
//                   {"torPid", IDS_TOR_INTERNALS_TOR_PID},
//                   {"torProxyURI", IDS_TOR_INTERNALS_TOR_PROXY_URI},
//                   {"torConnectionStatus",
//                    IDS_TOR_INTERNALS_TOR_CONNECTION_STATUS},
//                   {"torInitProgress", IDS_TOR_INTERNALS_TOR_INIT_PROGRESS},
//               }},
//           {
// #endif
// #if !BUILDFLAG(IS_ANDROID) && !BUILDFLAG(IS_IOS)
//               "webcompat",
//               {
//                   // Report modal
//                   {"reportModalTitle",
//                    IDS_WOOTZ_WEBCOMPATREPORTER_REPORT_MODAL_TITLE},
//                   {"reportExplanation",
//                    IDS_WOOTZ_WEBCOMPATREPORTER_REPORT_EXPLANATION},
//                   {"reportNonHttpExplanation",
//                    IDS_WOOTZ_WEBCOMPATREPORTER_REPORT_NON_HTTP_EXPLANATION},
//                   {"reportLocalExplanation",
//                    IDS_WOOTZ_WEBCOMPATREPORTER_REPORT_LOCAL_EXPLANATION},
//                   {"reportErrorPageExplanation",
//                    IDS_WOOTZ_WEBCOMPATREPORTER_REPORT_ERROR_PAGE_EXPLANATION},
//                   {"reportDisclaimer",
//                    IDS_WOOTZ_WEBCOMPATREPORTER_REPORT_DISCLAIMER2},
//                   {"reportInfoLink", IDS_WOOTZ_WEBCOMPATREPORTER_INFO_LINK},
//                   {"reportDetails", IDS_WOOTZ_WEBCOMPATREPORTER_REPORT_DETAILS},
//                   {"reportContactPlaceholder",
//                    IDS_WOOTZ_WEBCOMPATREPORTER_REPORT_CONTACT_PLACEHOLDER},
//                   {"reportContactLabel",
//                    IDS_WOOTZ_WEBCOMPATREPORTER_REPORT_CONTACT_LABEL},
//                   {"attachScreenshotLabel",
//                    IDS_WOOTZ_WEBCOMPATREPORTER_ATTACH_SCREENSHOT_LABEL},
//                   {"viewScreenshotLabel",
//                    IDS_WOOTZ_WEBCOMPATREPORTER_VIEW_SCREENSHOT_LABEL},
//                   {"cancel", IDS_WOOTZ_WEBCOMPATREPORTER_CANCEL},
//                   {"close", IDS_WOOTZ_WEBCOMPATREPORTER_CLOSE},
//                   {"submit", IDS_WOOTZ_WEBCOMPATREPORTER_SUBMIT},
//                   // Confirmation modal
//                   {"thankYou", IDS_WOOTZ_WEBCOMPATREPORTER_THANK_YOU},
//                   {"confirmationNotice",
//                    IDS_WOOTZ_WEBCOMPATREPORTER_CONFIRMATION_NOTICE},
//               }
// #endif
          },
      }};

  if (auto it = kLocalizedStrings->find(webui_name);
      it != kLocalizedStrings->end()) {
    return it->second;
  }
  return {};
}  // NOLINT (readability/fn_size)

}  // namespace wootz
